<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '00501' => ['state' => 'NY', 'cities' => ['Holtsville']],
    '00544' => ['state' => 'NY', 'cities' => ['Holtsville']],
];
