<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '00801' => ['state' => 'VI', 'cities' => ['St Thomas']],
    '00802' => ['state' => 'VI', 'cities' => ['St Thomas']],
    '00803' => ['state' => 'VI', 'cities' => ['St Thomas']],
    '00804' => ['state' => 'VI', 'cities' => ['St Thomas']],
    '00805' => ['state' => 'VI', 'cities' => ['St Thomas']],
    '00820' => ['state' => 'VI', 'cities' => ['Christiansted']],
    '00821' => ['state' => 'VI', 'cities' => ['Christiansted']],
    '00822' => ['state' => 'VI', 'cities' => ['Christiansted']],
    '00823' => ['state' => 'VI', 'cities' => ['Christiansted']],
    '00824' => ['state' => 'VI', 'cities' => ['Christiansted']],
    '00830' => ['state' => 'VI', 'cities' => ['St John']],
    '00831' => ['state' => 'VI', 'cities' => ['St John']],
    '00840' => ['state' => 'VI', 'cities' => ['Frederiksted']],
    '00841' => ['state' => 'VI', 'cities' => ['Frederiksted']],
    '00850' => ['state' => 'VI', 'cities' => ['Kingshill']],
    '00851' => ['state' => 'VI', 'cities' => ['Kingshill']],
];
