<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '01101' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01102' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01103' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01104' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01105' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01106' => ['state' => 'MA', 'cities' => ['Longmeadow']],
    '01107' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01108' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01109' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01111' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01115' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01116' => ['state' => 'MA', 'cities' => ['Longmeadow']],
    '01118' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01119' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01128' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01129' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01138' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01139' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01144' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01151' => ['state' => 'MA', 'cities' => ['Indian Orchard']],
    '01152' => ['state' => 'MA', 'cities' => ['Springfield']],
    '01199' => ['state' => 'MA', 'cities' => ['Springfield']],
];
