<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '01420' => ['state' => 'MA', 'cities' => ['Fitchburg']],
    '01430' => ['state' => 'MA', 'cities' => ['Ashburnham']],
    '01431' => ['state' => 'MA', 'cities' => ['Ashby']],
    '01432' => ['state' => 'MA', 'cities' => ['Ayer']],
    '01434' => ['state' => 'MA', 'cities' => ['Devens']],
    '01436' => ['state' => 'MA', 'cities' => ['Baldwinville']],
    '01438' => ['state' => 'MA', 'cities' => ['East Templeton']],
    '01440' => ['state' => 'MA', 'cities' => ['Gardner']],
    '01441' => ['state' => 'MA', 'cities' => ['Westminster']],
    '01450' => ['state' => 'MA', 'cities' => ['Groton']],
    '01451' => ['state' => 'MA', 'cities' => ['Harvard']],
    '01452' => ['state' => 'MA', 'cities' => ['Hubbardston']],
    '01453' => ['state' => 'MA', 'cities' => ['Leominster']],
    '01460' => ['state' => 'MA', 'cities' => ['Littleton']],
    '01462' => ['state' => 'MA', 'cities' => ['Lunenburg']],
    '01463' => ['state' => 'MA', 'cities' => ['Pepperell']],
    '01464' => ['state' => 'MA', 'cities' => ['Shirley']],
    '01467' => ['state' => 'MA', 'cities' => ['Still River']],
    '01468' => ['state' => 'MA', 'cities' => ['Templeton']],
    '01469' => ['state' => 'MA', 'cities' => ['Townsend']],
    '01470' => ['state' => 'MA', 'cities' => ['Groton']],
    '01471' => ['state' => 'MA', 'cities' => ['Groton']],
    '01472' => ['state' => 'MA', 'cities' => ['West Groton']],
    '01473' => ['state' => 'MA', 'cities' => ['Westminster']],
    '01474' => ['state' => 'MA', 'cities' => ['West Townsend']],
    '01475' => ['state' => 'MA', 'cities' => ['Winchendon']],
];
