<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '01601' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01602' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01603' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01604' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01605' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01606' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01607' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01608' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01609' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01610' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01611' => ['state' => 'MA', 'cities' => ['Cherry Valley']],
    '01612' => ['state' => 'MA', 'cities' => ['Paxton']],
    '01613' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01614' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01615' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01653' => ['state' => 'MA', 'cities' => ['Worcester']],
    '01655' => ['state' => 'MA', 'cities' => ['Worcester']],
];
