<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '02201' => ['state' => 'MA', 'cities' => ['Boston']],
    '02203' => ['state' => 'MA', 'cities' => ['Boston']],
    '02204' => ['state' => 'MA', 'cities' => ['Boston']],
    '02205' => ['state' => 'MA', 'cities' => ['Boston']],
    '02206' => ['state' => 'MA', 'cities' => ['Boston']],
    '02210' => ['state' => 'MA', 'cities' => ['Boston']],
    '02211' => ['state' => 'MA', 'cities' => ['Boston']],
    '02212' => ['state' => 'MA', 'cities' => ['Boston']],
    '02215' => ['state' => 'MA', 'cities' => ['Boston']],
    '02217' => ['state' => 'MA', 'cities' => ['Boston']],
    '02222' => ['state' => 'MA', 'cities' => ['Boston']],
    '02238' => ['state' => 'MA', 'cities' => ['Cambridge']],
    '02241' => ['state' => 'MA', 'cities' => ['Boston']],
    '02266' => ['state' => 'MA', 'cities' => ['Boston']],
    '02269' => ['state' => 'MA', 'cities' => ['Quincy']],
    '02283' => ['state' => 'MA', 'cities' => ['Boston']],
    '02284' => ['state' => 'MA', 'cities' => ['Boston']],
    '02293' => ['state' => 'MA', 'cities' => ['Boston']],
    '02297' => ['state' => 'MA', 'cities' => ['Boston']],
    '02298' => ['state' => 'MA', 'cities' => ['Boston']],
];
