<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '02532' => ['state' => 'MA', 'cities' => ['Buzzards Bay']],
    '02534' => ['state' => 'MA', 'cities' => ['Cataumet']],
    '02535' => ['state' => 'MA', 'cities' => ['Chilmark']],
    '02536' => ['state' => 'MA', 'cities' => ['East Falmouth']],
    '02537' => ['state' => 'MA', 'cities' => ['East Sandwich']],
    '02538' => ['state' => 'MA', 'cities' => ['East Wareham']],
    '02539' => ['state' => 'MA', 'cities' => ['Edgartown']],
    '02540' => ['state' => 'MA', 'cities' => ['Falmouth']],
    '02541' => ['state' => 'MA', 'cities' => ['Falmouth']],
    '02542' => ['state' => 'MA', 'cities' => ['Buzzards Bay']],
    '02543' => ['state' => 'MA', 'cities' => ['Woods Hole']],
    '02552' => ['state' => 'MA', 'cities' => ['Menemsha']],
    '02553' => ['state' => 'MA', 'cities' => ['Monument Beach']],
    '02554' => ['state' => 'MA', 'cities' => ['Nantucket']],
    '02556' => ['state' => 'MA', 'cities' => ['North Falmouth']],
    '02557' => ['state' => 'MA', 'cities' => ['Oak Bluffs']],
    '02558' => ['state' => 'MA', 'cities' => ['Onset']],
    '02559' => ['state' => 'MA', 'cities' => ['Pocasset']],
    '02561' => ['state' => 'MA', 'cities' => ['Sagamore']],
    '02562' => ['state' => 'MA', 'cities' => ['Sagamore Beach']],
    '02563' => ['state' => 'MA', 'cities' => ['Sandwich']],
    '02564' => ['state' => 'MA', 'cities' => ['Siasconset']],
    '02568' => ['state' => 'MA', 'cities' => ['Vineyard Haven']],
    '02571' => ['state' => 'MA', 'cities' => ['Wareham']],
    '02574' => ['state' => 'MA', 'cities' => ['West Falmouth']],
    '02575' => ['state' => 'MA', 'cities' => ['West Tisbury']],
    '02576' => ['state' => 'MA', 'cities' => ['West Wareham']],
    '02584' => ['state' => 'MA', 'cities' => ['Nantucket']],
];
