<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '02901' => ['state' => 'RI', 'cities' => ['Providence']],
    '02902' => ['state' => 'RI', 'cities' => ['Providence']],
    '02903' => ['state' => 'RI', 'cities' => ['Providence']],
    '02904' => ['state' => 'RI', 'cities' => ['Providence']],
    '02905' => ['state' => 'RI', 'cities' => ['Providence']],
    '02906' => ['state' => 'RI', 'cities' => ['Providence']],
    '02907' => ['state' => 'RI', 'cities' => ['Providence']],
    '02908' => ['state' => 'RI', 'cities' => ['Providence']],
    '02909' => ['state' => 'RI', 'cities' => ['Providence']],
    '02910' => ['state' => 'RI', 'cities' => ['Cranston']],
    '02911' => ['state' => 'RI', 'cities' => ['North Providence']],
    '02912' => ['state' => 'RI', 'cities' => ['Providence']],
    '02914' => ['state' => 'RI', 'cities' => ['East Providence']],
    '02915' => ['state' => 'RI', 'cities' => ['Riverside']],
    '02916' => ['state' => 'RI', 'cities' => ['Rumford']],
    '02917' => ['state' => 'RI', 'cities' => ['Smithfield']],
    '02918' => ['state' => 'RI', 'cities' => ['Providence']],
    '02919' => ['state' => 'RI', 'cities' => ['Johnston']],
    '02920' => ['state' => 'RI', 'cities' => ['Cranston']],
    '02921' => ['state' => 'RI', 'cities' => ['Cranston']],
    '02940' => ['state' => 'RI', 'cities' => ['Providence']],
];
