<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03101' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03102' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03103' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03104' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03105' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03106' => ['state' => 'NH', 'cities' => ['Hooksett']],
    '03108' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03109' => ['state' => 'NH', 'cities' => ['Manchester']],
    '03110' => ['state' => 'NH', 'cities' => ['Bedford']],
    '03111' => ['state' => 'NH', 'cities' => ['Manchester']],
];
