<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03301' => ['state' => 'NH', 'cities' => ['Concord']],
    '03302' => ['state' => 'NH', 'cities' => ['Concord']],
    '03303' => ['state' => 'NH', 'cities' => ['Concord']],
    '03304' => ['state' => 'NH', 'cities' => ['Bow']],
    '03305' => ['state' => 'NH', 'cities' => ['Concord']],
    '03307' => ['state' => 'NH', 'cities' => ['Loudon']],
];
