<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03431' => ['state' => 'NH', 'cities' => ['Keene']],
    '03435' => ['state' => 'NH', 'cities' => ['Keene']],
    '03440' => ['state' => 'NH', 'cities' => ['Antrim']],
    '03441' => ['state' => 'NH', 'cities' => ['Ashuelot']],
    '03442' => ['state' => 'NH', 'cities' => ['Bennington']],
    '03443' => ['state' => 'NH', 'cities' => ['Chesterfield']],
    '03444' => ['state' => 'NH', 'cities' => ['Dublin']],
    '03445' => ['state' => 'NH', 'cities' => ['Sullivan']],
    '03446' => ['state' => 'NH', 'cities' => ['Swanzey']],
    '03447' => ['state' => 'NH', 'cities' => ['Fitzwilliam']],
    '03448' => ['state' => 'NH', 'cities' => ['Gilsum']],
    '03449' => ['state' => 'NH', 'cities' => ['Hancock']],
    '03450' => ['state' => 'NH', 'cities' => ['Harrisville']],
    '03451' => ['state' => 'NH', 'cities' => ['Hinsdale']],
    '03452' => ['state' => 'NH', 'cities' => ['Jaffrey']],
    '03455' => ['state' => 'NH', 'cities' => ['Marlborough']],
    '03456' => ['state' => 'NH', 'cities' => ['Marlow']],
    '03457' => ['state' => 'NH', 'cities' => ['Nelson']],
    '03458' => ['state' => 'NH', 'cities' => ['Peterborough']],
    '03461' => ['state' => 'NH', 'cities' => ['Rindge']],
    '03462' => ['state' => 'NH', 'cities' => ['Spofford']],
    '03464' => ['state' => 'NH', 'cities' => ['Stoddard']],
    '03465' => ['state' => 'NH', 'cities' => ['Troy']],
    '03466' => ['state' => 'NH', 'cities' => ['West Chesterfield']],
    '03467' => ['state' => 'NH', 'cities' => ['Westmoreland']],
    '03468' => ['state' => 'NH', 'cities' => ['West Peterborough']],
    '03469' => ['state' => 'NH', 'cities' => ['West Swanzey']],
    '03470' => ['state' => 'NH', 'cities' => ['Winchester']],
];
