<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03561' => ['state' => 'NH', 'cities' => ['Littleton']],
    '03570' => ['state' => 'NH', 'cities' => ['Berlin']],
    '03574' => ['state' => 'NH', 'cities' => ['Bethlehem']],
    '03575' => ['state' => 'NH', 'cities' => ['Bretton Woods']],
    '03576' => ['state' => 'NH', 'cities' => ['Colebrook']],
    '03579' => ['state' => 'NH', 'cities' => ['Errol']],
    '03580' => ['state' => 'NH', 'cities' => ['Franconia']],
    '03581' => ['state' => 'NH', 'cities' => ['Gorham']],
    '03582' => ['state' => 'NH', 'cities' => ['Groveton']],
    '03583' => ['state' => 'NH', 'cities' => ['Jefferson']],
    '03584' => ['state' => 'NH', 'cities' => ['Lancaster']],
    '03585' => ['state' => 'NH', 'cities' => ['Lisbon']],
    '03586' => ['state' => 'NH', 'cities' => ['Sugar Hill']],
    '03588' => ['state' => 'NH', 'cities' => ['Milan']],
    '03589' => ['state' => 'NH', 'cities' => ['Mount Washington']],
    '03590' => ['state' => 'NH', 'cities' => ['North Stratford']],
    '03592' => ['state' => 'NH', 'cities' => ['Pittsburg']],
    '03593' => ['state' => 'NH', 'cities' => ['Randolph']],
    '03595' => ['state' => 'NH', 'cities' => ['Twin Mountain']],
    '03597' => ['state' => 'NH', 'cities' => ['West Stewartstown']],
    '03598' => ['state' => 'NH', 'cities' => ['Whitefield']],
];
