<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03601' => ['state' => 'NH', 'cities' => ['Acworth']],
    '03602' => ['state' => 'NH', 'cities' => ['Alstead']],
    '03603' => ['state' => 'NH', 'cities' => ['Charlestown']],
    '03604' => ['state' => 'NH', 'cities' => ['Drewsville']],
    '03605' => ['state' => 'NH', 'cities' => ['Lempster']],
    '03607' => ['state' => 'NH', 'cities' => ['South Acworth']],
    '03608' => ['state' => 'NH', 'cities' => ['Walpole']],
    '03609' => ['state' => 'NH', 'cities' => ['North Walpole']],
];
