<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '03901' => ['state' => 'ME', 'cities' => ['Berwick']],
    '03902' => ['state' => 'ME', 'cities' => ['Cape Neddick']],
    '03903' => ['state' => 'ME', 'cities' => ['Eliot']],
    '03904' => ['state' => 'ME', 'cities' => ['Kittery']],
    '03905' => ['state' => 'ME', 'cities' => ['Kittery Point']],
    '03906' => ['state' => 'ME', 'cities' => ['North Berwick']],
    '03907' => ['state' => 'ME', 'cities' => ['Ogunquit']],
    '03908' => ['state' => 'ME', 'cities' => ['South Berwick']],
    '03909' => ['state' => 'ME', 'cities' => ['York']],
    '03910' => ['state' => 'ME', 'cities' => ['York Beach']],
    '03911' => ['state' => 'ME', 'cities' => ['York Harbor']],
];
