<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '04101' => ['state' => 'ME', 'cities' => ['Portland']],
    '04102' => ['state' => 'ME', 'cities' => ['Portland']],
    '04103' => ['state' => 'ME', 'cities' => ['Portland']],
    '04104' => ['state' => 'ME', 'cities' => ['Portland']],
    '04105' => ['state' => 'ME', 'cities' => ['Falmouth']],
    '04106' => ['state' => 'ME', 'cities' => ['South Portland']],
    '04107' => ['state' => 'ME', 'cities' => ['Cape Elizabeth']],
    '04108' => ['state' => 'ME', 'cities' => ['Peaks Island']],
    '04109' => ['state' => 'ME', 'cities' => ['Portland']],
    '04110' => ['state' => 'ME', 'cities' => ['Cumberland Foreside']],
    '04112' => ['state' => 'ME', 'cities' => ['Portland']],
    '04116' => ['state' => 'ME', 'cities' => ['South Portland']],
    '04122' => ['state' => 'ME', 'cities' => ['Portland']],
    '04123' => ['state' => 'ME', 'cities' => ['Portland']],
    '04124' => ['state' => 'ME', 'cities' => ['Portland']],
];
