<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '04330' => ['state' => 'ME', 'cities' => ['Augusta']],
    '04332' => ['state' => 'ME', 'cities' => ['Augusta']],
    '04333' => ['state' => 'ME', 'cities' => ['Augusta']],
    '04336' => ['state' => 'ME', 'cities' => ['Augusta']],
    '04338' => ['state' => 'ME', 'cities' => ['Augusta']],
    '04341' => ['state' => 'ME', 'cities' => ['Coopers Mills']],
    '04342' => ['state' => 'ME', 'cities' => ['Dresden']],
    '04343' => ['state' => 'ME', 'cities' => ['East Winthrop']],
    '04344' => ['state' => 'ME', 'cities' => ['Farmingdale']],
    '04345' => ['state' => 'ME', 'cities' => ['Gardiner']],
    '04346' => ['state' => 'ME', 'cities' => ['Randolph']],
    '04347' => ['state' => 'ME', 'cities' => ['Hallowell']],
    '04348' => ['state' => 'ME', 'cities' => ['Jefferson']],
    '04349' => ['state' => 'ME', 'cities' => ['Kents Hill']],
    '04350' => ['state' => 'ME', 'cities' => ['Litchfield']],
    '04351' => ['state' => 'ME', 'cities' => ['Manchester']],
    '04352' => ['state' => 'ME', 'cities' => ['Mount Vernon']],
    '04353' => ['state' => 'ME', 'cities' => ['Whitefield']],
    '04354' => ['state' => 'ME', 'cities' => ['Palermo']],
    '04355' => ['state' => 'ME', 'cities' => ['Readfield']],
    '04357' => ['state' => 'ME', 'cities' => ['Richmond']],
    '04358' => ['state' => 'ME', 'cities' => ['South China']],
    '04359' => ['state' => 'ME', 'cities' => ['South Gardiner']],
    '04360' => ['state' => 'ME', 'cities' => ['Vienna']],
    '04363' => ['state' => 'ME', 'cities' => ['Windsor']],
    '04364' => ['state' => 'ME', 'cities' => ['Winthrop']],
];
