<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '04841' => ['state' => 'ME', 'cities' => ['Rockland']],
    '04843' => ['state' => 'ME', 'cities' => ['Camden']],
    '04847' => ['state' => 'ME', 'cities' => ['Hope']],
    '04848' => ['state' => 'ME', 'cities' => ['Islesboro']],
    '04849' => ['state' => 'ME', 'cities' => ['Lincolnville']],
    '04850' => ['state' => 'ME', 'cities' => ['Lincolnville Center']],
    '04851' => ['state' => 'ME', 'cities' => ['Matinicus']],
    '04852' => ['state' => 'ME', 'cities' => ['Monhegan']],
    '04853' => ['state' => 'ME', 'cities' => ['North Haven']],
    '04854' => ['state' => 'ME', 'cities' => ['Owls Head']],
    '04855' => ['state' => 'ME', 'cities' => ['Port Clyde']],
    '04856' => ['state' => 'ME', 'cities' => ['Rockport']],
    '04858' => ['state' => 'ME', 'cities' => ['South Thomaston']],
    '04859' => ['state' => 'ME', 'cities' => ['Spruce Head']],
    '04860' => ['state' => 'ME', 'cities' => ['Tenants Harbor']],
    '04861' => ['state' => 'ME', 'cities' => ['Thomaston']],
    '04862' => ['state' => 'ME', 'cities' => ['Union']],
    '04863' => ['state' => 'ME', 'cities' => ['Vinalhaven']],
    '04864' => ['state' => 'ME', 'cities' => ['Warren']],
    '04865' => ['state' => 'ME', 'cities' => ['West Rockport']],
];
