<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '05101' => ['state' => 'VT', 'cities' => ['Bellows Falls']],
    '05141' => ['state' => 'VT', 'cities' => ['Cambridgeport']],
    '05142' => ['state' => 'VT', 'cities' => ['Cavendish']],
    '05143' => ['state' => 'VT', 'cities' => ['Chester']],
    '05146' => ['state' => 'VT', 'cities' => ['Grafton']],
    '05148' => ['state' => 'VT', 'cities' => ['Londonderry']],
    '05149' => ['state' => 'VT', 'cities' => ['Ludlow']],
    '05150' => ['state' => 'VT', 'cities' => ['North Springfield']],
    '05151' => ['state' => 'VT', 'cities' => ['Perkinsville']],
    '05152' => ['state' => 'VT', 'cities' => ['Peru']],
    '05153' => ['state' => 'VT', 'cities' => ['Proctorsville']],
    '05154' => ['state' => 'VT', 'cities' => ['Saxtons River']],
    '05155' => ['state' => 'VT', 'cities' => ['South Londonderry']],
    '05156' => ['state' => 'VT', 'cities' => ['Springfield']],
    '05158' => ['state' => 'VT', 'cities' => ['Westminster']],
    '05159' => ['state' => 'VT', 'cities' => ['Westminster Station']],
    '05161' => ['state' => 'VT', 'cities' => ['Weston']],
];
