<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '05201' => ['state' => 'VT', 'cities' => ['Bennington']],
    '05250' => ['state' => 'VT', 'cities' => ['Arlington']],
    '05251' => ['state' => 'VT', 'cities' => ['Dorset']],
    '05252' => ['state' => 'VT', 'cities' => ['East Arlington']],
    '05253' => ['state' => 'VT', 'cities' => ['East Dorset']],
    '05254' => ['state' => 'VT', 'cities' => ['Manchester']],
    '05255' => ['state' => 'VT', 'cities' => ['Manchester Center']],
    '05257' => ['state' => 'VT', 'cities' => ['North Bennington']],
    '05260' => ['state' => 'VT', 'cities' => ['North Pownal']],
    '05261' => ['state' => 'VT', 'cities' => ['Pownal']],
    '05262' => ['state' => 'VT', 'cities' => ['Shaftsbury']],
];
