<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '05301' => ['state' => 'VT', 'cities' => ['Brattleboro']],
    '05302' => ['state' => 'VT', 'cities' => ['Brattleboro']],
    '05303' => ['state' => 'VT', 'cities' => ['Brattleboro']],
    '05304' => ['state' => 'VT', 'cities' => ['Brattleboro']],
    '05340' => ['state' => 'VT', 'cities' => ['Bondville']],
    '05341' => ['state' => 'VT', 'cities' => ['East Dover']],
    '05342' => ['state' => 'VT', 'cities' => ['Jacksonville']],
    '05343' => ['state' => 'VT', 'cities' => ['Jamaica']],
    '05344' => ['state' => 'VT', 'cities' => ['Marlboro']],
    '05345' => ['state' => 'VT', 'cities' => ['Newfane']],
    '05346' => ['state' => 'VT', 'cities' => ['Putney']],
    '05350' => ['state' => 'VT', 'cities' => ['Readsboro']],
    '05351' => ['state' => 'VT', 'cities' => ['South Newfane']],
    '05352' => ['state' => 'VT', 'cities' => ['Stamford']],
    '05353' => ['state' => 'VT', 'cities' => ['Townshend']],
    '05354' => ['state' => 'VT', 'cities' => ['Vernon']],
    '05355' => ['state' => 'VT', 'cities' => ['Wardsboro']],
    '05356' => ['state' => 'VT', 'cities' => ['West Dover']],
    '05357' => ['state' => 'VT', 'cities' => ['West Dummerston']],
    '05358' => ['state' => 'VT', 'cities' => ['West Halifax']],
    '05359' => ['state' => 'VT', 'cities' => ['West Townshend']],
    '05360' => ['state' => 'VT', 'cities' => ['West Wardsboro']],
    '05361' => ['state' => 'VT', 'cities' => ['Whitingham']],
    '05362' => ['state' => 'VT', 'cities' => ['Williamsville']],
    '05363' => ['state' => 'VT', 'cities' => ['Wilmington']],
];
