<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '05501' => ['state' => 'MA', 'cities' => ['Andover']],
    '05544' => ['state' => 'MA', 'cities' => ['Andover']],
];
