<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '05901' => ['state' => 'VT', 'cities' => ['Averill']],
    '05902' => ['state' => 'VT', 'cities' => ['Beecher Falls']],
    '05903' => ['state' => 'VT', 'cities' => ['Canaan']],
    '05904' => ['state' => 'VT', 'cities' => ['Gilman']],
    '05905' => ['state' => 'VT', 'cities' => ['Guildhall']],
    '05906' => ['state' => 'VT', 'cities' => ['Lunenburg']],
    '05907' => ['state' => 'VT', 'cities' => ['Norton']],
];
