<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '06601' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06602' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06604' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06605' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06606' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06607' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06608' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06610' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06611' => ['state' => 'CT', 'cities' => ['Trumbull']],
    '06612' => ['state' => 'CT', 'cities' => ['Easton']],
    '06614' => ['state' => 'CT', 'cities' => ['Stratford']],
    '06615' => ['state' => 'CT', 'cities' => ['Stratford']],
    '06673' => ['state' => 'CT', 'cities' => ['Bridgeport']],
    '06699' => ['state' => 'CT', 'cities' => ['Bridgeport']],
];
