<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '06901' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06902' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06903' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06904' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06905' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06906' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06907' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06910' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06911' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06912' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06913' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06914' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06920' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06921' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06922' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06926' => ['state' => 'CT', 'cities' => ['Stamford']],
    '06927' => ['state' => 'CT', 'cities' => ['Stamford']],
];
