<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '07201' => ['state' => 'NJ', 'cities' => ['Elizabeth']],
    '07202' => ['state' => 'NJ', 'cities' => ['Elizabeth']],
    '07203' => ['state' => 'NJ', 'cities' => ['Roselle']],
    '07204' => ['state' => 'NJ', 'cities' => ['Roselle Park']],
    '07205' => ['state' => 'NJ', 'cities' => ['Hillside']],
    '07206' => ['state' => 'NJ', 'cities' => ['Elizabethport']],
    '07207' => ['state' => 'NJ', 'cities' => ['Elizabeth']],
    '07208' => ['state' => 'NJ', 'cities' => ['Elizabeth']],
];
