<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '07501' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07502' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07503' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07504' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07505' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07506' => ['state' => 'NJ', 'cities' => ['Hawthorne']],
    '07507' => ['state' => 'NJ', 'cities' => ['Hawthorne']],
    '07508' => ['state' => 'NJ', 'cities' => ['Haledon']],
    '07509' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07510' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07511' => ['state' => 'NJ', 'cities' => ['Totowa']],
    '07512' => ['state' => 'NJ', 'cities' => ['Totowa']],
    '07513' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07514' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07522' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07524' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07533' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07538' => ['state' => 'NJ', 'cities' => ['Haledon']],
    '07543' => ['state' => 'NJ', 'cities' => ['Paterson']],
    '07544' => ['state' => 'NJ', 'cities' => ['Paterson']],
];
