<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '08101' => ['state' => 'NJ', 'cities' => ['Camden']],
    '08102' => ['state' => 'NJ', 'cities' => ['Camden']],
    '08103' => ['state' => 'NJ', 'cities' => ['Camden']],
    '08104' => ['state' => 'NJ', 'cities' => ['Camden']],
    '08105' => ['state' => 'NJ', 'cities' => ['Camden']],
    '08106' => ['state' => 'NJ', 'cities' => ['Audubon']],
    '08107' => ['state' => 'NJ', 'cities' => ['Oaklyn']],
    '08108' => ['state' => 'NJ', 'cities' => ['Collingswood']],
    '08109' => ['state' => 'NJ', 'cities' => ['Merchantville']],
    '08110' => ['state' => 'NJ', 'cities' => ['Pennsauken']],
];
