<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '08701' => ['state' => 'NJ', 'cities' => ['Lakewood']],
    '08720' => ['state' => 'NJ', 'cities' => ['Allenwood']],
    '08721' => ['state' => 'NJ', 'cities' => ['Bayville']],
    '08722' => ['state' => 'NJ', 'cities' => ['Beachwood']],
    '08723' => ['state' => 'NJ', 'cities' => ['Brick']],
    '08724' => ['state' => 'NJ', 'cities' => ['Brick']],
    '08730' => ['state' => 'NJ', 'cities' => ['Brielle']],
    '08731' => ['state' => 'NJ', 'cities' => ['Forked River']],
    '08732' => ['state' => 'NJ', 'cities' => ['Island Heights']],
    '08733' => ['state' => 'NJ', 'cities' => ['Lakehurst']],
    '08734' => ['state' => 'NJ', 'cities' => ['Lanoka Harbor']],
    '08735' => ['state' => 'NJ', 'cities' => ['Lavallette']],
    '08736' => ['state' => 'NJ', 'cities' => ['Manasquan']],
    '08738' => ['state' => 'NJ', 'cities' => ['Mantoloking']],
    '08739' => ['state' => 'NJ', 'cities' => ['Normandy Beach']],
    '08740' => ['state' => 'NJ', 'cities' => ['Ocean Gate']],
    '08741' => ['state' => 'NJ', 'cities' => ['Pine Beach']],
    '08742' => ['state' => 'NJ', 'cities' => ['Point Pleasant Beach']],
    '08750' => ['state' => 'NJ', 'cities' => ['Sea Girt']],
    '08751' => ['state' => 'NJ', 'cities' => ['Seaside Heights']],
    '08752' => ['state' => 'NJ', 'cities' => ['Seaside Park']],
    '08753' => ['state' => 'NJ', 'cities' => ['Toms River']],
    '08754' => ['state' => 'NJ', 'cities' => ['Toms River']],
    '08755' => ['state' => 'NJ', 'cities' => ['Toms River']],
    '08756' => ['state' => 'NJ', 'cities' => ['Toms River']],
    '08757' => ['state' => 'NJ', 'cities' => ['Toms River']],
    '08758' => ['state' => 'NJ', 'cities' => ['Waretown']],
    '08759' => ['state' => 'NJ', 'cities' => ['Manchester Township']],
];
