<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '08901' => ['state' => 'NJ', 'cities' => ['New Brunswick']],
    '08902' => ['state' => 'NJ', 'cities' => ['North Brunswick']],
    '08903' => ['state' => 'NJ', 'cities' => ['New Brunswick']],
    '08904' => ['state' => 'NJ', 'cities' => ['Highland Park']],
    '08906' => ['state' => 'NJ', 'cities' => ['New Brunswick']],
    '08933' => ['state' => 'NJ', 'cities' => ['New Brunswick']],
    '08989' => ['state' => 'NJ', 'cities' => ['New Brunswick']],
];
