<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '10451' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10452' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10453' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10454' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10455' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10456' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10457' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10458' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10459' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10460' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10461' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10462' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10463' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10464' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10465' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10466' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10467' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10468' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10469' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10470' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10471' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10472' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10473' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10474' => ['state' => 'NY', 'cities' => ['Bronx']],
    '10475' => ['state' => 'NY', 'cities' => ['Bronx']],
];
