<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '10701' => ['state' => 'NY', 'cities' => ['Yonkers']],
    '10702' => ['state' => 'NY', 'cities' => ['Yonkers']],
    '10703' => ['state' => 'NY', 'cities' => ['Yonkers']],
    '10704' => ['state' => 'NY', 'cities' => ['Yonkers']],
    '10705' => ['state' => 'NY', 'cities' => ['Yonkers']],
    '10706' => ['state' => 'NY', 'cities' => ['Hastings On Hudson']],
    '10707' => ['state' => 'NY', 'cities' => ['Tuckahoe']],
    '10708' => ['state' => 'NY', 'cities' => ['Bronxville']],
    '10709' => ['state' => 'NY', 'cities' => ['Eastchester']],
    '10710' => ['state' => 'NY', 'cities' => ['Yonkers']],
];
