<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '11101' => ['state' => 'NY', 'cities' => ['Long Island City']],
    '11102' => ['state' => 'NY', 'cities' => ['Astoria']],
    '11103' => ['state' => 'NY', 'cities' => ['Astoria']],
    '11104' => ['state' => 'NY', 'cities' => ['Sunnyside']],
    '11105' => ['state' => 'NY', 'cities' => ['Astoria']],
    '11106' => ['state' => 'NY', 'cities' => ['Astoria']],
    '11109' => ['state' => 'NY', 'cities' => ['Long Island City']],
    '11120' => ['state' => 'NY', 'cities' => ['Long Island City']],
];
