<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '11690' => ['state' => 'NY', 'cities' => ['Far Rockaway']],
    '11691' => ['state' => 'NY', 'cities' => ['Far Rockaway']],
    '11692' => ['state' => 'NY', 'cities' => ['Arverne']],
    '11693' => ['state' => 'NY', 'cities' => ['Far Rockaway']],
    '11694' => ['state' => 'NY', 'cities' => ['Rockaway Park']],
    '11695' => ['state' => 'NY', 'cities' => ['Far Rockaway']],
    '11697' => ['state' => 'NY', 'cities' => ['Breezy Point']],
];
