<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '11801' => ['state' => 'NY', 'cities' => ['Hicksville']],
    '11802' => ['state' => 'NY', 'cities' => ['Hicksville']],
    '11803' => ['state' => 'NY', 'cities' => ['Plainview']],
    '11804' => ['state' => 'NY', 'cities' => ['Old Bethpage']],
    '11815' => ['state' => 'NY', 'cities' => ['Hicksville']],
    '11819' => ['state' => 'NY', 'cities' => ['Hicksville']],
    '11853' => ['state' => 'NY', 'cities' => ['Jericho']],
];
