<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '12301' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12302' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12303' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12304' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12305' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12306' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12307' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12308' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12309' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12325' => ['state' => 'NY', 'cities' => ['Schenectady']],
    '12345' => ['state' => 'NY', 'cities' => ['Schenectady']],
];
