<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '12601' => ['state' => 'NY', 'cities' => ['Poughkeepsie']],
    '12602' => ['state' => 'NY', 'cities' => ['Poughkeepsie']],
    '12603' => ['state' => 'NY', 'cities' => ['Poughkeepsie']],
    '12604' => ['state' => 'NY', 'cities' => ['Poughkeepsie']],
];
