<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '13201' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13202' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13203' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13204' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13205' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13206' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13207' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13208' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13209' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13210' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13211' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13212' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13214' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13215' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13217' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13218' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13219' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13220' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13221' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13224' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13225' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13235' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13244' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13250' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13251' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13252' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13261' => ['state' => 'NY', 'cities' => ['Syracuse']],
    '13290' => ['state' => 'NY', 'cities' => ['Syracuse']],
];
