<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '13501' => ['state' => 'NY', 'cities' => ['Utica']],
    '13502' => ['state' => 'NY', 'cities' => ['Utica']],
    '13503' => ['state' => 'NY', 'cities' => ['Utica']],
    '13504' => ['state' => 'NY', 'cities' => ['Utica']],
    '13505' => ['state' => 'NY', 'cities' => ['Utica']],
    '13599' => ['state' => 'NY', 'cities' => ['Utica']],
];
