<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '13901' => ['state' => 'NY', 'cities' => ['Binghamton']],
    '13902' => ['state' => 'NY', 'cities' => ['Binghamton']],
    '13903' => ['state' => 'NY', 'cities' => ['Binghamton']],
    '13904' => ['state' => 'NY', 'cities' => ['Binghamton']],
    '13905' => ['state' => 'NY', 'cities' => ['Binghamton']],
];
