<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '14901' => ['state' => 'NY', 'cities' => ['Elmira']],
    '14902' => ['state' => 'NY', 'cities' => ['Elmira']],
    '14903' => ['state' => 'NY', 'cities' => ['Elmira']],
    '14904' => ['state' => 'NY', 'cities' => ['Elmira']],
    '14905' => ['state' => 'NY', 'cities' => ['Elmira']],
];
