<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '16501' => ['state' => 'PA', 'cities' => ['Erie']],
    '16502' => ['state' => 'PA', 'cities' => ['Erie']],
    '16503' => ['state' => 'PA', 'cities' => ['Erie']],
    '16504' => ['state' => 'PA', 'cities' => ['Erie']],
    '16505' => ['state' => 'PA', 'cities' => ['Erie']],
    '16506' => ['state' => 'PA', 'cities' => ['Erie']],
    '16507' => ['state' => 'PA', 'cities' => ['Erie']],
    '16508' => ['state' => 'PA', 'cities' => ['Erie']],
    '16509' => ['state' => 'PA', 'cities' => ['Erie']],
    '16510' => ['state' => 'PA', 'cities' => ['Erie']],
    '16511' => ['state' => 'PA', 'cities' => ['Erie']],
    '16512' => ['state' => 'PA', 'cities' => ['Erie']],
    '16514' => ['state' => 'PA', 'cities' => ['Erie']],
    '16515' => ['state' => 'PA', 'cities' => ['Erie']],
    '16522' => ['state' => 'PA', 'cities' => ['Erie']],
    '16530' => ['state' => 'PA', 'cities' => ['Erie']],
    '16531' => ['state' => 'PA', 'cities' => ['Erie']],
    '16534' => ['state' => 'PA', 'cities' => ['Erie']],
    '16538' => ['state' => 'PA', 'cities' => ['Erie']],
    '16541' => ['state' => 'PA', 'cities' => ['Erie']],
    '16544' => ['state' => 'PA', 'cities' => ['Erie']],
    '16546' => ['state' => 'PA', 'cities' => ['Erie']],
    '16550' => ['state' => 'PA', 'cities' => ['Erie']],
    '16553' => ['state' => 'PA', 'cities' => ['Erie']],
    '16563' => ['state' => 'PA', 'cities' => ['Erie']],
    '16565' => ['state' => 'PA', 'cities' => ['Erie']],
];
