<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '16701' => ['state' => 'PA', 'cities' => ['Bradford']],
    '16720' => ['state' => 'PA', 'cities' => ['Austin']],
    '16724' => ['state' => 'PA', 'cities' => ['Crosby']],
    '16725' => ['state' => 'PA', 'cities' => ['Custer City']],
    '16726' => ['state' => 'PA', 'cities' => ['Cyclone']],
    '16727' => ['state' => 'PA', 'cities' => ['Derrick City']],
    '16728' => ['state' => 'PA', 'cities' => ['De Young']],
    '16729' => ['state' => 'PA', 'cities' => ['Duke Center']],
    '16730' => ['state' => 'PA', 'cities' => ['East Smethport']],
    '16731' => ['state' => 'PA', 'cities' => ['Eldred']],
    '16732' => ['state' => 'PA', 'cities' => ['Gifford']],
    '16733' => ['state' => 'PA', 'cities' => ['Hazel Hurst']],
    '16734' => ['state' => 'PA', 'cities' => ['James City']],
    '16735' => ['state' => 'PA', 'cities' => ['Kane']],
    '16738' => ['state' => 'PA', 'cities' => ['Lewis Run']],
    '16740' => ['state' => 'PA', 'cities' => ['Mount Jewett']],
    '16743' => ['state' => 'PA', 'cities' => ['Port Allegany']],
    '16744' => ['state' => 'PA', 'cities' => ['Rew']],
    '16745' => ['state' => 'PA', 'cities' => ['Rixford']],
    '16746' => ['state' => 'PA', 'cities' => ['Roulette']],
    '16748' => ['state' => 'PA', 'cities' => ['Shinglehouse']],
    '16749' => ['state' => 'PA', 'cities' => ['Smethport']],
    '16750' => ['state' => 'PA', 'cities' => ['Turtlepoint']],
];
