<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '17101' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17102' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17103' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17104' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17105' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17106' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17107' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17108' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17109' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17110' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17111' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17112' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17113' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17120' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17121' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17122' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17123' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17124' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17125' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17126' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17127' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17128' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17129' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17130' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17140' => ['state' => 'PA', 'cities' => ['Harrisburg']],
    '17177' => ['state' => 'PA', 'cities' => ['Harrisburg']],
];
