<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '17401' => ['state' => 'PA', 'cities' => ['York']],
    '17402' => ['state' => 'PA', 'cities' => ['York']],
    '17403' => ['state' => 'PA', 'cities' => ['York']],
    '17404' => ['state' => 'PA', 'cities' => ['York']],
    '17405' => ['state' => 'PA', 'cities' => ['York']],
    '17406' => ['state' => 'PA', 'cities' => ['York']],
    '17407' => ['state' => 'PA', 'cities' => ['York']],
    '17408' => ['state' => 'PA', 'cities' => ['York']],
];
