<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '18101' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18102' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18103' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18104' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18105' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18106' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18109' => ['state' => 'PA', 'cities' => ['Allentown']],
    '18195' => ['state' => 'PA', 'cities' => ['Allentown']],
];
