<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '18501' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18502' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18503' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18504' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18505' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18507' => ['state' => 'PA', 'cities' => ['Moosic']],
    '18508' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18509' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18510' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18512' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18515' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18517' => ['state' => 'PA', 'cities' => ['Taylor']],
    '18518' => ['state' => 'PA', 'cities' => ['Old Forge']],
    '18519' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18540' => ['state' => 'PA', 'cities' => ['Scranton']],
    '18577' => ['state' => 'PA', 'cities' => ['Scranton']],
];
