<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '18701' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18702' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18703' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18704' => ['state' => 'PA', 'cities' => ['Kingston']],
    '18705' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18706' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18707' => ['state' => 'PA', 'cities' => ['Mountain Top']],
    '18708' => ['state' => 'PA', 'cities' => ['Shavertown']],
    '18709' => ['state' => 'PA', 'cities' => ['Luzerne']],
    '18710' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18711' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18762' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18764' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18765' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18766' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18767' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18769' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
    '18773' => ['state' => 'PA', 'cities' => ['Wilkes Barre']],
];
