<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '19244' => ['state' => 'PA', 'cities' => ['Philadelphia']],
    '19255' => ['state' => 'PA', 'cities' => ['Philadelphia']],
];
