<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '19701' => ['state' => 'DE', 'cities' => ['Bear']],
    '19702' => ['state' => 'DE', 'cities' => ['Newark']],
    '19703' => ['state' => 'DE', 'cities' => ['Claymont']],
    '19706' => ['state' => 'DE', 'cities' => ['Delaware City']],
    '19707' => ['state' => 'DE', 'cities' => ['Hockessin']],
    '19708' => ['state' => 'DE', 'cities' => ['Kirkwood']],
    '19709' => ['state' => 'DE', 'cities' => ['Middletown']],
    '19710' => ['state' => 'DE', 'cities' => ['Montchanin']],
    '19711' => ['state' => 'DE', 'cities' => ['Newark']],
    '19712' => ['state' => 'DE', 'cities' => ['Newark']],
    '19713' => ['state' => 'DE', 'cities' => ['Newark']],
    '19714' => ['state' => 'DE', 'cities' => ['Newark']],
    '19715' => ['state' => 'DE', 'cities' => ['Newark']],
    '19716' => ['state' => 'DE', 'cities' => ['Newark']],
    '19717' => ['state' => 'DE', 'cities' => ['Newark']],
    '19718' => ['state' => 'DE', 'cities' => ['Newark']],
    '19720' => ['state' => 'DE', 'cities' => ['New Castle']],
    '19721' => ['state' => 'DE', 'cities' => ['New Castle']],
    '19725' => ['state' => 'DE', 'cities' => ['Newark']],
    '19726' => ['state' => 'DE', 'cities' => ['New Castle']],
    '19730' => ['state' => 'DE', 'cities' => ['Odessa']],
    '19731' => ['state' => 'DE', 'cities' => ['Port Penn']],
    '19732' => ['state' => 'DE', 'cities' => ['Rockland']],
    '19733' => ['state' => 'DE', 'cities' => ['Saint Georges']],
    '19734' => ['state' => 'DE', 'cities' => ['Townsend']],
    '19735' => ['state' => 'DE', 'cities' => ['Winterthur']],
    '19736' => ['state' => 'DE', 'cities' => ['Yorklyn']],
];
