<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '19801' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19802' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19803' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19804' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19805' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19806' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19807' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19808' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19809' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19810' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19850' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19880' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19884' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19885' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19886' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19890' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19891' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19892' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19893' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19894' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19895' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19896' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19897' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19898' => ['state' => 'DE', 'cities' => ['Wilmington']],
    '19899' => ['state' => 'DE', 'cities' => ['Wilmington']],
];
