<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '20301' => ['state' => 'DC', 'cities' => ['Washington']],
    '20303' => ['state' => 'DC', 'cities' => ['Washington']],
    '20306' => ['state' => 'DC', 'cities' => ['Washington']],
    '20310' => ['state' => 'DC', 'cities' => ['Washington']],
    '20314' => ['state' => 'DC', 'cities' => ['Washington']],
    '20317' => ['state' => 'DC', 'cities' => ['Washington']],
    '20318' => ['state' => 'DC', 'cities' => ['Washington']],
    '20319' => ['state' => 'DC', 'cities' => ['Washington']],
    '20330' => ['state' => 'DC', 'cities' => ['Washington']],
    '20340' => ['state' => 'DC', 'cities' => ['Washington']],
    '20350' => ['state' => 'DC', 'cities' => ['Washington']],
    '20355' => ['state' => 'DC', 'cities' => ['Washington']],
    '20370' => ['state' => 'DC', 'cities' => ['Washington']],
    '20372' => ['state' => 'DC', 'cities' => ['Washington']],
    '20373' => ['state' => 'DC', 'cities' => ['Naval Anacost Annex']],
    '20374' => ['state' => 'DC', 'cities' => ['Washington Navy Yard']],
    '20375' => ['state' => 'DC', 'cities' => ['Washington']],
    '20376' => ['state' => 'DC', 'cities' => ['Washington Navy Yard']],
    '20380' => ['state' => 'DC', 'cities' => ['Washington']],
    '20388' => ['state' => 'DC', 'cities' => ['Washington Navy Yard']],
    '20389' => ['state' => 'DC', 'cities' => ['Washington']],
    '20390' => ['state' => 'DC', 'cities' => ['Washington']],
    '20391' => ['state' => 'DC', 'cities' => ['Washington Navy Yard']],
    '20392' => ['state' => 'DC', 'cities' => ['Washington']],
    '20393' => ['state' => 'DC', 'cities' => ['Washington']],
    '20394' => ['state' => 'DC', 'cities' => ['Washington']],
    '20395' => ['state' => 'DC', 'cities' => ['Washington']],
    '20398' => ['state' => 'DC', 'cities' => ['Washington Navy Yard']],
];
