<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '20901' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20902' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20903' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20904' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20905' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20906' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20907' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20908' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20910' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20911' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20912' => ['state' => 'MD', 'cities' => ['Takoma Park']],
    '20913' => ['state' => 'MD', 'cities' => ['Takoma Park']],
    '20914' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20915' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20916' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20918' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20993' => ['state' => 'MD', 'cities' => ['Silver Spring']],
    '20997' => ['state' => 'MD', 'cities' => ['Silver Spring']],
];
