<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '21401' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21402' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21403' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21404' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21405' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21409' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21411' => ['state' => 'MD', 'cities' => ['Annapolis']],
    '21412' => ['state' => 'MD', 'cities' => ['Annapolis']],
];
