<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '21901' => ['state' => 'MD', 'cities' => ['North East']],
    '21902' => ['state' => 'MD', 'cities' => ['Perry Point']],
    '21903' => ['state' => 'MD', 'cities' => ['Perryville']],
    '21904' => ['state' => 'MD', 'cities' => ['Port Deposit']],
    '21911' => ['state' => 'MD', 'cities' => ['Rising Sun']],
    '21912' => ['state' => 'MD', 'cities' => ['Warwick']],
    '21913' => ['state' => 'MD', 'cities' => ['Cecilton']],
    '21914' => ['state' => 'MD', 'cities' => ['Charlestown']],
    '21915' => ['state' => 'MD', 'cities' => ['Chesapeake City']],
    '21916' => ['state' => 'MD', 'cities' => ['Childs']],
    '21917' => ['state' => 'MD', 'cities' => ['Colora']],
    '21918' => ['state' => 'MD', 'cities' => ['Conowingo']],
    '21919' => ['state' => 'MD', 'cities' => ['Earleville']],
    '21920' => ['state' => 'MD', 'cities' => ['Elk Mills']],
    '21921' => ['state' => 'MD', 'cities' => ['Elkton']],
    '21922' => ['state' => 'MD', 'cities' => ['Elkton']],
    '21930' => ['state' => 'MD', 'cities' => ['Georgetown']],
];
