<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '22301' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22302' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22303' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22304' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22305' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22306' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22307' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22308' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22309' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22310' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22311' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22312' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22313' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22314' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22315' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22320' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22331' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22332' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22333' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22334' => ['state' => 'VA', 'cities' => ['Alexandria']],
    '22350' => ['state' => 'VA', 'cities' => ['Alexandria']],
];
