<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '23501' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23502' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23503' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23504' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23505' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23506' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23507' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23508' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23509' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23510' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23511' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23513' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23514' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23515' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23517' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23518' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23519' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23523' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23529' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23541' => ['state' => 'VA', 'cities' => ['Norfolk']],
    '23551' => ['state' => 'VA', 'cities' => ['Norfolk']],
];
