<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '23701' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23702' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23703' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23704' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23705' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23707' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23708' => ['state' => 'VA', 'cities' => ['Portsmouth']],
    '23709' => ['state' => 'VA', 'cities' => ['Portsmouth']],
];
