<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '24701' => ['state' => 'WV', 'cities' => ['Bluefield']],
    '24712' => ['state' => 'WV', 'cities' => ['Athens']],
    '24714' => ['state' => 'WV', 'cities' => ['Beeson']],
    '24715' => ['state' => 'WV', 'cities' => ['Bramwell']],
    '24716' => ['state' => 'WV', 'cities' => ['Bud']],
    '24719' => ['state' => 'WV', 'cities' => ['Covel']],
    '24724' => ['state' => 'WV', 'cities' => ['Freeman']],
    '24726' => ['state' => 'WV', 'cities' => ['Herndon']],
    '24729' => ['state' => 'WV', 'cities' => ['Hiawatha']],
    '24731' => ['state' => 'WV', 'cities' => ['Kegley']],
    '24732' => ['state' => 'WV', 'cities' => ['Kellysville']],
    '24733' => ['state' => 'WV', 'cities' => ['Lashmeet']],
    '24736' => ['state' => 'WV', 'cities' => ['Matoaka']],
    '24737' => ['state' => 'WV', 'cities' => ['Montcalm']],
    '24738' => ['state' => 'WV', 'cities' => ['Nemours']],
    '24739' => ['state' => 'WV', 'cities' => ['Princeton']],
    '24740' => ['state' => 'WV', 'cities' => ['Princeton']],
    '24747' => ['state' => 'WV', 'cities' => ['Rock']],
    '24751' => ['state' => 'WV', 'cities' => ['Wolfe']],
];
