<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '26003' => ['state' => 'WV', 'cities' => ['Wheeling']],
    '26030' => ['state' => 'WV', 'cities' => ['Beech Bottom']],
    '26031' => ['state' => 'WV', 'cities' => ['Benwood']],
    '26032' => ['state' => 'WV', 'cities' => ['Bethany']],
    '26033' => ['state' => 'WV', 'cities' => ['Cameron']],
    '26034' => ['state' => 'WV', 'cities' => ['Chester']],
    '26035' => ['state' => 'WV', 'cities' => ['Colliers']],
    '26036' => ['state' => 'WV', 'cities' => ['Dallas']],
    '26037' => ['state' => 'WV', 'cities' => ['Follansbee']],
    '26038' => ['state' => 'WV', 'cities' => ['Glen Dale']],
    '26039' => ['state' => 'WV', 'cities' => ['Glen Easton']],
    '26040' => ['state' => 'WV', 'cities' => ['Mcmechen']],
    '26041' => ['state' => 'WV', 'cities' => ['Moundsville']],
    '26047' => ['state' => 'WV', 'cities' => ['New Cumberland']],
    '26050' => ['state' => 'WV', 'cities' => ['Newell']],
    '26055' => ['state' => 'WV', 'cities' => ['Proctor']],
    '26056' => ['state' => 'WV', 'cities' => ['New Manchester']],
    '26058' => ['state' => 'WV', 'cities' => ['Short Creek']],
    '26059' => ['state' => 'WV', 'cities' => ['Triadelphia']],
    '26060' => ['state' => 'WV', 'cities' => ['Valley Grove']],
    '26062' => ['state' => 'WV', 'cities' => ['Weirton']],
    '26070' => ['state' => 'WV', 'cities' => ['Wellsburg']],
    '26074' => ['state' => 'WV', 'cities' => ['West Liberty']],
    '26075' => ['state' => 'WV', 'cities' => ['Windsor Heights']],
];
