<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '26704' => ['state' => 'WV', 'cities' => ['Augusta']],
    '26705' => ['state' => 'WV', 'cities' => ['Aurora']],
    '26707' => ['state' => 'WV', 'cities' => ['Bayard']],
    '26710' => ['state' => 'WV', 'cities' => ['Burlington']],
    '26711' => ['state' => 'WV', 'cities' => ['Capon Bridge']],
    '26714' => ['state' => 'WV', 'cities' => ['Delray']],
    '26716' => ['state' => 'WV', 'cities' => ['Eglon']],
    '26717' => ['state' => 'WV', 'cities' => ['Elk Garden']],
    '26719' => ['state' => 'WV', 'cities' => ['Fort Ashby']],
    '26720' => ['state' => 'WV', 'cities' => ['Gormania']],
    '26722' => ['state' => 'WV', 'cities' => ['Green Spring']],
    '26726' => ['state' => 'WV', 'cities' => ['Keyser']],
    '26731' => ['state' => 'WV', 'cities' => ['Lahmansville']],
    '26739' => ['state' => 'WV', 'cities' => ['Mount Storm']],
    '26743' => ['state' => 'WV', 'cities' => ['New Creek']],
    '26750' => ['state' => 'WV', 'cities' => ['Piedmont']],
    '26753' => ['state' => 'WV', 'cities' => ['Ridgeley']],
    '26755' => ['state' => 'WV', 'cities' => ['Rio']],
    '26757' => ['state' => 'WV', 'cities' => ['Romney']],
    '26761' => ['state' => 'WV', 'cities' => ['Shanks']],
    '26763' => ['state' => 'WV', 'cities' => ['Springfield']],
    '26764' => ['state' => 'WV', 'cities' => ['Terra Alta']],
    '26767' => ['state' => 'WV', 'cities' => ['Wiley Ford']],
];
