<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '26801' => ['state' => 'WV', 'cities' => ['Baker']],
    '26802' => ['state' => 'WV', 'cities' => ['Brandywine']],
    '26804' => ['state' => 'WV', 'cities' => ['Circleville']],
    '26807' => ['state' => 'WV', 'cities' => ['Franklin']],
    '26808' => ['state' => 'WV', 'cities' => ['High View']],
    '26810' => ['state' => 'WV', 'cities' => ['Lost City']],
    '26812' => ['state' => 'WV', 'cities' => ['Mathias']],
    '26814' => ['state' => 'WV', 'cities' => ['Riverton']],
    '26815' => ['state' => 'WV', 'cities' => ['Sugar Grove']],
    '26817' => ['state' => 'WV', 'cities' => ['Bloomery']],
    '26818' => ['state' => 'WV', 'cities' => ['Fisher']],
    '26823' => ['state' => 'WV', 'cities' => ['Capon Springs']],
    '26833' => ['state' => 'WV', 'cities' => ['Maysville']],
    '26836' => ['state' => 'WV', 'cities' => ['Moorefield']],
    '26838' => ['state' => 'WV', 'cities' => ['Milam']],
    '26845' => ['state' => 'WV', 'cities' => ['Old Fields']],
    '26847' => ['state' => 'WV', 'cities' => ['Petersburg']],
    '26851' => ['state' => 'WV', 'cities' => ['Wardensville']],
    '26852' => ['state' => 'WV', 'cities' => ['Purgitsville']],
    '26855' => ['state' => 'WV', 'cities' => ['Cabins']],
    '26865' => ['state' => 'WV', 'cities' => ['Yellow Spring']],
    '26866' => ['state' => 'WV', 'cities' => ['Upper Tract']],
    '26884' => ['state' => 'WV', 'cities' => ['Seneca Rocks']],
    '26886' => ['state' => 'WV', 'cities' => ['Onego']],
];
