<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '27101' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27102' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27103' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27104' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27105' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27106' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27107' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27108' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27109' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27110' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27111' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27113' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27114' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27115' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27116' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27117' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27120' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27127' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27130' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27150' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27152' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27155' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27157' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27198' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
    '27199' => ['state' => 'NC', 'cities' => ['Winston-Salem']],
];
