<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '27401' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27402' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27403' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27404' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27405' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27406' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27407' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27408' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27409' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27410' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27411' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27412' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27413' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27415' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27416' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27417' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27419' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27420' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27425' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27427' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27429' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27435' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27438' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27455' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27495' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27497' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27498' => ['state' => 'NC', 'cities' => ['Greensboro']],
    '27499' => ['state' => 'NC', 'cities' => ['Greensboro']],
];
