<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '28901' => ['state' => 'NC', 'cities' => ['Andrews']],
    '28902' => ['state' => 'NC', 'cities' => ['Brasstown']],
    '28903' => ['state' => 'NC', 'cities' => ['Culberson']],
    '28904' => ['state' => 'NC', 'cities' => ['Hayesville']],
    '28905' => ['state' => 'NC', 'cities' => ['Marble']],
    '28906' => ['state' => 'NC', 'cities' => ['Murphy']],
    '28909' => ['state' => 'NC', 'cities' => ['Warne']],
];
