<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '30802' => ['state' => 'GA', 'cities' => ['Appling']],
    '30803' => ['state' => 'GA', 'cities' => ['Avera']],
    '30805' => ['state' => 'GA', 'cities' => ['Blythe']],
    '30806' => ['state' => 'GA', 'cities' => ['Boneville']],
    '30807' => ['state' => 'GA', 'cities' => ['Camak']],
    '30808' => ['state' => 'GA', 'cities' => ['Dearing']],
    '30809' => ['state' => 'GA', 'cities' => ['Evans']],
    '30810' => ['state' => 'GA', 'cities' => ['Gibson']],
    '30811' => ['state' => 'GA', 'cities' => ['Gough']],
    '30812' => ['state' => 'GA', 'cities' => ['Gracewood']],
    '30813' => ['state' => 'GA', 'cities' => ['Grovetown']],
    '30814' => ['state' => 'GA', 'cities' => ['Harlem']],
    '30815' => ['state' => 'GA', 'cities' => ['Hephzibah']],
    '30816' => ['state' => 'GA', 'cities' => ['Keysville']],
    '30817' => ['state' => 'GA', 'cities' => ['Lincolnton']],
    '30818' => ['state' => 'GA', 'cities' => ['Matthews']],
    '30819' => ['state' => 'GA', 'cities' => ['Mesena']],
    '30820' => ['state' => 'GA', 'cities' => ['Mitchell']],
    '30821' => ['state' => 'GA', 'cities' => ['Norwood']],
    '30822' => ['state' => 'GA', 'cities' => ['Perkins']],
    '30823' => ['state' => 'GA', 'cities' => ['Stapleton']],
    '30824' => ['state' => 'GA', 'cities' => ['Thomson']],
    '30828' => ['state' => 'GA', 'cities' => ['Warrenton']],
    '30830' => ['state' => 'GA', 'cities' => ['Waynesboro']],
    '30833' => ['state' => 'GA', 'cities' => ['Wrens']],
];
