<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '30901' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30903' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30904' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30905' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30906' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30907' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30909' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30912' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30914' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30916' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30917' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30919' => ['state' => 'GA', 'cities' => ['Augusta']],
    '30999' => ['state' => 'GA', 'cities' => ['Augusta']],
];
