<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31106' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31107' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31119' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31126' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31131' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31136' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31139' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31141' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31144' => ['state' => 'GA', 'cities' => ['Kennesaw']],
    '31145' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31146' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31150' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31156' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31169' => ['state' => 'GA', 'cities' => ['Peachtree City']],
    '31192' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31193' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31195' => ['state' => 'GA', 'cities' => ['Atlanta']],
    '31196' => ['state' => 'GA', 'cities' => ['Atlanta']],
];
