<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31201' => ['state' => 'GA', 'cities' => ['Macon']],
    '31202' => ['state' => 'GA', 'cities' => ['Macon']],
    '31203' => ['state' => 'GA', 'cities' => ['Macon']],
    '31204' => ['state' => 'GA', 'cities' => ['Macon']],
    '31205' => ['state' => 'GA', 'cities' => ['Macon']],
    '31206' => ['state' => 'GA', 'cities' => ['Macon']],
    '31207' => ['state' => 'GA', 'cities' => ['Macon']],
    '31208' => ['state' => 'GA', 'cities' => ['Macon']],
    '31209' => ['state' => 'GA', 'cities' => ['Macon']],
    '31210' => ['state' => 'GA', 'cities' => ['Macon']],
    '31211' => ['state' => 'GA', 'cities' => ['Macon']],
    '31213' => ['state' => 'GA', 'cities' => ['Macon']],
    '31216' => ['state' => 'GA', 'cities' => ['Macon']],
    '31217' => ['state' => 'GA', 'cities' => ['Macon']],
    '31220' => ['state' => 'GA', 'cities' => ['Macon']],
    '31221' => ['state' => 'GA', 'cities' => ['Macon']],
    '31294' => ['state' => 'GA', 'cities' => ['Macon']],
    '31295' => ['state' => 'GA', 'cities' => ['Macon']],
    '31296' => ['state' => 'GA', 'cities' => ['Macon']],
    '31297' => ['state' => 'GA', 'cities' => ['Macon']],
];
