<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31301' => ['state' => 'GA', 'cities' => ['Allenhurst']],
    '31302' => ['state' => 'GA', 'cities' => ['Bloomingdale']],
    '31303' => ['state' => 'GA', 'cities' => ['Clyo']],
    '31304' => ['state' => 'GA', 'cities' => ['Crescent']],
    '31305' => ['state' => 'GA', 'cities' => ['Darien']],
    '31307' => ['state' => 'GA', 'cities' => ['Eden']],
    '31308' => ['state' => 'GA', 'cities' => ['Ellabell']],
    '31309' => ['state' => 'GA', 'cities' => ['Fleming']],
    '31310' => ['state' => 'GA', 'cities' => ['Hinesville']],
    '31312' => ['state' => 'GA', 'cities' => ['Guyton']],
    '31313' => ['state' => 'GA', 'cities' => ['Hinesville']],
    '31314' => ['state' => 'GA', 'cities' => ['Fort Stewart']],
    '31315' => ['state' => 'GA', 'cities' => ['Fort Stewart']],
    '31316' => ['state' => 'GA', 'cities' => ['Ludowici']],
    '31318' => ['state' => 'GA', 'cities' => ['Meldrim']],
    '31319' => ['state' => 'GA', 'cities' => ['Meridian']],
    '31320' => ['state' => 'GA', 'cities' => ['Midway']],
    '31321' => ['state' => 'GA', 'cities' => ['Pembroke']],
    '31322' => ['state' => 'GA', 'cities' => ['Pooler']],
    '31323' => ['state' => 'GA', 'cities' => ['Riceboro']],
    '31324' => ['state' => 'GA', 'cities' => ['Richmond Hill']],
    '31326' => ['state' => 'GA', 'cities' => ['Rincon']],
    '31327' => ['state' => 'GA', 'cities' => ['Sapelo Island']],
    '31328' => ['state' => 'GA', 'cities' => ['Tybee Island']],
    '31329' => ['state' => 'GA', 'cities' => ['Springfield']],
    '31331' => ['state' => 'GA', 'cities' => ['Townsend']],
    '31333' => ['state' => 'GA', 'cities' => ['Walthourville']],
];
