<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31401' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31402' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31403' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31404' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31405' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31406' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31407' => ['state' => 'GA', 'cities' => ['Port Wentworth']],
    '31408' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31409' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31410' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31411' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31412' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31414' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31415' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31416' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31418' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31419' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31420' => ['state' => 'GA', 'cities' => ['Savannah']],
    '31421' => ['state' => 'GA', 'cities' => ['Savannah']],
];
