<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31801' => ['state' => 'GA', 'cities' => ['Box Springs']],
    '31803' => ['state' => 'GA', 'cities' => ['Buena Vista']],
    '31804' => ['state' => 'GA', 'cities' => ['Cataula']],
    '31805' => ['state' => 'GA', 'cities' => ['Cusseta']],
    '31806' => ['state' => 'GA', 'cities' => ['Ellaville']],
    '31807' => ['state' => 'GA', 'cities' => ['Ellerslie']],
    '31808' => ['state' => 'GA', 'cities' => ['Fortson']],
    '31810' => ['state' => 'GA', 'cities' => ['Geneva']],
    '31811' => ['state' => 'GA', 'cities' => ['Hamilton']],
    '31812' => ['state' => 'GA', 'cities' => ['Junction City']],
    '31814' => ['state' => 'GA', 'cities' => ['Louvale']],
    '31815' => ['state' => 'GA', 'cities' => ['Lumpkin']],
    '31816' => ['state' => 'GA', 'cities' => ['Manchester']],
    '31820' => ['state' => 'GA', 'cities' => ['Midland']],
    '31821' => ['state' => 'GA', 'cities' => ['Omaha']],
    '31822' => ['state' => 'GA', 'cities' => ['Pine Mountain']],
    '31823' => ['state' => 'GA', 'cities' => ['Pine Mountain Valley']],
    '31824' => ['state' => 'GA', 'cities' => ['Preston']],
    '31825' => ['state' => 'GA', 'cities' => ['Richland']],
    '31826' => ['state' => 'GA', 'cities' => ['Shiloh']],
    '31827' => ['state' => 'GA', 'cities' => ['Talbotton']],
    '31829' => ['state' => 'GA', 'cities' => ['Upatoi']],
    '31830' => ['state' => 'GA', 'cities' => ['Warm Springs']],
    '31831' => ['state' => 'GA', 'cities' => ['Waverly Hall']],
    '31832' => ['state' => 'GA', 'cities' => ['Weston']],
    '31833' => ['state' => 'GA', 'cities' => ['West Point']],
    '31836' => ['state' => 'GA', 'cities' => ['Woodland']],
];
