<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '31901' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31902' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31903' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31904' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31905' => ['state' => 'GA', 'cities' => ['Fort Benning']],
    '31906' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31907' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31908' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31909' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31914' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31917' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31993' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31995' => ['state' => 'GA', 'cities' => ['Fort Benning']],
    '31997' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31998' => ['state' => 'GA', 'cities' => ['Columbus']],
    '31999' => ['state' => 'GA', 'cities' => ['Columbus']],
];
