<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '33206' => ['state' => 'FL', 'cities' => ['Miami']],
    '33222' => ['state' => 'FL', 'cities' => ['Miami']],
    '33231' => ['state' => 'FL', 'cities' => ['Miami']],
    '33233' => ['state' => 'FL', 'cities' => ['Miami']],
    '33234' => ['state' => 'FL', 'cities' => ['Miami']],
    '33238' => ['state' => 'FL', 'cities' => ['Miami']],
    '33239' => ['state' => 'FL', 'cities' => ['Miami Beach']],
    '33242' => ['state' => 'FL', 'cities' => ['Miami']],
    '33243' => ['state' => 'FL', 'cities' => ['Miami']],
    '33245' => ['state' => 'FL', 'cities' => ['Miami']],
    '33247' => ['state' => 'FL', 'cities' => ['Miami']],
    '33255' => ['state' => 'FL', 'cities' => ['Miami']],
    '33256' => ['state' => 'FL', 'cities' => ['Miami']],
    '33257' => ['state' => 'FL', 'cities' => ['Miami']],
    '33261' => ['state' => 'FL', 'cities' => ['Miami']],
    '33265' => ['state' => 'FL', 'cities' => ['Miami']],
    '33266' => ['state' => 'FL', 'cities' => ['Miami']],
    '33269' => ['state' => 'FL', 'cities' => ['Miami']],
    '33280' => ['state' => 'FL', 'cities' => ['Miami']],
    '33283' => ['state' => 'FL', 'cities' => ['Miami']],
    '33296' => ['state' => 'FL', 'cities' => ['Miami']],
    '33299' => ['state' => 'FL', 'cities' => ['Miami']],
];
