<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '35801' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35802' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35803' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35804' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35805' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35806' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35807' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35808' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35809' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35810' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35811' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35812' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35813' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35814' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35815' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35816' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35824' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35893' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35894' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35895' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35896' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35897' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35898' => ['state' => 'AL', 'cities' => ['Huntsville']],
    '35899' => ['state' => 'AL', 'cities' => ['Huntsville']],
];
