<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '36901' => ['state' => 'AL', 'cities' => ['Bellamy']],
    '36904' => ['state' => 'AL', 'cities' => ['Butler']],
    '36907' => ['state' => 'AL', 'cities' => ['Cuba']],
    '36908' => ['state' => 'AL', 'cities' => ['Gilbertown']],
    '36910' => ['state' => 'AL', 'cities' => ['Jachin']],
    '36912' => ['state' => 'AL', 'cities' => ['Lisman']],
    '36913' => ['state' => 'AL', 'cities' => ['Melvin']],
    '36915' => ['state' => 'AL', 'cities' => ['Needham']],
    '36916' => ['state' => 'AL', 'cities' => ['Pennington']],
    '36919' => ['state' => 'AL', 'cities' => ['Silas']],
    '36921' => ['state' => 'AL', 'cities' => ['Toxey']],
    '36922' => ['state' => 'AL', 'cities' => ['Ward']],
    '36925' => ['state' => 'AL', 'cities' => ['York']],
];
