<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '37401' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37402' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37403' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37404' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37405' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37406' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37407' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37408' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37409' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37410' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37411' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37412' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37414' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37415' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37416' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37419' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37421' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37422' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37424' => ['state' => 'TN', 'cities' => ['Chattanooga']],
    '37450' => ['state' => 'TN', 'cities' => ['Chattanooga']],
];
