<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '40701' => ['state' => 'KY', 'cities' => ['Corbin']],
    '40702' => ['state' => 'KY', 'cities' => ['Corbin']],
    '40724' => ['state' => 'KY', 'cities' => ['Bush']],
    '40729' => ['state' => 'KY', 'cities' => ['East Bernstadt']],
    '40730' => ['state' => 'KY', 'cities' => ['Emlyn']],
    '40734' => ['state' => 'KY', 'cities' => ['Gray']],
    '40737' => ['state' => 'KY', 'cities' => ['Keavy']],
    '40740' => ['state' => 'KY', 'cities' => ['Lily']],
    '40741' => ['state' => 'KY', 'cities' => ['London']],
    '40742' => ['state' => 'KY', 'cities' => ['London']],
    '40743' => ['state' => 'KY', 'cities' => ['London']],
    '40744' => ['state' => 'KY', 'cities' => ['London']],
    '40745' => ['state' => 'KY', 'cities' => ['London']],
    '40750' => ['state' => 'KY', 'cities' => ['London']],
    '40755' => ['state' => 'KY', 'cities' => ['Pittsburg']],
    '40759' => ['state' => 'KY', 'cities' => ['Rockholds']],
    '40763' => ['state' => 'KY', 'cities' => ['Siler']],
    '40769' => ['state' => 'KY', 'cities' => ['Williamsburg']],
    '40771' => ['state' => 'KY', 'cities' => ['Woodbine']],
];
