<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '41301' => ['state' => 'KY', 'cities' => ['Campton']],
    '41310' => ['state' => 'KY', 'cities' => ['Bays']],
    '41311' => ['state' => 'KY', 'cities' => ['Beattyville']],
    '41314' => ['state' => 'KY', 'cities' => ['Booneville']],
    '41317' => ['state' => 'KY', 'cities' => ['Clayhole']],
    '41332' => ['state' => 'KY', 'cities' => ['Hazel Green']],
    '41339' => ['state' => 'KY', 'cities' => ['Jackson']],
    '41347' => ['state' => 'KY', 'cities' => ['Lone']],
    '41348' => ['state' => 'KY', 'cities' => ['Lost Creek']],
    '41351' => ['state' => 'KY', 'cities' => ['Mistletoe']],
    '41352' => ['state' => 'KY', 'cities' => ['Mize']],
    '41360' => ['state' => 'KY', 'cities' => ['Pine Ridge']],
    '41364' => ['state' => 'KY', 'cities' => ['Ricetown']],
    '41365' => ['state' => 'KY', 'cities' => ['Rogers']],
    '41366' => ['state' => 'KY', 'cities' => ['Rousseau']],
    '41367' => ['state' => 'KY', 'cities' => ['Rowdy']],
    '41368' => ['state' => 'KY', 'cities' => ['Saint Helens']],
    '41385' => ['state' => 'KY', 'cities' => ['Vancleve']],
    '41386' => ['state' => 'KY', 'cities' => ['Vincent']],
    '41390' => ['state' => 'KY', 'cities' => ['Whick']],
    '41397' => ['state' => 'KY', 'cities' => ['Zoe']],
];
