<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '41408' => ['state' => 'KY', 'cities' => ['Cannel City']],
    '41413' => ['state' => 'KY', 'cities' => ['Crockett']],
    '41421' => ['state' => 'KY', 'cities' => ['Elkfork']],
    '41425' => ['state' => 'KY', 'cities' => ['Ezel']],
    '41426' => ['state' => 'KY', 'cities' => ['Falcon']],
    '41451' => ['state' => 'KY', 'cities' => ['Malone']],
    '41464' => ['state' => 'KY', 'cities' => ['Royalton']],
    '41465' => ['state' => 'KY', 'cities' => ['Salyersville']],
    '41472' => ['state' => 'KY', 'cities' => ['West Liberty']],
    '41477' => ['state' => 'KY', 'cities' => ['Wrigley']],
];
