<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '42501' => ['state' => 'KY', 'cities' => ['Somerset']],
    '42502' => ['state' => 'KY', 'cities' => ['Somerset']],
    '42503' => ['state' => 'KY', 'cities' => ['Somerset']],
    '42516' => ['state' => 'KY', 'cities' => ['Bethelridge']],
    '42518' => ['state' => 'KY', 'cities' => ['Bronston']],
    '42519' => ['state' => 'KY', 'cities' => ['Burnside']],
    '42528' => ['state' => 'KY', 'cities' => ['Dunnville']],
    '42533' => ['state' => 'KY', 'cities' => ['Ferguson']],
    '42539' => ['state' => 'KY', 'cities' => ['Liberty']],
    '42541' => ['state' => 'KY', 'cities' => ['Middleburg']],
    '42544' => ['state' => 'KY', 'cities' => ['Nancy']],
    '42553' => ['state' => 'KY', 'cities' => ['Science Hill']],
    '42558' => ['state' => 'KY', 'cities' => ['Tateville']],
    '42564' => ['state' => 'KY', 'cities' => ['West Somerset']],
    '42565' => ['state' => 'KY', 'cities' => ['Windsor']],
    '42566' => ['state' => 'KY', 'cities' => ['Yosemite']],
    '42567' => ['state' => 'KY', 'cities' => ['Eubank']],
];
