<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '42602' => ['state' => 'KY', 'cities' => ['Albany']],
    '42603' => ['state' => 'KY', 'cities' => ['Alpha']],
    '42629' => ['state' => 'KY', 'cities' => ['Jamestown']],
    '42631' => ['state' => 'KY', 'cities' => ['Marshes Siding']],
    '42633' => ['state' => 'KY', 'cities' => ['Monticello']],
    '42634' => ['state' => 'KY', 'cities' => ['Parkers Lake']],
    '42635' => ['state' => 'KY', 'cities' => ['Pine Knot']],
    '42638' => ['state' => 'KY', 'cities' => ['Revelo']],
    '42642' => ['state' => 'KY', 'cities' => ['Russell Springs']],
    '42647' => ['state' => 'KY', 'cities' => ['Stearns']],
    '42649' => ['state' => 'KY', 'cities' => ['Strunk']],
    '42653' => ['state' => 'KY', 'cities' => ['Whitley City']],
];
