<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '43802' => ['state' => 'OH', 'cities' => ['Adamsville']],
    '43803' => ['state' => 'OH', 'cities' => ['Bakersville']],
    '43804' => ['state' => 'OH', 'cities' => ['Baltic']],
    '43805' => ['state' => 'OH', 'cities' => ['Blissfield']],
    '43811' => ['state' => 'OH', 'cities' => ['Conesville']],
    '43812' => ['state' => 'OH', 'cities' => ['Coshocton']],
    '43821' => ['state' => 'OH', 'cities' => ['Dresden']],
    '43822' => ['state' => 'OH', 'cities' => ['Frazeysburg']],
    '43824' => ['state' => 'OH', 'cities' => ['Fresno']],
    '43828' => ['state' => 'OH', 'cities' => ['Keene']],
    '43830' => ['state' => 'OH', 'cities' => ['Nashport']],
    '43832' => ['state' => 'OH', 'cities' => ['Newcomerstown']],
    '43836' => ['state' => 'OH', 'cities' => ['Plainfield']],
    '43837' => ['state' => 'OH', 'cities' => ['Port Washington']],
    '43840' => ['state' => 'OH', 'cities' => ['Stone Creek']],
    '43842' => ['state' => 'OH', 'cities' => ['Trinway']],
    '43843' => ['state' => 'OH', 'cities' => ['Walhonding']],
    '43844' => ['state' => 'OH', 'cities' => ['Warsaw']],
    '43845' => ['state' => 'OH', 'cities' => ['West Lafayette']],
];
