<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '44501' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44502' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44503' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44504' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44505' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44506' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44507' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44509' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44510' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44511' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44512' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44513' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44514' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44515' => ['state' => 'OH', 'cities' => ['Youngstown']],
    '44555' => ['state' => 'OH', 'cities' => ['Youngstown']],
];
