<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '44701' => ['state' => 'OH', 'cities' => ['Canton']],
    '44702' => ['state' => 'OH', 'cities' => ['Canton']],
    '44703' => ['state' => 'OH', 'cities' => ['Canton']],
    '44704' => ['state' => 'OH', 'cities' => ['Canton']],
    '44705' => ['state' => 'OH', 'cities' => ['Canton']],
    '44706' => ['state' => 'OH', 'cities' => ['Canton']],
    '44707' => ['state' => 'OH', 'cities' => ['Canton']],
    '44708' => ['state' => 'OH', 'cities' => ['Canton']],
    '44709' => ['state' => 'OH', 'cities' => ['Canton']],
    '44710' => ['state' => 'OH', 'cities' => ['Canton']],
    '44711' => ['state' => 'OH', 'cities' => ['Canton']],
    '44714' => ['state' => 'OH', 'cities' => ['Canton']],
    '44718' => ['state' => 'OH', 'cities' => ['Canton']],
    '44720' => ['state' => 'OH', 'cities' => ['North Canton']],
    '44721' => ['state' => 'OH', 'cities' => ['Canton']],
    '44730' => ['state' => 'OH', 'cities' => ['East Canton']],
    '44735' => ['state' => 'OH', 'cities' => ['Canton']],
    '44750' => ['state' => 'OH', 'cities' => ['Canton']],
    '44767' => ['state' => 'OH', 'cities' => ['Canton']],
    '44799' => ['state' => 'OH', 'cities' => ['Canton']],
];
