<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '44901' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44902' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44903' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44904' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44905' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44906' => ['state' => 'OH', 'cities' => ['Mansfield']],
    '44907' => ['state' => 'OH', 'cities' => ['Mansfield']],
];
