<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '45501' => ['state' => 'OH', 'cities' => ['Springfield']],
    '45502' => ['state' => 'OH', 'cities' => ['Springfield']],
    '45503' => ['state' => 'OH', 'cities' => ['Springfield']],
    '45504' => ['state' => 'OH', 'cities' => ['Springfield']],
    '45505' => ['state' => 'OH', 'cities' => ['Springfield']],
    '45506' => ['state' => 'OH', 'cities' => ['Springfield']],
];
