<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '46401' => ['state' => 'IN', 'cities' => ['Gary']],
    '46402' => ['state' => 'IN', 'cities' => ['Gary']],
    '46403' => ['state' => 'IN', 'cities' => ['Gary']],
    '46404' => ['state' => 'IN', 'cities' => ['Gary']],
    '46405' => ['state' => 'IN', 'cities' => ['Lake Station']],
    '46406' => ['state' => 'IN', 'cities' => ['Gary']],
    '46407' => ['state' => 'IN', 'cities' => ['Gary']],
    '46408' => ['state' => 'IN', 'cities' => ['Gary']],
    '46409' => ['state' => 'IN', 'cities' => ['Gary']],
    '46410' => ['state' => 'IN', 'cities' => ['Merrillville']],
    '46411' => ['state' => 'IN', 'cities' => ['Merrillville']],
];
