<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '48501' => ['state' => 'MI', 'cities' => ['Flint']],
    '48502' => ['state' => 'MI', 'cities' => ['Flint']],
    '48503' => ['state' => 'MI', 'cities' => ['Flint']],
    '48504' => ['state' => 'MI', 'cities' => ['Flint']],
    '48505' => ['state' => 'MI', 'cities' => ['Flint']],
    '48506' => ['state' => 'MI', 'cities' => ['Flint']],
    '48507' => ['state' => 'MI', 'cities' => ['Flint']],
    '48509' => ['state' => 'MI', 'cities' => ['Burton']],
    '48519' => ['state' => 'MI', 'cities' => ['Burton']],
    '48529' => ['state' => 'MI', 'cities' => ['Burton']],
    '48531' => ['state' => 'MI', 'cities' => ['Flint']],
    '48532' => ['state' => 'MI', 'cities' => ['Flint']],
    '48550' => ['state' => 'MI', 'cities' => ['Flint']],
    '48551' => ['state' => 'MI', 'cities' => ['Flint']],
    '48552' => ['state' => 'MI', 'cities' => ['Flint']],
    '48553' => ['state' => 'MI', 'cities' => ['Flint']],
    '48554' => ['state' => 'MI', 'cities' => ['Flint']],
    '48555' => ['state' => 'MI', 'cities' => ['Flint']],
    '48556' => ['state' => 'MI', 'cities' => ['Flint']],
    '48557' => ['state' => 'MI', 'cities' => ['Flint']],
];
