<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '48901' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48906' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48908' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48909' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48910' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48911' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48912' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48913' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48915' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48916' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48917' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48918' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48919' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48922' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48924' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48929' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48930' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48933' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48937' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48951' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48956' => ['state' => 'MI', 'cities' => ['Lansing']],
    '48980' => ['state' => 'MI', 'cities' => ['Lansing']],
];
