<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '49101' => ['state' => 'MI', 'cities' => ['Baroda']],
    '49102' => ['state' => 'MI', 'cities' => ['Berrien Center']],
    '49103' => ['state' => 'MI', 'cities' => ['Berrien Springs']],
    '49104' => ['state' => 'MI', 'cities' => ['Berrien Springs']],
    '49106' => ['state' => 'MI', 'cities' => ['Bridgman']],
    '49107' => ['state' => 'MI', 'cities' => ['Buchanan']],
    '49111' => ['state' => 'MI', 'cities' => ['Eau Claire']],
    '49112' => ['state' => 'MI', 'cities' => ['Edwardsburg']],
    '49113' => ['state' => 'MI', 'cities' => ['Galien']],
    '49115' => ['state' => 'MI', 'cities' => ['Harbert']],
    '49116' => ['state' => 'MI', 'cities' => ['Lakeside']],
    '49117' => ['state' => 'MI', 'cities' => ['New Buffalo']],
    '49119' => ['state' => 'MI', 'cities' => ['New Troy']],
    '49120' => ['state' => 'MI', 'cities' => ['Niles']],
    '49125' => ['state' => 'MI', 'cities' => ['Sawyer']],
    '49126' => ['state' => 'MI', 'cities' => ['Sodus']],
    '49127' => ['state' => 'MI', 'cities' => ['Stevensville']],
    '49128' => ['state' => 'MI', 'cities' => ['Three Oaks']],
    '49129' => ['state' => 'MI', 'cities' => ['Union Pier']],
    '49130' => ['state' => 'MI', 'cities' => ['Union']],
];
