<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '49501' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49502' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49503' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49504' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49505' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49506' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49507' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49508' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49509' => ['state' => 'MI', 'cities' => ['Wyoming']],
    '49510' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49512' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49514' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49515' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49516' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49518' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49519' => ['state' => 'MI', 'cities' => ['Wyoming']],
    '49523' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49525' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49528' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49530' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49534' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49544' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49546' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49548' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49555' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49560' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49588' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
    '49599' => ['state' => 'MI', 'cities' => ['Grand Rapids']],
];
