<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '50701' => ['state' => 'IA', 'cities' => ['Waterloo']],
    '50702' => ['state' => 'IA', 'cities' => ['Waterloo']],
    '50703' => ['state' => 'IA', 'cities' => ['Waterloo']],
    '50704' => ['state' => 'IA', 'cities' => ['Waterloo']],
    '50707' => ['state' => 'IA', 'cities' => ['Evansdale']],
];
