<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '50801' => ['state' => 'IA', 'cities' => ['Creston']],
    '50830' => ['state' => 'IA', 'cities' => ['Afton']],
    '50831' => ['state' => 'IA', 'cities' => ['Arispe']],
    '50833' => ['state' => 'IA', 'cities' => ['Bedford']],
    '50835' => ['state' => 'IA', 'cities' => ['Benton']],
    '50836' => ['state' => 'IA', 'cities' => ['Blockton']],
    '50837' => ['state' => 'IA', 'cities' => ['Bridgewater']],
    '50839' => ['state' => 'IA', 'cities' => ['Carbon']],
    '50840' => ['state' => 'IA', 'cities' => ['Clearfield']],
    '50841' => ['state' => 'IA', 'cities' => ['Corning']],
    '50842' => ['state' => 'IA', 'cities' => ['Cromwell']],
    '50843' => ['state' => 'IA', 'cities' => ['Cumberland']],
    '50845' => ['state' => 'IA', 'cities' => ['Diagonal']],
    '50846' => ['state' => 'IA', 'cities' => ['Fontanelle']],
    '50847' => ['state' => 'IA', 'cities' => ['Grant']],
    '50848' => ['state' => 'IA', 'cities' => ['Gravity']],
    '50849' => ['state' => 'IA', 'cities' => ['Greenfield']],
    '50851' => ['state' => 'IA', 'cities' => ['Lenox']],
    '50853' => ['state' => 'IA', 'cities' => ['Massena']],
    '50854' => ['state' => 'IA', 'cities' => ['Mount Ayr']],
    '50857' => ['state' => 'IA', 'cities' => ['Nodaway']],
    '50858' => ['state' => 'IA', 'cities' => ['Orient']],
    '50859' => ['state' => 'IA', 'cities' => ['Prescott']],
    '50860' => ['state' => 'IA', 'cities' => ['Redding']],
    '50861' => ['state' => 'IA', 'cities' => ['Shannon City']],
    '50862' => ['state' => 'IA', 'cities' => ['Sharpsburg']],
    '50863' => ['state' => 'IA', 'cities' => ['Tingley']],
    '50864' => ['state' => 'IA', 'cities' => ['Villisca']],
];
