<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '50936' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50940' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50947' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50950' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50980' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50981' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50982' => ['state' => 'IA', 'cities' => ['Des Moines']],
    '50983' => ['state' => 'IA', 'cities' => ['Des Moines']],
];
