<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '51101' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51102' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51103' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51104' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51105' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51106' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51108' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51109' => ['state' => 'IA', 'cities' => ['Sioux City']],
    '51111' => ['state' => 'IA', 'cities' => ['Sioux City']],
];
