<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '51201' => ['state' => 'IA', 'cities' => ['Sheldon']],
    '51230' => ['state' => 'IA', 'cities' => ['Alvord']],
    '51231' => ['state' => 'IA', 'cities' => ['Archer']],
    '51232' => ['state' => 'IA', 'cities' => ['Ashton']],
    '51234' => ['state' => 'IA', 'cities' => ['Boyden']],
    '51235' => ['state' => 'IA', 'cities' => ['Doon']],
    '51237' => ['state' => 'IA', 'cities' => ['George']],
    '51238' => ['state' => 'IA', 'cities' => ['Hospers']],
    '51239' => ['state' => 'IA', 'cities' => ['Hull']],
    '51240' => ['state' => 'IA', 'cities' => ['Inwood']],
    '51241' => ['state' => 'IA', 'cities' => ['Larchwood']],
    '51242' => ['state' => 'IA', 'cities' => ['Lester']],
    '51243' => ['state' => 'IA', 'cities' => ['Little Rock']],
    '51244' => ['state' => 'IA', 'cities' => ['Matlock']],
    '51245' => ['state' => 'IA', 'cities' => ['Primghar']],
    '51246' => ['state' => 'IA', 'cities' => ['Rock Rapids']],
    '51247' => ['state' => 'IA', 'cities' => ['Rock Valley']],
    '51248' => ['state' => 'IA', 'cities' => ['Sanborn']],
    '51249' => ['state' => 'IA', 'cities' => ['Sibley']],
    '51250' => ['state' => 'IA', 'cities' => ['Sioux Center']],
];
