<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '51301' => ['state' => 'IA', 'cities' => ['Spencer']],
    '51331' => ['state' => 'IA', 'cities' => ['Arnolds Park']],
    '51333' => ['state' => 'IA', 'cities' => ['Dickens']],
    '51334' => ['state' => 'IA', 'cities' => ['Estherville']],
    '51338' => ['state' => 'IA', 'cities' => ['Everly']],
    '51340' => ['state' => 'IA', 'cities' => ['Fostoria']],
    '51341' => ['state' => 'IA', 'cities' => ['Gillett Grove']],
    '51342' => ['state' => 'IA', 'cities' => ['Graettinger']],
    '51343' => ['state' => 'IA', 'cities' => ['Greenville']],
    '51345' => ['state' => 'IA', 'cities' => ['Harris']],
    '51346' => ['state' => 'IA', 'cities' => ['Hartley']],
    '51347' => ['state' => 'IA', 'cities' => ['Lake Park']],
    '51350' => ['state' => 'IA', 'cities' => ['Melvin']],
    '51351' => ['state' => 'IA', 'cities' => ['Milford']],
    '51354' => ['state' => 'IA', 'cities' => ['Ocheyedan']],
    '51355' => ['state' => 'IA', 'cities' => ['Okoboji']],
    '51357' => ['state' => 'IA', 'cities' => ['Royal']],
    '51358' => ['state' => 'IA', 'cities' => ['Ruthven']],
    '51360' => ['state' => 'IA', 'cities' => ['Spirit Lake']],
    '51363' => ['state' => 'IA', 'cities' => ['Superior']],
    '51364' => ['state' => 'IA', 'cities' => ['Terril']],
    '51365' => ['state' => 'IA', 'cities' => ['Wallingford']],
    '51366' => ['state' => 'IA', 'cities' => ['Webb']],
];
