<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '51601' => ['state' => 'IA', 'cities' => ['Shenandoah']],
    '51603' => ['state' => 'IA', 'cities' => ['Shenandoah']],
    '51630' => ['state' => 'IA', 'cities' => ['Blanchard']],
    '51631' => ['state' => 'IA', 'cities' => ['Braddyville']],
    '51632' => ['state' => 'IA', 'cities' => ['Clarinda']],
    '51636' => ['state' => 'IA', 'cities' => ['Coin']],
    '51637' => ['state' => 'IA', 'cities' => ['College Springs']],
    '51638' => ['state' => 'IA', 'cities' => ['Essex']],
    '51639' => ['state' => 'IA', 'cities' => ['Farragut']],
    '51640' => ['state' => 'IA', 'cities' => ['Hamburg']],
    '51645' => ['state' => 'IA', 'cities' => ['Imogene']],
    '51646' => ['state' => 'IA', 'cities' => ['New Market']],
    '51647' => ['state' => 'IA', 'cities' => ['Northboro']],
    '51648' => ['state' => 'IA', 'cities' => ['Percival']],
    '51649' => ['state' => 'IA', 'cities' => ['Randolph']],
    '51650' => ['state' => 'IA', 'cities' => ['Riverton']],
    '51651' => ['state' => 'IA', 'cities' => ['Shambaugh']],
    '51652' => ['state' => 'IA', 'cities' => ['Sidney']],
    '51653' => ['state' => 'IA', 'cities' => ['Tabor']],
    '51654' => ['state' => 'IA', 'cities' => ['Thurman']],
    '51656' => ['state' => 'IA', 'cities' => ['Yorktown']],
];
