<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '52401' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52402' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52403' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52404' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52405' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52406' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52407' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52408' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52409' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52410' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52411' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52497' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52498' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
    '52499' => ['state' => 'IA', 'cities' => ['Cedar Rapids']],
];
