<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '53401' => ['state' => 'WI', 'cities' => ['Racine']],
    '53402' => ['state' => 'WI', 'cities' => ['Racine']],
    '53403' => ['state' => 'WI', 'cities' => ['Racine']],
    '53404' => ['state' => 'WI', 'cities' => ['Racine']],
    '53405' => ['state' => 'WI', 'cities' => ['Racine']],
    '53406' => ['state' => 'WI', 'cities' => ['Racine']],
    '53407' => ['state' => 'WI', 'cities' => ['Racine']],
    '53408' => ['state' => 'WI', 'cities' => ['Racine']],
];
