<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '53801' => ['state' => 'WI', 'cities' => ['Bagley']],
    '53802' => ['state' => 'WI', 'cities' => ['Beetown']],
    '53803' => ['state' => 'WI', 'cities' => ['Benton']],
    '53804' => ['state' => 'WI', 'cities' => ['Bloomington']],
    '53805' => ['state' => 'WI', 'cities' => ['Boscobel']],
    '53806' => ['state' => 'WI', 'cities' => ['Cassville']],
    '53807' => ['state' => 'WI', 'cities' => ['Cuba City']],
    '53808' => ['state' => 'WI', 'cities' => ['Dickeyville']],
    '53809' => ['state' => 'WI', 'cities' => ['Fennimore']],
    '53810' => ['state' => 'WI', 'cities' => ['Glen Haven']],
    '53811' => ['state' => 'WI', 'cities' => ['Hazel Green']],
    '53812' => ['state' => 'WI', 'cities' => ['Kieler']],
    '53813' => ['state' => 'WI', 'cities' => ['Lancaster']],
    '53816' => ['state' => 'WI', 'cities' => ['Mount Hope']],
    '53817' => ['state' => 'WI', 'cities' => ['Patch Grove']],
    '53818' => ['state' => 'WI', 'cities' => ['Platteville']],
    '53820' => ['state' => 'WI', 'cities' => ['Potosi']],
    '53821' => ['state' => 'WI', 'cities' => ['Prairie Du Chien']],
    '53824' => ['state' => 'WI', 'cities' => ['Sinsinawa']],
    '53825' => ['state' => 'WI', 'cities' => ['Stitzer']],
    '53826' => ['state' => 'WI', 'cities' => ['Wauzeka']],
    '53827' => ['state' => 'WI', 'cities' => ['Woodman']],
];
