<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '54001' => ['state' => 'WI', 'cities' => ['Amery']],
    '54002' => ['state' => 'WI', 'cities' => ['Baldwin']],
    '54003' => ['state' => 'WI', 'cities' => ['Beldenville']],
    '54004' => ['state' => 'WI', 'cities' => ['Clayton']],
    '54005' => ['state' => 'WI', 'cities' => ['Clear Lake']],
    '54006' => ['state' => 'WI', 'cities' => ['Cushing']],
    '54007' => ['state' => 'WI', 'cities' => ['Deer Park']],
    '54009' => ['state' => 'WI', 'cities' => ['Dresser']],
    '54010' => ['state' => 'WI', 'cities' => ['East Ellsworth']],
    '54011' => ['state' => 'WI', 'cities' => ['Ellsworth']],
    '54013' => ['state' => 'WI', 'cities' => ['Glenwood City']],
    '54014' => ['state' => 'WI', 'cities' => ['Hager City']],
    '54015' => ['state' => 'WI', 'cities' => ['Hammond']],
    '54016' => ['state' => 'WI', 'cities' => ['Hudson']],
    '54017' => ['state' => 'WI', 'cities' => ['New Richmond']],
    '54020' => ['state' => 'WI', 'cities' => ['Osceola']],
    '54021' => ['state' => 'WI', 'cities' => ['Prescott']],
    '54022' => ['state' => 'WI', 'cities' => ['River Falls']],
    '54023' => ['state' => 'WI', 'cities' => ['Roberts']],
    '54024' => ['state' => 'WI', 'cities' => ['Saint Croix Falls']],
    '54025' => ['state' => 'WI', 'cities' => ['Somerset']],
    '54026' => ['state' => 'WI', 'cities' => ['Star Prairie']],
    '54027' => ['state' => 'WI', 'cities' => ['Wilson']],
    '54028' => ['state' => 'WI', 'cities' => ['Woodville']],
    '54082' => ['state' => 'WI', 'cities' => ['Houlton']],
];
