<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '55550' => ['state' => 'MN', 'cities' => ['Young America']],
    '55551' => ['state' => 'MN', 'cities' => ['Young America']],
    '55553' => ['state' => 'MN', 'cities' => ['Young America']],
    '55554' => ['state' => 'MN', 'cities' => ['Norwood']],
    '55558' => ['state' => 'MN', 'cities' => ['Young America']],
    '55568' => ['state' => 'MN', 'cities' => ['Young America']],
    '55569' => ['state' => 'MN', 'cities' => ['Osseo']],
    '55570' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55571' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55572' => ['state' => 'MN', 'cities' => ['Rockford']],
    '55573' => ['state' => 'MN', 'cities' => ['Young America']],
    '55574' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55575' => ['state' => 'MN', 'cities' => ['Howard Lake']],
    '55576' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55577' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55578' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55579' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55583' => ['state' => 'MN', 'cities' => ['Norwood']],
    '55592' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55593' => ['state' => 'MN', 'cities' => ['Maple Plain']],
    '55594' => ['state' => 'MN', 'cities' => ['Young America']],
    '55595' => ['state' => 'MN', 'cities' => ['Loretto']],
    '55596' => ['state' => 'MN', 'cities' => ['Loretto']],
    '55597' => ['state' => 'MN', 'cities' => ['Loretto']],
    '55598' => ['state' => 'MN', 'cities' => ['Loretto']],
    '55599' => ['state' => 'MN', 'cities' => ['Loretto']],
];
