<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '55601' => ['state' => 'MN', 'cities' => ['Beaver Bay']],
    '55602' => ['state' => 'MN', 'cities' => ['Brimson']],
    '55603' => ['state' => 'MN', 'cities' => ['Finland']],
    '55604' => ['state' => 'MN', 'cities' => ['Grand Marais']],
    '55605' => ['state' => 'MN', 'cities' => ['Grand Portage']],
    '55606' => ['state' => 'MN', 'cities' => ['Hovland']],
    '55607' => ['state' => 'MN', 'cities' => ['Isabella']],
    '55609' => ['state' => 'MN', 'cities' => ['Knife River']],
    '55612' => ['state' => 'MN', 'cities' => ['Lutsen']],
    '55613' => ['state' => 'MN', 'cities' => ['Schroeder']],
    '55614' => ['state' => 'MN', 'cities' => ['Silver Bay']],
    '55615' => ['state' => 'MN', 'cities' => ['Tofte']],
    '55616' => ['state' => 'MN', 'cities' => ['Two Harbors']],
];
