<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '55801' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55802' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55803' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55804' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55805' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55806' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55807' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55808' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55810' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55811' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55812' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55814' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55815' => ['state' => 'MN', 'cities' => ['Duluth']],
    '55816' => ['state' => 'MN', 'cities' => ['Duluth']],
];
