<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '56901' => ['state' => 'DC', 'cities' => ['Washington']],
    '56915' => ['state' => 'DC', 'cities' => ['Washington']],
    '56920' => ['state' => 'DC', 'cities' => ['Washington']],
    '56933' => ['state' => 'DC', 'cities' => ['Washington']],
    '56944' => ['state' => 'DC', 'cities' => ['Washington']],
    '56972' => ['state' => 'DC', 'cities' => ['Washington']],
];
