<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '57101' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57103' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57104' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57105' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57106' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57107' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57108' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57109' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57110' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57117' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57118' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57186' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57193' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57197' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
    '57198' => ['state' => 'SD', 'cities' => ['Sioux Falls']],
];
