<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '58102' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58103' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58104' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58105' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58106' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58107' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58108' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58109' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58121' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58122' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58124' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58125' => ['state' => 'ND', 'cities' => ['Fargo']],
    '58126' => ['state' => 'ND', 'cities' => ['Fargo']],
];
