<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '58801' => ['state' => 'ND', 'cities' => ['Williston']],
    '58802' => ['state' => 'ND', 'cities' => ['Williston']],
    '58803' => ['state' => 'ND', 'cities' => ['Williston']],
    '58830' => ['state' => 'ND', 'cities' => ['Alamo']],
    '58831' => ['state' => 'ND', 'cities' => ['Alexander']],
    '58833' => ['state' => 'ND', 'cities' => ['Ambrose']],
    '58835' => ['state' => 'ND', 'cities' => ['Arnegard']],
    '58838' => ['state' => 'ND', 'cities' => ['Cartwright']],
    '58843' => ['state' => 'ND', 'cities' => ['Epping']],
    '58844' => ['state' => 'ND', 'cities' => ['Fortuna']],
    '58845' => ['state' => 'ND', 'cities' => ['Grenora']],
    '58847' => ['state' => 'ND', 'cities' => ['Keene']],
    '58849' => ['state' => 'ND', 'cities' => ['Ray']],
    '58852' => ['state' => 'ND', 'cities' => ['Tioga']],
    '58853' => ['state' => 'ND', 'cities' => ['Trenton']],
    '58854' => ['state' => 'ND', 'cities' => ['Watford City']],
    '58856' => ['state' => 'ND', 'cities' => ['Zahl']],
];
