<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '59101' => ['state' => 'MT', 'cities' => ['Billings']],
    '59102' => ['state' => 'MT', 'cities' => ['Billings']],
    '59103' => ['state' => 'MT', 'cities' => ['Billings']],
    '59104' => ['state' => 'MT', 'cities' => ['Billings']],
    '59105' => ['state' => 'MT', 'cities' => ['Billings']],
    '59106' => ['state' => 'MT', 'cities' => ['Billings']],
    '59107' => ['state' => 'MT', 'cities' => ['Billings']],
    '59108' => ['state' => 'MT', 'cities' => ['Billings']],
    '59111' => ['state' => 'MT', 'cities' => ['Billings']],
    '59112' => ['state' => 'MT', 'cities' => ['Billings']],
    '59114' => ['state' => 'MT', 'cities' => ['Billings']],
    '59115' => ['state' => 'MT', 'cities' => ['Billings']],
    '59116' => ['state' => 'MT', 'cities' => ['Billings']],
    '59117' => ['state' => 'MT', 'cities' => ['Billings']],
];
