<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '59501' => ['state' => 'MT', 'cities' => ['Havre']],
    '59520' => ['state' => 'MT', 'cities' => ['Big Sandy']],
    '59521' => ['state' => 'MT', 'cities' => ['Box Elder']],
    '59522' => ['state' => 'MT', 'cities' => ['Chester']],
    '59523' => ['state' => 'MT', 'cities' => ['Chinook']],
    '59524' => ['state' => 'MT', 'cities' => ['Dodson']],
    '59525' => ['state' => 'MT', 'cities' => ['Gildford']],
    '59526' => ['state' => 'MT', 'cities' => ['Harlem']],
    '59527' => ['state' => 'MT', 'cities' => ['Hays']],
    '59528' => ['state' => 'MT', 'cities' => ['Hingham']],
    '59529' => ['state' => 'MT', 'cities' => ['Hogeland']],
    '59530' => ['state' => 'MT', 'cities' => ['Inverness']],
    '59531' => ['state' => 'MT', 'cities' => ['Joplin']],
    '59532' => ['state' => 'MT', 'cities' => ['Kremlin']],
    '59535' => ['state' => 'MT', 'cities' => ['Lloyd']],
    '59537' => ['state' => 'MT', 'cities' => ['Loring']],
    '59538' => ['state' => 'MT', 'cities' => ['Malta']],
    '59540' => ['state' => 'MT', 'cities' => ['Rudyard']],
    '59542' => ['state' => 'MT', 'cities' => ['Turner']],
    '59544' => ['state' => 'MT', 'cities' => ['Whitewater']],
    '59545' => ['state' => 'MT', 'cities' => ['Whitlash']],
    '59546' => ['state' => 'MT', 'cities' => ['Zortman']],
    '59547' => ['state' => 'MT', 'cities' => ['Zurich']],
];
