<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '59601' => ['state' => 'MT', 'cities' => ['Helena']],
    '59602' => ['state' => 'MT', 'cities' => ['Helena']],
    '59604' => ['state' => 'MT', 'cities' => ['Helena']],
    '59620' => ['state' => 'MT', 'cities' => ['Helena']],
    '59623' => ['state' => 'MT', 'cities' => ['Helena']],
    '59624' => ['state' => 'MT', 'cities' => ['Helena']],
    '59625' => ['state' => 'MT', 'cities' => ['Helena']],
    '59626' => ['state' => 'MT', 'cities' => ['Helena']],
    '59631' => ['state' => 'MT', 'cities' => ['Basin']],
    '59632' => ['state' => 'MT', 'cities' => ['Boulder']],
    '59633' => ['state' => 'MT', 'cities' => ['Canyon Creek']],
    '59634' => ['state' => 'MT', 'cities' => ['Clancy']],
    '59635' => ['state' => 'MT', 'cities' => ['East Helena']],
    '59636' => ['state' => 'MT', 'cities' => ['Fort Harrison']],
    '59638' => ['state' => 'MT', 'cities' => ['Jefferson City']],
    '59639' => ['state' => 'MT', 'cities' => ['Lincoln']],
    '59640' => ['state' => 'MT', 'cities' => ['Marysville']],
    '59641' => ['state' => 'MT', 'cities' => ['Radersburg']],
    '59642' => ['state' => 'MT', 'cities' => ['Ringling']],
    '59643' => ['state' => 'MT', 'cities' => ['Toston']],
    '59644' => ['state' => 'MT', 'cities' => ['Townsend']],
    '59645' => ['state' => 'MT', 'cities' => ['White Sulphur Springs']],
    '59647' => ['state' => 'MT', 'cities' => ['Winston']],
    '59648' => ['state' => 'MT', 'cities' => ['Wolf Creek']],
];
