<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '60201' => ['state' => 'IL', 'cities' => ['Evanston']],
    '60202' => ['state' => 'IL', 'cities' => ['Evanston']],
    '60203' => ['state' => 'IL', 'cities' => ['Evanston']],
    '60204' => ['state' => 'IL', 'cities' => ['Evanston']],
    '60208' => ['state' => 'IL', 'cities' => ['Evanston']],
    '60209' => ['state' => 'IL', 'cities' => ['Evanston']],
];
