<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '60301' => ['state' => 'IL', 'cities' => ['Oak Park']],
    '60302' => ['state' => 'IL', 'cities' => ['Oak Park']],
    '60303' => ['state' => 'IL', 'cities' => ['Oak Park']],
    '60304' => ['state' => 'IL', 'cities' => ['Oak Park']],
    '60305' => ['state' => 'IL', 'cities' => ['River Forest']],
    '60399' => ['state' => 'IL', 'cities' => ['Wood Dale']],
];
