<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '60701' => ['state' => 'IL', 'cities' => ['Chicago']],
    '60706' => ['state' => 'IL', 'cities' => ['Harwood Heights']],
    '60707' => ['state' => 'IL', 'cities' => ['Elmwood Park']],
    '60712' => ['state' => 'IL', 'cities' => ['Lincolnwood']],
    '60714' => ['state' => 'IL', 'cities' => ['Niles']],
];
