<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '60803' => ['state' => 'IL', 'cities' => ['Alsip']],
    '60804' => ['state' => 'IL', 'cities' => ['Cicero']],
    '60805' => ['state' => 'IL', 'cities' => ['Evergreen Park']],
    '60827' => ['state' => 'IL', 'cities' => ['Riverdale']],
];
