<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '64501' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64502' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64503' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64504' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64505' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64506' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64507' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
    '64508' => ['state' => 'MO', 'cities' => ['Saint Joseph']],
];
