<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '65801' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65802' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65803' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65804' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65805' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65806' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65807' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65808' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65809' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65810' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65814' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65817' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65890' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65897' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65898' => ['state' => 'MO', 'cities' => ['Springfield']],
    '65899' => ['state' => 'MO', 'cities' => ['Springfield']],
];
