<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '66101' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66102' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66103' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66104' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66105' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66106' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66109' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66110' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66111' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66112' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66113' => ['state' => 'KS', 'cities' => ['Edwardsville']],
    '66115' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66117' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66118' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66119' => ['state' => 'KS', 'cities' => ['Kansas City']],
    '66160' => ['state' => 'KS', 'cities' => ['Kansas City']],
];
