<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '67301' => ['state' => 'KS', 'cities' => ['Independence']],
    '67330' => ['state' => 'KS', 'cities' => ['Altamont']],
    '67332' => ['state' => 'KS', 'cities' => ['Bartlett']],
    '67333' => ['state' => 'KS', 'cities' => ['Caney']],
    '67334' => ['state' => 'KS', 'cities' => ['Chautauqua']],
    '67335' => ['state' => 'KS', 'cities' => ['Cherryvale']],
    '67336' => ['state' => 'KS', 'cities' => ['Chetopa']],
    '67337' => ['state' => 'KS', 'cities' => ['Coffeyville']],
    '67340' => ['state' => 'KS', 'cities' => ['Dearing']],
    '67341' => ['state' => 'KS', 'cities' => ['Dennis']],
    '67342' => ['state' => 'KS', 'cities' => ['Edna']],
    '67344' => ['state' => 'KS', 'cities' => ['Elk City']],
    '67345' => ['state' => 'KS', 'cities' => ['Elk Falls']],
    '67346' => ['state' => 'KS', 'cities' => ['Grenola']],
    '67347' => ['state' => 'KS', 'cities' => ['Havana']],
    '67349' => ['state' => 'KS', 'cities' => ['Howard']],
    '67351' => ['state' => 'KS', 'cities' => ['Liberty']],
    '67352' => ['state' => 'KS', 'cities' => ['Longton']],
    '67353' => ['state' => 'KS', 'cities' => ['Moline']],
    '67354' => ['state' => 'KS', 'cities' => ['Mound Valley']],
    '67355' => ['state' => 'KS', 'cities' => ['Niotaze']],
    '67356' => ['state' => 'KS', 'cities' => ['Oswego']],
    '67357' => ['state' => 'KS', 'cities' => ['Parsons']],
    '67360' => ['state' => 'KS', 'cities' => ['Peru']],
    '67361' => ['state' => 'KS', 'cities' => ['Sedan']],
    '67363' => ['state' => 'KS', 'cities' => ['Sycamore']],
    '67364' => ['state' => 'KS', 'cities' => ['Tyro']],
];
