<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '67701' => ['state' => 'KS', 'cities' => ['Colby']],
    '67730' => ['state' => 'KS', 'cities' => ['Atwood']],
    '67731' => ['state' => 'KS', 'cities' => ['Bird City']],
    '67732' => ['state' => 'KS', 'cities' => ['Brewster']],
    '67733' => ['state' => 'KS', 'cities' => ['Edson']],
    '67734' => ['state' => 'KS', 'cities' => ['Gem']],
    '67735' => ['state' => 'KS', 'cities' => ['Goodland']],
    '67736' => ['state' => 'KS', 'cities' => ['Gove']],
    '67737' => ['state' => 'KS', 'cities' => ['Grainfield']],
    '67738' => ['state' => 'KS', 'cities' => ['Grinnell']],
    '67739' => ['state' => 'KS', 'cities' => ['Herndon']],
    '67740' => ['state' => 'KS', 'cities' => ['Hoxie']],
    '67741' => ['state' => 'KS', 'cities' => ['Kanorado']],
    '67743' => ['state' => 'KS', 'cities' => ['Levant']],
    '67744' => ['state' => 'KS', 'cities' => ['Ludell']],
    '67745' => ['state' => 'KS', 'cities' => ['Mc Donald']],
    '67747' => ['state' => 'KS', 'cities' => ['Monument']],
    '67748' => ['state' => 'KS', 'cities' => ['Oakley']],
    '67749' => ['state' => 'KS', 'cities' => ['Oberlin']],
    '67751' => ['state' => 'KS', 'cities' => ['Park']],
    '67752' => ['state' => 'KS', 'cities' => ['Quinter']],
    '67753' => ['state' => 'KS', 'cities' => ['Rexford']],
    '67756' => ['state' => 'KS', 'cities' => ['Saint Francis']],
    '67757' => ['state' => 'KS', 'cities' => ['Selden']],
    '67758' => ['state' => 'KS', 'cities' => ['Sharon Springs']],
    '67761' => ['state' => 'KS', 'cities' => ['Wallace']],
    '67762' => ['state' => 'KS', 'cities' => ['Weskan']],
    '67764' => ['state' => 'KS', 'cities' => ['Winona']],
];
