<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '67901' => ['state' => 'KS', 'cities' => ['Liberal']],
    '67905' => ['state' => 'KS', 'cities' => ['Liberal']],
    '67950' => ['state' => 'KS', 'cities' => ['Elkhart']],
    '67951' => ['state' => 'KS', 'cities' => ['Hugoton']],
    '67952' => ['state' => 'KS', 'cities' => ['Moscow']],
    '67953' => ['state' => 'KS', 'cities' => ['Richfield']],
    '67954' => ['state' => 'KS', 'cities' => ['Rolla']],
];
