<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '69001' => ['state' => 'NE', 'cities' => ['Mc Cook']],
    '69020' => ['state' => 'NE', 'cities' => ['Bartley']],
    '69021' => ['state' => 'NE', 'cities' => ['Benkelman']],
    '69022' => ['state' => 'NE', 'cities' => ['Cambridge']],
    '69023' => ['state' => 'NE', 'cities' => ['Champion']],
    '69024' => ['state' => 'NE', 'cities' => ['Culbertson']],
    '69025' => ['state' => 'NE', 'cities' => ['Curtis']],
    '69026' => ['state' => 'NE', 'cities' => ['Danbury']],
    '69027' => ['state' => 'NE', 'cities' => ['Enders']],
    '69028' => ['state' => 'NE', 'cities' => ['Eustis']],
    '69029' => ['state' => 'NE', 'cities' => ['Farnam']],
    '69030' => ['state' => 'NE', 'cities' => ['Haigler']],
    '69032' => ['state' => 'NE', 'cities' => ['Hayes Center']],
    '69033' => ['state' => 'NE', 'cities' => ['Imperial']],
    '69034' => ['state' => 'NE', 'cities' => ['Indianola']],
    '69036' => ['state' => 'NE', 'cities' => ['Lebanon']],
    '69037' => ['state' => 'NE', 'cities' => ['Max']],
    '69038' => ['state' => 'NE', 'cities' => ['Maywood']],
    '69039' => ['state' => 'NE', 'cities' => ['Moorefield']],
    '69040' => ['state' => 'NE', 'cities' => ['Palisade']],
    '69041' => ['state' => 'NE', 'cities' => ['Parks']],
    '69042' => ['state' => 'NE', 'cities' => ['Stockville']],
    '69043' => ['state' => 'NE', 'cities' => ['Stratton']],
    '69044' => ['state' => 'NE', 'cities' => ['Trenton']],
    '69045' => ['state' => 'NE', 'cities' => ['Wauneta']],
    '69046' => ['state' => 'NE', 'cities' => ['Wilsonville']],
];
