<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '69201' => ['state' => 'NE', 'cities' => ['Valentine']],
    '69210' => ['state' => 'NE', 'cities' => ['Ainsworth']],
    '69211' => ['state' => 'NE', 'cities' => ['Cody']],
    '69212' => ['state' => 'NE', 'cities' => ['Crookston']],
    '69214' => ['state' => 'NE', 'cities' => ['Johnstown']],
    '69216' => ['state' => 'NE', 'cities' => ['Kilgore']],
    '69217' => ['state' => 'NE', 'cities' => ['Long Pine']],
    '69218' => ['state' => 'NE', 'cities' => ['Merriman']],
    '69219' => ['state' => 'NE', 'cities' => ['Nenzel']],
    '69220' => ['state' => 'NE', 'cities' => ['Sparks']],
    '69221' => ['state' => 'NE', 'cities' => ['Wood Lake']],
];
