<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '72201' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72202' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72203' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72204' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72205' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72206' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72207' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72209' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72210' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72211' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72212' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72214' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72215' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72216' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72217' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72219' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72221' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72222' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72223' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72225' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72227' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72231' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72255' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72260' => ['state' => 'AR', 'cities' => ['Little Rock']],
    '72295' => ['state' => 'AR', 'cities' => ['Little Rock']],
];
