<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '73801' => ['state' => 'OK', 'cities' => ['Woodward']],
    '73802' => ['state' => 'OK', 'cities' => ['Woodward']],
    '73832' => ['state' => 'OK', 'cities' => ['Arnett']],
    '73834' => ['state' => 'OK', 'cities' => ['Buffalo']],
    '73835' => ['state' => 'OK', 'cities' => ['Camargo']],
    '73838' => ['state' => 'OK', 'cities' => ['Chester']],
    '73840' => ['state' => 'OK', 'cities' => ['Fargo']],
    '73841' => ['state' => 'OK', 'cities' => ['Fort Supply']],
    '73842' => ['state' => 'OK', 'cities' => ['Freedom']],
    '73843' => ['state' => 'OK', 'cities' => ['Gage']],
    '73844' => ['state' => 'OK', 'cities' => ['Gate']],
    '73848' => ['state' => 'OK', 'cities' => ['Laverne']],
    '73851' => ['state' => 'OK', 'cities' => ['May']],
    '73852' => ['state' => 'OK', 'cities' => ['Mooreland']],
    '73853' => ['state' => 'OK', 'cities' => ['Mutual']],
    '73855' => ['state' => 'OK', 'cities' => ['Rosston']],
    '73857' => ['state' => 'OK', 'cities' => ['Sharon']],
    '73858' => ['state' => 'OK', 'cities' => ['Shattuck']],
    '73859' => ['state' => 'OK', 'cities' => ['Vici']],
    '73860' => ['state' => 'OK', 'cities' => ['Waynoka']],
];
