<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '73901' => ['state' => 'OK', 'cities' => ['Adams']],
    '73931' => ['state' => 'OK', 'cities' => ['Balko']],
    '73932' => ['state' => 'OK', 'cities' => ['Beaver']],
    '73933' => ['state' => 'OK', 'cities' => ['Boise City']],
    '73937' => ['state' => 'OK', 'cities' => ['Felt']],
    '73938' => ['state' => 'OK', 'cities' => ['Forgan']],
    '73939' => ['state' => 'OK', 'cities' => ['Goodwell']],
    '73942' => ['state' => 'OK', 'cities' => ['Guymon']],
    '73944' => ['state' => 'OK', 'cities' => ['Hardesty']],
    '73945' => ['state' => 'OK', 'cities' => ['Hooker']],
    '73946' => ['state' => 'OK', 'cities' => ['Kenton']],
    '73947' => ['state' => 'OK', 'cities' => ['Keyes']],
    '73949' => ['state' => 'OK', 'cities' => ['Texhoma']],
    '73950' => ['state' => 'OK', 'cities' => ['Turpin']],
    '73951' => ['state' => 'OK', 'cities' => ['Tyrone']],
    '73960' => ['state' => 'TX', 'cities' => ['Texhoma']],
];
