<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '74601' => ['state' => 'OK', 'cities' => ['Ponca City']],
    '74602' => ['state' => 'OK', 'cities' => ['Ponca City']],
    '74604' => ['state' => 'OK', 'cities' => ['Ponca City']],
    '74630' => ['state' => 'OK', 'cities' => ['Billings']],
    '74631' => ['state' => 'OK', 'cities' => ['Blackwell']],
    '74632' => ['state' => 'OK', 'cities' => ['Braman']],
    '74633' => ['state' => 'OK', 'cities' => ['Burbank']],
    '74636' => ['state' => 'OK', 'cities' => ['Deer Creek']],
    '74637' => ['state' => 'OK', 'cities' => ['Fairfax']],
    '74640' => ['state' => 'OK', 'cities' => ['Hunter']],
    '74641' => ['state' => 'OK', 'cities' => ['Kaw City']],
    '74643' => ['state' => 'OK', 'cities' => ['Lamont']],
    '74644' => ['state' => 'OK', 'cities' => ['Marland']],
    '74646' => ['state' => 'OK', 'cities' => ['Nardin']],
    '74647' => ['state' => 'OK', 'cities' => ['Newkirk']],
    '74650' => ['state' => 'OK', 'cities' => ['Ralston']],
    '74651' => ['state' => 'OK', 'cities' => ['Red Rock']],
    '74652' => ['state' => 'OK', 'cities' => ['Shidler']],
    '74653' => ['state' => 'OK', 'cities' => ['Tonkawa']],
];
