<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '75501' => ['state' => 'TX', 'cities' => ['Texarkana']],
    '75503' => ['state' => 'TX', 'cities' => ['Texarkana']],
    '75504' => ['state' => 'TX', 'cities' => ['Texarkana']],
    '75505' => ['state' => 'TX', 'cities' => ['Texarkana']],
    '75507' => ['state' => 'TX', 'cities' => ['Texarkana']],
    '75550' => ['state' => 'TX', 'cities' => ['Annona']],
    '75551' => ['state' => 'TX', 'cities' => ['Atlanta']],
    '75554' => ['state' => 'TX', 'cities' => ['Avery']],
    '75555' => ['state' => 'TX', 'cities' => ['Bivins']],
    '75556' => ['state' => 'TX', 'cities' => ['Bloomburg']],
    '75558' => ['state' => 'TX', 'cities' => ['Cookville']],
    '75559' => ['state' => 'TX', 'cities' => ['De Kalb']],
    '75560' => ['state' => 'TX', 'cities' => ['Douglassville']],
    '75561' => ['state' => 'TX', 'cities' => ['Hooks']],
    '75562' => ['state' => 'TX', 'cities' => ['Kildare']],
    '75563' => ['state' => 'TX', 'cities' => ['Linden']],
    '75564' => ['state' => 'TX', 'cities' => ['Lodi']],
    '75565' => ['state' => 'TX', 'cities' => ['Mc Leod']],
    '75566' => ['state' => 'TX', 'cities' => ['Marietta']],
    '75567' => ['state' => 'TX', 'cities' => ['Maud']],
    '75568' => ['state' => 'TX', 'cities' => ['Naples']],
    '75569' => ['state' => 'TX', 'cities' => ['Nash']],
    '75570' => ['state' => 'TX', 'cities' => ['New Boston']],
    '75571' => ['state' => 'TX', 'cities' => ['Omaha']],
    '75572' => ['state' => 'TX', 'cities' => ['Queen City']],
    '75573' => ['state' => 'TX', 'cities' => ['Redwater']],
    '75574' => ['state' => 'TX', 'cities' => ['Simms']],
    '75599' => ['state' => 'TX', 'cities' => ['Texarkana']],
];
