<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '76701' => ['state' => 'TX', 'cities' => ['Waco']],
    '76702' => ['state' => 'TX', 'cities' => ['Waco']],
    '76703' => ['state' => 'TX', 'cities' => ['Waco']],
    '76704' => ['state' => 'TX', 'cities' => ['Waco']],
    '76705' => ['state' => 'TX', 'cities' => ['Waco']],
    '76706' => ['state' => 'TX', 'cities' => ['Waco']],
    '76707' => ['state' => 'TX', 'cities' => ['Waco']],
    '76708' => ['state' => 'TX', 'cities' => ['Waco']],
    '76710' => ['state' => 'TX', 'cities' => ['Waco']],
    '76711' => ['state' => 'TX', 'cities' => ['Waco']],
    '76712' => ['state' => 'TX', 'cities' => ['Woodway']],
    '76714' => ['state' => 'TX', 'cities' => ['Waco']],
    '76715' => ['state' => 'TX', 'cities' => ['Waco']],
    '76716' => ['state' => 'TX', 'cities' => ['Waco']],
    '76797' => ['state' => 'TX', 'cities' => ['Waco']],
    '76798' => ['state' => 'TX', 'cities' => ['Waco']],
    '76799' => ['state' => 'TX', 'cities' => ['Waco']],
];
