<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '76901' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76902' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76903' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76904' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76905' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76906' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76908' => ['state' => 'TX', 'cities' => ['Goodfellow Afb']],
    '76909' => ['state' => 'TX', 'cities' => ['San Angelo']],
    '76930' => ['state' => 'TX', 'cities' => ['Barnhart']],
    '76932' => ['state' => 'TX', 'cities' => ['Big Lake']],
    '76933' => ['state' => 'TX', 'cities' => ['Bronte']],
    '76934' => ['state' => 'TX', 'cities' => ['Carlsbad']],
    '76935' => ['state' => 'TX', 'cities' => ['Christoval']],
    '76936' => ['state' => 'TX', 'cities' => ['Eldorado']],
    '76937' => ['state' => 'TX', 'cities' => ['Eola']],
    '76939' => ['state' => 'TX', 'cities' => ['Knickerbocker']],
    '76940' => ['state' => 'TX', 'cities' => ['Mereta']],
    '76941' => ['state' => 'TX', 'cities' => ['Mertzon']],
    '76943' => ['state' => 'TX', 'cities' => ['Ozona']],
    '76945' => ['state' => 'TX', 'cities' => ['Robert Lee']],
    '76949' => ['state' => 'TX', 'cities' => ['Silver']],
    '76950' => ['state' => 'TX', 'cities' => ['Sonora']],
    '76951' => ['state' => 'TX', 'cities' => ['Sterling City']],
    '76953' => ['state' => 'TX', 'cities' => ['Tennyson']],
    '76955' => ['state' => 'TX', 'cities' => ['Vancourt']],
    '76957' => ['state' => 'TX', 'cities' => ['Wall']],
    '76958' => ['state' => 'TX', 'cities' => ['Water Valley']],
];
