<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '77701' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77702' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77703' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77704' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77705' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77706' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77707' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77708' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77710' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77713' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77720' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77725' => ['state' => 'TX', 'cities' => ['Beaumont']],
    '77726' => ['state' => 'TX', 'cities' => ['Beaumont']],
];
