<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '78931' => ['state' => 'TX', 'cities' => ['Bleiblerville']],
    '78932' => ['state' => 'TX', 'cities' => ['Carmine']],
    '78933' => ['state' => 'TX', 'cities' => ['Cat Spring']],
    '78934' => ['state' => 'TX', 'cities' => ['Columbus']],
    '78935' => ['state' => 'TX', 'cities' => ['Alleyton']],
    '78938' => ['state' => 'TX', 'cities' => ['Ellinger']],
    '78940' => ['state' => 'TX', 'cities' => ['Fayetteville']],
    '78941' => ['state' => 'TX', 'cities' => ['Flatonia']],
    '78942' => ['state' => 'TX', 'cities' => ['Giddings']],
    '78943' => ['state' => 'TX', 'cities' => ['Glidden']],
    '78944' => ['state' => 'TX', 'cities' => ['Industry']],
    '78945' => ['state' => 'TX', 'cities' => ['La Grange']],
    '78946' => ['state' => 'TX', 'cities' => ['Ledbetter']],
    '78947' => ['state' => 'TX', 'cities' => ['Lexington']],
    '78948' => ['state' => 'TX', 'cities' => ['Lincoln']],
    '78949' => ['state' => 'TX', 'cities' => ['Muldoon']],
    '78950' => ['state' => 'TX', 'cities' => ['New Ulm']],
    '78951' => ['state' => 'TX', 'cities' => ['Oakland']],
    '78952' => ['state' => 'TX', 'cities' => ['Plum']],
    '78953' => ['state' => 'TX', 'cities' => ['Rosanky']],
    '78954' => ['state' => 'TX', 'cities' => ['Round Top']],
    '78956' => ['state' => 'TX', 'cities' => ['Schulenburg']],
    '78957' => ['state' => 'TX', 'cities' => ['Smithville']],
    '78959' => ['state' => 'TX', 'cities' => ['Waelder']],
    '78960' => ['state' => 'TX', 'cities' => ['Warda']],
    '78961' => ['state' => 'TX', 'cities' => ['Round Top']],
    '78962' => ['state' => 'TX', 'cities' => ['Weimar']],
    '78963' => ['state' => 'TX', 'cities' => ['West Point']],
];
