<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '79101' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79102' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79103' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79104' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79105' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79106' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79107' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79108' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79109' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79110' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79111' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79114' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79116' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79117' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79118' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79119' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79120' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79121' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79124' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79159' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79166' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79168' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79172' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79174' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79178' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79185' => ['state' => 'TX', 'cities' => ['Amarillo']],
    '79189' => ['state' => 'TX', 'cities' => ['Amarillo']],
];
