<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '79401' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79402' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79403' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79404' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79406' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79407' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79408' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79409' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79410' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79411' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79412' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79413' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79414' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79415' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79416' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79423' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79424' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79430' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79452' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79453' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79457' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79464' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79490' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79491' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79493' => ['state' => 'TX', 'cities' => ['Lubbock']],
    '79499' => ['state' => 'TX', 'cities' => ['Lubbock']],
];
