<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '79601' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79602' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79603' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79604' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79605' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79606' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79607' => ['state' => 'TX', 'cities' => ['Dyess Afb']],
    '79608' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79697' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79698' => ['state' => 'TX', 'cities' => ['Abilene']],
    '79699' => ['state' => 'TX', 'cities' => ['Abilene']],
];
