<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '79821' => ['state' => 'TX', 'cities' => ['Anthony']],
    '79830' => ['state' => 'TX', 'cities' => ['Alpine']],
    '79831' => ['state' => 'TX', 'cities' => ['Alpine']],
    '79832' => ['state' => 'TX', 'cities' => ['Alpine']],
    '79834' => ['state' => 'TX', 'cities' => ['Big Bend National Park']],
    '79835' => ['state' => 'TX', 'cities' => ['Canutillo']],
    '79836' => ['state' => 'TX', 'cities' => ['Clint']],
    '79837' => ['state' => 'TX', 'cities' => ['Dell City']],
    '79838' => ['state' => 'TX', 'cities' => ['Fabens']],
    '79839' => ['state' => 'TX', 'cities' => ['Fort Hancock']],
    '79842' => ['state' => 'TX', 'cities' => ['Marathon']],
    '79843' => ['state' => 'TX', 'cities' => ['Marfa']],
    '79845' => ['state' => 'TX', 'cities' => ['Presidio']],
    '79846' => ['state' => 'TX', 'cities' => ['Redford']],
    '79847' => ['state' => 'TX', 'cities' => ['Salt Flat']],
    '79848' => ['state' => 'TX', 'cities' => ['Sanderson']],
    '79849' => ['state' => 'TX', 'cities' => ['San Elizario']],
    '79851' => ['state' => 'TX', 'cities' => ['Sierra Blanca']],
    '79852' => ['state' => 'TX', 'cities' => ['Terlingua']],
    '79853' => ['state' => 'TX', 'cities' => ['Tornillo']],
    '79854' => ['state' => 'TX', 'cities' => ['Valentine']],
    '79855' => ['state' => 'TX', 'cities' => ['Van Horn']],
];
