<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '80301' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80302' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80303' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80304' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80305' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80306' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80307' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80308' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80309' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80310' => ['state' => 'CO', 'cities' => ['Boulder']],
    '80314' => ['state' => 'CO', 'cities' => ['Boulder']],
];
