<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '81301' => ['state' => 'CO', 'cities' => ['Durango']],
    '81302' => ['state' => 'CO', 'cities' => ['Durango']],
    '81303' => ['state' => 'CO', 'cities' => ['Durango']],
    '81320' => ['state' => 'CO', 'cities' => ['Cahone']],
    '81321' => ['state' => 'CO', 'cities' => ['Cortez']],
    '81323' => ['state' => 'CO', 'cities' => ['Dolores']],
    '81324' => ['state' => 'CO', 'cities' => ['Dove Creek']],
    '81325' => ['state' => 'CO', 'cities' => ['Egnar']],
    '81326' => ['state' => 'CO', 'cities' => ['Hesperus']],
    '81327' => ['state' => 'CO', 'cities' => ['Lewis']],
    '81328' => ['state' => 'CO', 'cities' => ['Mancos']],
    '81329' => ['state' => 'CO', 'cities' => ['Marvel']],
    '81330' => ['state' => 'CO', 'cities' => ['Mesa Verde National Park']],
    '81331' => ['state' => 'CO', 'cities' => ['Pleasant View']],
    '81332' => ['state' => 'CO', 'cities' => ['Rico']],
    '81334' => ['state' => 'CO', 'cities' => ['Towaoc']],
    '81335' => ['state' => 'CO', 'cities' => ['Yellow Jacket']],
];
