<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '81401' => ['state' => 'CO', 'cities' => ['Montrose']],
    '81402' => ['state' => 'CO', 'cities' => ['Montrose']],
    '81403' => ['state' => 'CO', 'cities' => ['Montrose']],
    '81410' => ['state' => 'CO', 'cities' => ['Austin']],
    '81411' => ['state' => 'CO', 'cities' => ['Bedrock']],
    '81413' => ['state' => 'CO', 'cities' => ['Cedaredge']],
    '81414' => ['state' => 'CO', 'cities' => ['Cory']],
    '81415' => ['state' => 'CO', 'cities' => ['Crawford']],
    '81416' => ['state' => 'CO', 'cities' => ['Delta']],
    '81418' => ['state' => 'CO', 'cities' => ['Eckert']],
    '81419' => ['state' => 'CO', 'cities' => ['Hotchkiss']],
    '81420' => ['state' => 'CO', 'cities' => ['Lazear']],
    '81422' => ['state' => 'CO', 'cities' => ['Naturita']],
    '81423' => ['state' => 'CO', 'cities' => ['Norwood']],
    '81424' => ['state' => 'CO', 'cities' => ['Nucla']],
    '81425' => ['state' => 'CO', 'cities' => ['Olathe']],
    '81426' => ['state' => 'CO', 'cities' => ['Ophir']],
    '81427' => ['state' => 'CO', 'cities' => ['Ouray']],
    '81428' => ['state' => 'CO', 'cities' => ['Paonia']],
    '81429' => ['state' => 'CO', 'cities' => ['Paradox']],
    '81430' => ['state' => 'CO', 'cities' => ['Placerville']],
    '81431' => ['state' => 'CO', 'cities' => ['Redvale']],
    '81432' => ['state' => 'CO', 'cities' => ['Ridgway']],
    '81433' => ['state' => 'CO', 'cities' => ['Silverton']],
    '81434' => ['state' => 'CO', 'cities' => ['Somerset']],
    '81435' => ['state' => 'CO', 'cities' => ['Telluride']],
];
