<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '81501' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81502' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81503' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81504' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81505' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81506' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81507' => ['state' => 'CO', 'cities' => ['Grand Junction']],
    '81520' => ['state' => 'CO', 'cities' => ['Clifton']],
    '81521' => ['state' => 'CO', 'cities' => ['Fruita']],
    '81522' => ['state' => 'CO', 'cities' => ['Gateway']],
    '81523' => ['state' => 'CO', 'cities' => ['Glade Park']],
    '81524' => ['state' => 'CO', 'cities' => ['Loma']],
    '81525' => ['state' => 'CO', 'cities' => ['Mack']],
    '81526' => ['state' => 'CO', 'cities' => ['Palisade']],
    '81527' => ['state' => 'CO', 'cities' => ['Whitewater']],
];
