<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82001' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82002' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82003' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82005' => ['state' => 'WY', 'cities' => ['Fe Warren Afb']],
    '82006' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82007' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82008' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82009' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82010' => ['state' => 'WY', 'cities' => ['Cheyenne']],
    '82050' => ['state' => 'WY', 'cities' => ['Albin']],
    '82051' => ['state' => 'WY', 'cities' => ['Bosler']],
    '82052' => ['state' => 'WY', 'cities' => ['Buford']],
    '82053' => ['state' => 'WY', 'cities' => ['Burns']],
    '82054' => ['state' => 'WY', 'cities' => ['Carpenter']],
    '82055' => ['state' => 'WY', 'cities' => ['Centennial']],
    '82058' => ['state' => 'WY', 'cities' => ['Garrett']],
    '82059' => ['state' => 'WY', 'cities' => ['Granite Canon']],
    '82060' => ['state' => 'WY', 'cities' => ['Hillsdale']],
    '82061' => ['state' => 'WY', 'cities' => ['Horse Creek']],
    '82063' => ['state' => 'WY', 'cities' => ['Jelm']],
    '82070' => ['state' => 'WY', 'cities' => ['Laramie']],
    '82071' => ['state' => 'WY', 'cities' => ['Laramie']],
    '82072' => ['state' => 'WY', 'cities' => ['Laramie']],
    '82073' => ['state' => 'WY', 'cities' => ['Laramie']],
    '82081' => ['state' => 'WY', 'cities' => ['Meriden']],
    '82082' => ['state' => 'WY', 'cities' => ['Pine Bluffs']],
    '82083' => ['state' => 'WY', 'cities' => ['Rock River']],
    '82084' => ['state' => 'WY', 'cities' => ['Tie Siding']],
];
