<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82201' => ['state' => 'WY', 'cities' => ['Wheatland']],
    '82210' => ['state' => 'WY', 'cities' => ['Chugwater']],
    '82212' => ['state' => 'WY', 'cities' => ['Fort Laramie']],
    '82213' => ['state' => 'WY', 'cities' => ['Glendo']],
    '82214' => ['state' => 'WY', 'cities' => ['Guernsey']],
    '82215' => ['state' => 'WY', 'cities' => ['Hartville']],
    '82217' => ['state' => 'WY', 'cities' => ['Hawk Springs']],
    '82218' => ['state' => 'WY', 'cities' => ['Huntley']],
    '82219' => ['state' => 'WY', 'cities' => ['Jay Em']],
    '82221' => ['state' => 'WY', 'cities' => ['Lagrange']],
    '82222' => ['state' => 'WY', 'cities' => ['Lance Creek']],
    '82223' => ['state' => 'WY', 'cities' => ['Lingle']],
    '82224' => ['state' => 'WY', 'cities' => ['Lost Springs']],
    '82225' => ['state' => 'WY', 'cities' => ['Lusk']],
    '82227' => ['state' => 'WY', 'cities' => ['Manville']],
    '82229' => ['state' => 'WY', 'cities' => ['Shawnee']],
    '82240' => ['state' => 'WY', 'cities' => ['Torrington']],
    '82242' => ['state' => 'WY', 'cities' => ['Van Tassell']],
    '82243' => ['state' => 'WY', 'cities' => ['Veteran']],
    '82244' => ['state' => 'WY', 'cities' => ['Yoder']],
];
