<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82301' => ['state' => 'WY', 'cities' => ['Rawlins']],
    '82310' => ['state' => 'WY', 'cities' => ['Jeffrey City']],
    '82321' => ['state' => 'WY', 'cities' => ['Baggs']],
    '82322' => ['state' => 'WY', 'cities' => ['Bairoil']],
    '82323' => ['state' => 'WY', 'cities' => ['Dixon']],
    '82324' => ['state' => 'WY', 'cities' => ['Elk Mountain']],
    '82325' => ['state' => 'WY', 'cities' => ['Encampment']],
    '82327' => ['state' => 'WY', 'cities' => ['Hanna']],
    '82329' => ['state' => 'WY', 'cities' => ['Medicine Bow']],
    '82331' => ['state' => 'WY', 'cities' => ['Saratoga']],
    '82332' => ['state' => 'WY', 'cities' => ['Savery']],
    '82334' => ['state' => 'WY', 'cities' => ['Sinclair']],
    '82335' => ['state' => 'WY', 'cities' => ['Walcott']],
    '82336' => ['state' => 'WY', 'cities' => ['Wamsutter']],
];
