<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82401' => ['state' => 'WY', 'cities' => ['Worland']],
    '82410' => ['state' => 'WY', 'cities' => ['Basin']],
    '82411' => ['state' => 'WY', 'cities' => ['Burlington']],
    '82412' => ['state' => 'WY', 'cities' => ['Byron']],
    '82414' => ['state' => 'WY', 'cities' => ['Cody']],
    '82420' => ['state' => 'WY', 'cities' => ['Cowley']],
    '82421' => ['state' => 'WY', 'cities' => ['Deaver']],
    '82422' => ['state' => 'WY', 'cities' => ['Emblem']],
    '82423' => ['state' => 'WY', 'cities' => ['Frannie']],
    '82426' => ['state' => 'WY', 'cities' => ['Greybull']],
    '82428' => ['state' => 'WY', 'cities' => ['Hyattville']],
    '82430' => ['state' => 'WY', 'cities' => ['Kirby']],
    '82431' => ['state' => 'WY', 'cities' => ['Lovell']],
    '82432' => ['state' => 'WY', 'cities' => ['Manderson']],
    '82433' => ['state' => 'WY', 'cities' => ['Meeteetse']],
    '82434' => ['state' => 'WY', 'cities' => ['Otto']],
    '82435' => ['state' => 'WY', 'cities' => ['Powell']],
    '82440' => ['state' => 'WY', 'cities' => ['Ralston']],
    '82441' => ['state' => 'WY', 'cities' => ['Shell']],
    '82442' => ['state' => 'WY', 'cities' => ['Ten Sleep']],
    '82443' => ['state' => 'WY', 'cities' => ['Thermopolis']],
    '82450' => ['state' => 'WY', 'cities' => ['Wapiti']],
];
