<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82501' => ['state' => 'WY', 'cities' => ['Riverton']],
    '82510' => ['state' => 'WY', 'cities' => ['Arapahoe']],
    '82512' => ['state' => 'WY', 'cities' => ['Crowheart']],
    '82513' => ['state' => 'WY', 'cities' => ['Dubois']],
    '82514' => ['state' => 'WY', 'cities' => ['Fort Washakie']],
    '82515' => ['state' => 'WY', 'cities' => ['Hudson']],
    '82516' => ['state' => 'WY', 'cities' => ['Kinnear']],
    '82520' => ['state' => 'WY', 'cities' => ['Lander']],
    '82523' => ['state' => 'WY', 'cities' => ['Pavillion']],
    '82524' => ['state' => 'WY', 'cities' => ['Saint Stephens']],
];
