<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82601' => ['state' => 'WY', 'cities' => ['Casper']],
    '82602' => ['state' => 'WY', 'cities' => ['Casper']],
    '82604' => ['state' => 'WY', 'cities' => ['Casper']],
    '82605' => ['state' => 'WY', 'cities' => ['Casper']],
    '82609' => ['state' => 'WY', 'cities' => ['Casper']],
    '82615' => ['state' => 'WY', 'cities' => ['Shirley Basin']],
    '82620' => ['state' => 'WY', 'cities' => ['Alcova']],
    '82630' => ['state' => 'WY', 'cities' => ['Arminto']],
    '82633' => ['state' => 'WY', 'cities' => ['Douglas']],
    '82635' => ['state' => 'WY', 'cities' => ['Edgerton']],
    '82636' => ['state' => 'WY', 'cities' => ['Evansville']],
    '82637' => ['state' => 'WY', 'cities' => ['Glenrock']],
    '82638' => ['state' => 'WY', 'cities' => ['Hiland']],
    '82639' => ['state' => 'WY', 'cities' => ['Kaycee']],
    '82640' => ['state' => 'WY', 'cities' => ['Linch']],
    '82642' => ['state' => 'WY', 'cities' => ['Lysite']],
    '82643' => ['state' => 'WY', 'cities' => ['Midwest']],
    '82644' => ['state' => 'WY', 'cities' => ['Mills']],
    '82646' => ['state' => 'WY', 'cities' => ['Natrona']],
    '82648' => ['state' => 'WY', 'cities' => ['Powder River']],
    '82649' => ['state' => 'WY', 'cities' => ['Shoshoni']],
];
