<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82701' => ['state' => 'WY', 'cities' => ['Newcastle']],
    '82710' => ['state' => 'WY', 'cities' => ['Aladdin']],
    '82711' => ['state' => 'WY', 'cities' => ['Alva']],
    '82712' => ['state' => 'WY', 'cities' => ['Beulah']],
    '82714' => ['state' => 'WY', 'cities' => ['Devils Tower']],
    '82715' => ['state' => 'WY', 'cities' => ['Four Corners']],
    '82716' => ['state' => 'WY', 'cities' => ['Gillette']],
    '82717' => ['state' => 'WY', 'cities' => ['Gillette']],
    '82718' => ['state' => 'WY', 'cities' => ['Gillette']],
    '82720' => ['state' => 'WY', 'cities' => ['Hulett']],
    '82721' => ['state' => 'WY', 'cities' => ['Moorcroft']],
    '82723' => ['state' => 'WY', 'cities' => ['Osage']],
    '82725' => ['state' => 'WY', 'cities' => ['Recluse']],
    '82727' => ['state' => 'WY', 'cities' => ['Rozet']],
    '82729' => ['state' => 'WY', 'cities' => ['Sundance']],
    '82730' => ['state' => 'WY', 'cities' => ['Upton']],
    '82731' => ['state' => 'WY', 'cities' => ['Weston']],
    '82732' => ['state' => 'WY', 'cities' => ['Wright']],
];
