<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82801' => ['state' => 'WY', 'cities' => ['Sheridan']],
    '82831' => ['state' => 'WY', 'cities' => ['Arvada']],
    '82832' => ['state' => 'WY', 'cities' => ['Banner']],
    '82833' => ['state' => 'WY', 'cities' => ['Big Horn']],
    '82834' => ['state' => 'WY', 'cities' => ['Buffalo']],
    '82835' => ['state' => 'WY', 'cities' => ['Clearmont']],
    '82836' => ['state' => 'WY', 'cities' => ['Dayton']],
    '82837' => ['state' => 'WY', 'cities' => ['Leiter']],
    '82838' => ['state' => 'WY', 'cities' => ['Parkman']],
    '82839' => ['state' => 'WY', 'cities' => ['Ranchester']],
    '82840' => ['state' => 'WY', 'cities' => ['Saddlestring']],
    '82842' => ['state' => 'WY', 'cities' => ['Story']],
    '82844' => ['state' => 'WY', 'cities' => ['Wolf']],
    '82845' => ['state' => 'WY', 'cities' => ['Wyarno']],
];
