<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '82901' => ['state' => 'WY', 'cities' => ['Rock Springs']],
    '82902' => ['state' => 'WY', 'cities' => ['Rock Springs']],
    '82922' => ['state' => 'WY', 'cities' => ['Bondurant']],
    '82923' => ['state' => 'WY', 'cities' => ['Boulder']],
    '82925' => ['state' => 'WY', 'cities' => ['Cora']],
    '82929' => ['state' => 'WY', 'cities' => ['Little America']],
    '82930' => ['state' => 'WY', 'cities' => ['Evanston']],
    '82931' => ['state' => 'WY', 'cities' => ['Evanston']],
    '82932' => ['state' => 'WY', 'cities' => ['Farson']],
    '82933' => ['state' => 'WY', 'cities' => ['Fort Bridger']],
    '82934' => ['state' => 'WY', 'cities' => ['Granger']],
    '82935' => ['state' => 'WY', 'cities' => ['Green River']],
    '82936' => ['state' => 'WY', 'cities' => ['Lonetree']],
    '82937' => ['state' => 'WY', 'cities' => ['Lyman']],
    '82938' => ['state' => 'WY', 'cities' => ['Mc Kinnon']],
    '82939' => ['state' => 'WY', 'cities' => ['Mountain View']],
    '82941' => ['state' => 'WY', 'cities' => ['Pinedale']],
    '82942' => ['state' => 'WY', 'cities' => ['Point Of Rocks']],
    '82943' => ['state' => 'WY', 'cities' => ['Reliance']],
    '82944' => ['state' => 'WY', 'cities' => ['Robertson']],
    '82945' => ['state' => 'WY', 'cities' => ['Superior']],
];
