<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '83001' => ['state' => 'WY', 'cities' => ['Jackson']],
    '83002' => ['state' => 'WY', 'cities' => ['Jackson']],
    '83011' => ['state' => 'WY', 'cities' => ['Kelly']],
    '83012' => ['state' => 'WY', 'cities' => ['Moose']],
    '83013' => ['state' => 'WY', 'cities' => ['Moran']],
    '83014' => ['state' => 'WY', 'cities' => ['Wilson']],
    '83025' => ['state' => 'WY', 'cities' => ['Teton Village']],
];
