<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '83101' => ['state' => 'WY', 'cities' => ['Kemmerer']],
    '83110' => ['state' => 'WY', 'cities' => ['Afton']],
    '83111' => ['state' => 'WY', 'cities' => ['Auburn']],
    '83112' => ['state' => 'WY', 'cities' => ['Bedford']],
    '83113' => ['state' => 'WY', 'cities' => ['Big Piney']],
    '83114' => ['state' => 'WY', 'cities' => ['Cokeville']],
    '83115' => ['state' => 'WY', 'cities' => ['Daniel']],
    '83116' => ['state' => 'WY', 'cities' => ['Diamondville']],
    '83118' => ['state' => 'WY', 'cities' => ['Etna']],
    '83119' => ['state' => 'WY', 'cities' => ['Fairview']],
    '83120' => ['state' => 'WY', 'cities' => ['Freedom']],
    '83121' => ['state' => 'WY', 'cities' => ['Frontier']],
    '83122' => ['state' => 'WY', 'cities' => ['Grover']],
    '83123' => ['state' => 'WY', 'cities' => ['La Barge']],
    '83124' => ['state' => 'WY', 'cities' => ['Opal']],
    '83126' => ['state' => 'WY', 'cities' => ['Smoot']],
    '83127' => ['state' => 'WY', 'cities' => ['Thayne']],
    '83128' => ['state' => 'WY', 'cities' => ['Alpine']],
];
