<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '83501' => ['state' => 'ID', 'cities' => ['Lewiston']],
    '83520' => ['state' => 'ID', 'cities' => ['Ahsahka']],
    '83522' => ['state' => 'ID', 'cities' => ['Cottonwood']],
    '83523' => ['state' => 'ID', 'cities' => ['Craigmont']],
    '83524' => ['state' => 'ID', 'cities' => ['Culdesac']],
    '83525' => ['state' => 'ID', 'cities' => ['Elk City']],
    '83526' => ['state' => 'ID', 'cities' => ['Ferdinand']],
    '83530' => ['state' => 'ID', 'cities' => ['Grangeville']],
    '83531' => ['state' => 'ID', 'cities' => ['Fenn']],
    '83533' => ['state' => 'ID', 'cities' => ['Greencreek']],
    '83535' => ['state' => 'ID', 'cities' => ['Juliaetta']],
    '83536' => ['state' => 'ID', 'cities' => ['Kamiah']],
    '83537' => ['state' => 'ID', 'cities' => ['Kendrick']],
    '83539' => ['state' => 'ID', 'cities' => ['Kooskia']],
    '83540' => ['state' => 'ID', 'cities' => ['Lapwai']],
    '83541' => ['state' => 'ID', 'cities' => ['Lenore']],
    '83542' => ['state' => 'ID', 'cities' => ['Lucile']],
    '83543' => ['state' => 'ID', 'cities' => ['Nezperce']],
    '83544' => ['state' => 'ID', 'cities' => ['Orofino']],
    '83545' => ['state' => 'ID', 'cities' => ['Peck']],
    '83546' => ['state' => 'ID', 'cities' => ['Pierce']],
    '83547' => ['state' => 'ID', 'cities' => ['Pollock']],
    '83548' => ['state' => 'ID', 'cities' => ['Reubens']],
    '83549' => ['state' => 'ID', 'cities' => ['Riggins']],
    '83552' => ['state' => 'ID', 'cities' => ['Stites']],
    '83553' => ['state' => 'ID', 'cities' => ['Weippe']],
    '83554' => ['state' => 'ID', 'cities' => ['White Bird']],
    '83555' => ['state' => 'ID', 'cities' => ['Winchester']],
];
