<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '84201' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84244' => ['state' => 'UT', 'cities' => ['Ogden']],
];
