<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '84401' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84402' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84403' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84404' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84405' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84407' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84408' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84409' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84412' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84414' => ['state' => 'UT', 'cities' => ['Ogden']],
    '84415' => ['state' => 'UT', 'cities' => ['Ogden']],
];
