<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '84501' => ['state' => 'UT', 'cities' => ['Price']],
    '84510' => ['state' => 'UT', 'cities' => ['Aneth']],
    '84511' => ['state' => 'UT', 'cities' => ['Blanding']],
    '84512' => ['state' => 'UT', 'cities' => ['Bluff']],
    '84513' => ['state' => 'UT', 'cities' => ['Castle Dale']],
    '84515' => ['state' => 'UT', 'cities' => ['Cisco']],
    '84516' => ['state' => 'UT', 'cities' => ['Clawson']],
    '84518' => ['state' => 'UT', 'cities' => ['Cleveland']],
    '84520' => ['state' => 'UT', 'cities' => ['East Carbon']],
    '84521' => ['state' => 'UT', 'cities' => ['Elmo']],
    '84522' => ['state' => 'UT', 'cities' => ['Emery']],
    '84523' => ['state' => 'UT', 'cities' => ['Ferron']],
    '84525' => ['state' => 'UT', 'cities' => ['Green River']],
    '84526' => ['state' => 'UT', 'cities' => ['Helper']],
    '84528' => ['state' => 'UT', 'cities' => ['Huntington']],
    '84529' => ['state' => 'UT', 'cities' => ['Kenilworth']],
    '84530' => ['state' => 'UT', 'cities' => ['La Sal']],
    '84531' => ['state' => 'UT', 'cities' => ['Mexican Hat']],
    '84532' => ['state' => 'UT', 'cities' => ['Moab']],
    '84533' => ['state' => 'UT', 'cities' => ['Lake Powell']],
    '84534' => ['state' => 'UT', 'cities' => ['Montezuma Creek']],
    '84535' => ['state' => 'UT', 'cities' => ['Monticello']],
    '84536' => ['state' => 'UT', 'cities' => ['Monument Valley']],
    '84537' => ['state' => 'UT', 'cities' => ['Orangeville']],
    '84539' => ['state' => 'UT', 'cities' => ['Sunnyside']],
    '84540' => ['state' => 'UT', 'cities' => ['Thompson']],
    '84542' => ['state' => 'UT', 'cities' => ['Wellington']],
];
