<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '85501' => ['state' => 'AZ', 'cities' => ['Globe']],
    '85502' => ['state' => 'AZ', 'cities' => ['Globe']],
    '85530' => ['state' => 'AZ', 'cities' => ['Bylas']],
    '85531' => ['state' => 'AZ', 'cities' => ['Central']],
    '85532' => ['state' => 'AZ', 'cities' => ['Claypool']],
    '85533' => ['state' => 'AZ', 'cities' => ['Clifton']],
    '85534' => ['state' => 'AZ', 'cities' => ['Duncan']],
    '85535' => ['state' => 'AZ', 'cities' => ['Eden']],
    '85536' => ['state' => 'AZ', 'cities' => ['Fort Thomas']],
    '85539' => ['state' => 'AZ', 'cities' => ['Miami']],
    '85540' => ['state' => 'AZ', 'cities' => ['Morenci']],
    '85541' => ['state' => 'AZ', 'cities' => ['Payson']],
    '85542' => ['state' => 'AZ', 'cities' => ['Peridot']],
    '85543' => ['state' => 'AZ', 'cities' => ['Pima']],
    '85544' => ['state' => 'AZ', 'cities' => ['Pine']],
    '85545' => ['state' => 'AZ', 'cities' => ['Roosevelt']],
    '85546' => ['state' => 'AZ', 'cities' => ['Safford']],
    '85547' => ['state' => 'AZ', 'cities' => ['Payson']],
    '85548' => ['state' => 'AZ', 'cities' => ['Safford']],
    '85550' => ['state' => 'AZ', 'cities' => ['San Carlos']],
    '85551' => ['state' => 'AZ', 'cities' => ['Solomon']],
    '85552' => ['state' => 'AZ', 'cities' => ['Thatcher']],
    '85553' => ['state' => 'AZ', 'cities' => ['Tonto Basin']],
    '85554' => ['state' => 'AZ', 'cities' => ['Young']],
];
