<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '85901' => ['state' => 'AZ', 'cities' => ['Show Low']],
    '85902' => ['state' => 'AZ', 'cities' => ['Show Low']],
    '85911' => ['state' => 'AZ', 'cities' => ['Cibecue']],
    '85912' => ['state' => 'AZ', 'cities' => ['White Mountain Lake']],
    '85920' => ['state' => 'AZ', 'cities' => ['Alpine']],
    '85922' => ['state' => 'AZ', 'cities' => ['Blue']],
    '85923' => ['state' => 'AZ', 'cities' => ['Clay Springs']],
    '85924' => ['state' => 'AZ', 'cities' => ['Concho']],
    '85925' => ['state' => 'AZ', 'cities' => ['Eagar']],
    '85926' => ['state' => 'AZ', 'cities' => ['Fort Apache']],
    '85927' => ['state' => 'AZ', 'cities' => ['Greer']],
    '85928' => ['state' => 'AZ', 'cities' => ['Heber']],
    '85929' => ['state' => 'AZ', 'cities' => ['Lakeside']],
    '85930' => ['state' => 'AZ', 'cities' => ['Mcnary']],
    '85931' => ['state' => 'AZ', 'cities' => ['Forest Lakes']],
    '85932' => ['state' => 'AZ', 'cities' => ['Nutrioso']],
    '85933' => ['state' => 'AZ', 'cities' => ['Overgaard']],
    '85934' => ['state' => 'AZ', 'cities' => ['Pinedale']],
    '85935' => ['state' => 'AZ', 'cities' => ['Pinetop']],
    '85936' => ['state' => 'AZ', 'cities' => ['Saint Johns']],
    '85937' => ['state' => 'AZ', 'cities' => ['Snowflake']],
    '85938' => ['state' => 'AZ', 'cities' => ['Springerville']],
    '85939' => ['state' => 'AZ', 'cities' => ['Taylor']],
    '85940' => ['state' => 'AZ', 'cities' => ['Vernon']],
    '85941' => ['state' => 'AZ', 'cities' => ['Whiteriver']],
    '85942' => ['state' => 'AZ', 'cities' => ['Woodruff']],
];
