<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '86502' => ['state' => 'AZ', 'cities' => ['Chambers']],
    '86503' => ['state' => 'AZ', 'cities' => ['Chinle']],
    '86504' => ['state' => 'AZ', 'cities' => ['Fort Defiance']],
    '86505' => ['state' => 'AZ', 'cities' => ['Ganado']],
    '86506' => ['state' => 'AZ', 'cities' => ['Houck']],
    '86507' => ['state' => 'AZ', 'cities' => ['Lukachukai']],
    '86508' => ['state' => 'AZ', 'cities' => ['Lupton']],
    '86510' => ['state' => 'AZ', 'cities' => ['Pinon']],
    '86511' => ['state' => 'AZ', 'cities' => ['Saint Michaels']],
    '86512' => ['state' => 'AZ', 'cities' => ['Sanders']],
    '86514' => ['state' => 'AZ', 'cities' => ['Teec Nos Pos']],
    '86515' => ['state' => 'AZ', 'cities' => ['Window Rock']],
    '86520' => ['state' => 'AZ', 'cities' => ['Blue Gap']],
    '86535' => ['state' => 'AZ', 'cities' => ['Dennehotso']],
    '86538' => ['state' => 'AZ', 'cities' => ['Many Farms']],
    '86540' => ['state' => 'AZ', 'cities' => ['Nazlini']],
    '86544' => ['state' => 'AZ', 'cities' => ['Red Valley']],
    '86545' => ['state' => 'AZ', 'cities' => ['Rock Point']],
    '86547' => ['state' => 'AZ', 'cities' => ['Round Rock']],
    '86556' => ['state' => 'AZ', 'cities' => ['Tsaile']],
];
