<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '87301' => ['state' => 'NM', 'cities' => ['Gallup']],
    '87302' => ['state' => 'NM', 'cities' => ['Gallup']],
    '87305' => ['state' => 'NM', 'cities' => ['Gallup']],
    '87310' => ['state' => 'NM', 'cities' => ['Brimhall']],
    '87311' => ['state' => 'NM', 'cities' => ['Church Rock']],
    '87312' => ['state' => 'NM', 'cities' => ['Continental Divide']],
    '87313' => ['state' => 'NM', 'cities' => ['Crownpoint']],
    '87315' => ['state' => 'NM', 'cities' => ['Fence Lake']],
    '87316' => ['state' => 'NM', 'cities' => ['Fort Wingate']],
    '87317' => ['state' => 'NM', 'cities' => ['Gamerco']],
    '87319' => ['state' => 'NM', 'cities' => ['Mentmore']],
    '87320' => ['state' => 'NM', 'cities' => ['Mexican Springs']],
    '87321' => ['state' => 'NM', 'cities' => ['Ramah']],
    '87322' => ['state' => 'NM', 'cities' => ['Rehoboth']],
    '87323' => ['state' => 'NM', 'cities' => ['Thoreau']],
    '87325' => ['state' => 'NM', 'cities' => ['Tohatchi']],
    '87326' => ['state' => 'NM', 'cities' => ['Vanderwagen']],
    '87327' => ['state' => 'NM', 'cities' => ['Zuni']],
    '87328' => ['state' => 'NM', 'cities' => ['Navajo']],
    '87347' => ['state' => 'NM', 'cities' => ['Jamestown']],
    '87357' => ['state' => 'NM', 'cities' => ['Pinehill']],
    '87364' => ['state' => 'NM', 'cities' => ['Sheep Springs']],
    '87365' => ['state' => 'NM', 'cities' => ['Smith Lake']],
    '87375' => ['state' => 'NM', 'cities' => ['Yatahey']],
];
