<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '87401' => ['state' => 'NM', 'cities' => ['Farmington']],
    '87402' => ['state' => 'NM', 'cities' => ['Farmington']],
    '87410' => ['state' => 'NM', 'cities' => ['Aztec']],
    '87412' => ['state' => 'NM', 'cities' => ['Blanco']],
    '87413' => ['state' => 'NM', 'cities' => ['Bloomfield']],
    '87415' => ['state' => 'NM', 'cities' => ['Flora Vista']],
    '87416' => ['state' => 'NM', 'cities' => ['Fruitland']],
    '87417' => ['state' => 'NM', 'cities' => ['Kirtland']],
    '87418' => ['state' => 'NM', 'cities' => ['La Plata']],
    '87419' => ['state' => 'NM', 'cities' => ['Navajo Dam']],
    '87420' => ['state' => 'NM', 'cities' => ['Shiprock']],
    '87421' => ['state' => 'NM', 'cities' => ['Waterflow']],
    '87455' => ['state' => 'NM', 'cities' => ['Newcomb']],
    '87461' => ['state' => 'NM', 'cities' => ['Sanostee']],
    '87499' => ['state' => 'NM', 'cities' => ['Farmington']],
];
