<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '87801' => ['state' => 'NM', 'cities' => ['Socorro']],
    '87820' => ['state' => 'NM', 'cities' => ['Aragon']],
    '87821' => ['state' => 'NM', 'cities' => ['Datil']],
    '87823' => ['state' => 'NM', 'cities' => ['Lemitar']],
    '87824' => ['state' => 'NM', 'cities' => ['Luna']],
    '87825' => ['state' => 'NM', 'cities' => ['Magdalena']],
    '87827' => ['state' => 'NM', 'cities' => ['Pie Town']],
    '87828' => ['state' => 'NM', 'cities' => ['Polvadera']],
    '87829' => ['state' => 'NM', 'cities' => ['Quemado']],
    '87830' => ['state' => 'NM', 'cities' => ['Reserve']],
    '87831' => ['state' => 'NM', 'cities' => ['San Acacia']],
    '87832' => ['state' => 'NM', 'cities' => ['San Antonio']],
];
