<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '87901' => ['state' => 'NM', 'cities' => ['Truth Or Consequences']],
    '87930' => ['state' => 'NM', 'cities' => ['Arrey']],
    '87931' => ['state' => 'NM', 'cities' => ['Caballo']],
    '87933' => ['state' => 'NM', 'cities' => ['Derry']],
    '87935' => ['state' => 'NM', 'cities' => ['Elephant Butte']],
    '87936' => ['state' => 'NM', 'cities' => ['Garfield']],
    '87937' => ['state' => 'NM', 'cities' => ['Hatch']],
    '87939' => ['state' => 'NM', 'cities' => ['Monticello']],
    '87940' => ['state' => 'NM', 'cities' => ['Rincon']],
    '87941' => ['state' => 'NM', 'cities' => ['Salem']],
    '87942' => ['state' => 'NM', 'cities' => ['Williamsburg']],
    '87943' => ['state' => 'NM', 'cities' => ['Winston']],
];
