<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '88101' => ['state' => 'NM', 'cities' => ['Clovis']],
    '88102' => ['state' => 'NM', 'cities' => ['Clovis']],
    '88103' => ['state' => 'NM', 'cities' => ['Cannon Afb']],
    '88112' => ['state' => 'NM', 'cities' => ['Broadview']],
    '88113' => ['state' => 'NM', 'cities' => ['Causey']],
    '88114' => ['state' => 'NM', 'cities' => ['Crossroads']],
    '88115' => ['state' => 'NM', 'cities' => ['Dora']],
    '88116' => ['state' => 'NM', 'cities' => ['Elida']],
    '88118' => ['state' => 'NM', 'cities' => ['Floyd']],
    '88119' => ['state' => 'NM', 'cities' => ['Fort Sumner']],
    '88120' => ['state' => 'NM', 'cities' => ['Grady']],
    '88121' => ['state' => 'NM', 'cities' => ['House']],
    '88122' => ['state' => 'NM', 'cities' => ['Kenna']],
    '88123' => ['state' => 'NM', 'cities' => ['Lingo']],
    '88124' => ['state' => 'NM', 'cities' => ['Melrose']],
    '88125' => ['state' => 'NM', 'cities' => ['Milnesand']],
    '88126' => ['state' => 'NM', 'cities' => ['Pep']],
    '88130' => ['state' => 'NM', 'cities' => ['Portales']],
    '88132' => ['state' => 'NM', 'cities' => ['Rogers']],
    '88133' => ['state' => 'NM', 'cities' => ['Saint Vrain']],
    '88134' => ['state' => 'NM', 'cities' => ['Taiban']],
    '88135' => ['state' => 'NM', 'cities' => ['Texico']],
    '88136' => ['state' => 'NM', 'cities' => ['Yeso']],
];
