<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '88201' => ['state' => 'NM', 'cities' => ['Roswell']],
    '88202' => ['state' => 'NM', 'cities' => ['Roswell']],
    '88203' => ['state' => 'NM', 'cities' => ['Roswell']],
    '88210' => ['state' => 'NM', 'cities' => ['Artesia']],
    '88211' => ['state' => 'NM', 'cities' => ['Artesia']],
    '88213' => ['state' => 'NM', 'cities' => ['Caprock']],
    '88220' => ['state' => 'NM', 'cities' => ['Carlsbad']],
    '88221' => ['state' => 'NM', 'cities' => ['Carlsbad']],
    '88230' => ['state' => 'NM', 'cities' => ['Dexter']],
    '88231' => ['state' => 'NM', 'cities' => ['Eunice']],
    '88232' => ['state' => 'NM', 'cities' => ['Hagerman']],
    '88240' => ['state' => 'NM', 'cities' => ['Hobbs']],
    '88241' => ['state' => 'NM', 'cities' => ['Hobbs']],
    '88242' => ['state' => 'NM', 'cities' => ['Hobbs']],
    '88244' => ['state' => 'NM', 'cities' => ['Hobbs']],
    '88250' => ['state' => 'NM', 'cities' => ['Hope']],
    '88252' => ['state' => 'NM', 'cities' => ['Jal']],
    '88253' => ['state' => 'NM', 'cities' => ['Lake Arthur']],
    '88254' => ['state' => 'NM', 'cities' => ['Lakewood']],
    '88255' => ['state' => 'NM', 'cities' => ['Loco Hills']],
    '88256' => ['state' => 'NM', 'cities' => ['Loving']],
    '88260' => ['state' => 'NM', 'cities' => ['Lovington']],
    '88262' => ['state' => 'NM', 'cities' => ['Mcdonald']],
    '88263' => ['state' => 'NM', 'cities' => ['Malaga']],
    '88264' => ['state' => 'NM', 'cities' => ['Maljamar']],
    '88265' => ['state' => 'NM', 'cities' => ['Monument']],
    '88267' => ['state' => 'NM', 'cities' => ['Tatum']],
    '88268' => ['state' => 'NM', 'cities' => ['Whites City']],
];
