<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '88401' => ['state' => 'NM', 'cities' => ['Tucumcari']],
    '88410' => ['state' => 'NM', 'cities' => ['Amistad']],
    '88411' => ['state' => 'NM', 'cities' => ['Bard']],
    '88414' => ['state' => 'NM', 'cities' => ['Capulin']],
    '88415' => ['state' => 'NM', 'cities' => ['Clayton']],
    '88416' => ['state' => 'NM', 'cities' => ['Conchas Dam']],
    '88417' => ['state' => 'NM', 'cities' => ['Cuervo']],
    '88418' => ['state' => 'NM', 'cities' => ['Des Moines']],
    '88419' => ['state' => 'NM', 'cities' => ['Folsom']],
    '88421' => ['state' => 'NM', 'cities' => ['Garita']],
    '88422' => ['state' => 'NM', 'cities' => ['Gladstone']],
    '88424' => ['state' => 'NM', 'cities' => ['Grenville']],
    '88426' => ['state' => 'NM', 'cities' => ['Logan']],
    '88427' => ['state' => 'NM', 'cities' => ['Mcalister']],
    '88430' => ['state' => 'NM', 'cities' => ['Nara Visa']],
    '88431' => ['state' => 'NM', 'cities' => ['Newkirk']],
    '88433' => ['state' => 'NM', 'cities' => ['Quay']],
    '88434' => ['state' => 'NM', 'cities' => ['San Jon']],
    '88435' => ['state' => 'NM', 'cities' => ['Santa Rosa']],
    '88436' => ['state' => 'NM', 'cities' => ['Sedan']],
    '88439' => ['state' => 'NM', 'cities' => ['Trementina']],
];
