<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '89301' => ['state' => 'NV', 'cities' => ['Ely']],
    '89310' => ['state' => 'NV', 'cities' => ['Austin']],
    '89311' => ['state' => 'NV', 'cities' => ['Baker']],
    '89314' => ['state' => 'NV', 'cities' => ['Duckwater']],
    '89315' => ['state' => 'NV', 'cities' => ['Ely']],
    '89316' => ['state' => 'NV', 'cities' => ['Eureka']],
    '89317' => ['state' => 'NV', 'cities' => ['Lund']],
    '89318' => ['state' => 'NV', 'cities' => ['Mc Gill']],
    '89319' => ['state' => 'NV', 'cities' => ['Ruth']],
];
