<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '89501' => ['state' => 'NV', 'cities' => ['Reno']],
    '89502' => ['state' => 'NV', 'cities' => ['Reno']],
    '89503' => ['state' => 'NV', 'cities' => ['Reno']],
    '89504' => ['state' => 'NV', 'cities' => ['Reno']],
    '89505' => ['state' => 'NV', 'cities' => ['Reno']],
    '89506' => ['state' => 'NV', 'cities' => ['Reno']],
    '89507' => ['state' => 'NV', 'cities' => ['Reno']],
    '89508' => ['state' => 'NV', 'cities' => ['Reno']],
    '89509' => ['state' => 'NV', 'cities' => ['Reno']],
    '89510' => ['state' => 'NV', 'cities' => ['Reno']],
    '89511' => ['state' => 'NV', 'cities' => ['Reno']],
    '89512' => ['state' => 'NV', 'cities' => ['Reno']],
    '89513' => ['state' => 'NV', 'cities' => ['Reno']],
    '89515' => ['state' => 'NV', 'cities' => ['Reno']],
    '89519' => ['state' => 'NV', 'cities' => ['Reno']],
    '89520' => ['state' => 'NV', 'cities' => ['Reno']],
    '89521' => ['state' => 'NV', 'cities' => ['Reno']],
    '89523' => ['state' => 'NV', 'cities' => ['Reno']],
    '89533' => ['state' => 'NV', 'cities' => ['Reno']],
    '89555' => ['state' => 'NV', 'cities' => ['Reno']],
    '89557' => ['state' => 'NV', 'cities' => ['Reno']],
    '89570' => ['state' => 'NV', 'cities' => ['Reno']],
    '89595' => ['state' => 'NV', 'cities' => ['Reno']],
    '89599' => ['state' => 'NV', 'cities' => ['Reno']],
];
