<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '89801' => ['state' => 'NV', 'cities' => ['Elko']],
    '89802' => ['state' => 'NV', 'cities' => ['Elko']],
    '89803' => ['state' => 'NV', 'cities' => ['Elko']],
    '89815' => ['state' => 'NV', 'cities' => ['Spring Creek']],
    '89820' => ['state' => 'NV', 'cities' => ['Battle Mountain']],
    '89821' => ['state' => 'NV', 'cities' => ['Crescent Valley']],
    '89822' => ['state' => 'NV', 'cities' => ['Carlin']],
    '89823' => ['state' => 'NV', 'cities' => ['Deeth']],
    '89825' => ['state' => 'NV', 'cities' => ['Jackpot']],
    '89826' => ['state' => 'NV', 'cities' => ['Jarbidge']],
    '89828' => ['state' => 'NV', 'cities' => ['Lamoille']],
    '89830' => ['state' => 'NV', 'cities' => ['Montello']],
    '89831' => ['state' => 'NV', 'cities' => ['Mountain City']],
    '89832' => ['state' => 'NV', 'cities' => ['Owyhee']],
    '89833' => ['state' => 'NV', 'cities' => ['Ruby Valley']],
    '89834' => ['state' => 'NV', 'cities' => ['Tuscarora']],
    '89835' => ['state' => 'NV', 'cities' => ['Wells']],
    '89883' => ['state' => 'NV', 'cities' => ['West Wendover']],
];
