<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '90301' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90302' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90303' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90304' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90305' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90306' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90307' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90308' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90309' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90310' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90311' => ['state' => 'CA', 'cities' => ['Inglewood']],
    '90312' => ['state' => 'CA', 'cities' => ['Inglewood']],
];
