<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '90401' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90402' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90403' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90404' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90405' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90406' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90407' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90408' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90409' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90410' => ['state' => 'CA', 'cities' => ['Santa Monica']],
    '90411' => ['state' => 'CA', 'cities' => ['Santa Monica']],
];
