<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '90501' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90502' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90503' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90504' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90505' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90506' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90507' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90508' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90509' => ['state' => 'CA', 'cities' => ['Torrance']],
    '90510' => ['state' => 'CA', 'cities' => ['Torrance']],
];
