<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '90801' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90802' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90803' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90804' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90805' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90806' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90807' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90808' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90809' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90810' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90813' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90814' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90815' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90822' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90831' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90832' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90833' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90834' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90835' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90840' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90842' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90844' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90846' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90847' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90848' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90853' => ['state' => 'CA', 'cities' => ['Long Beach']],
    '90895' => ['state' => 'CA', 'cities' => ['Carson']],
    '90899' => ['state' => 'CA', 'cities' => ['Long Beach']],
];
