<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91001' => ['state' => 'CA', 'cities' => ['Altadena']],
    '91003' => ['state' => 'CA', 'cities' => ['Altadena']],
    '91006' => ['state' => 'CA', 'cities' => ['Arcadia']],
    '91007' => ['state' => 'CA', 'cities' => ['Arcadia']],
    '91008' => ['state' => 'CA', 'cities' => ['Duarte']],
    '91009' => ['state' => 'CA', 'cities' => ['Duarte']],
    '91010' => ['state' => 'CA', 'cities' => ['Duarte']],
    '91011' => ['state' => 'CA', 'cities' => ['La Canada Flintridge']],
    '91012' => ['state' => 'CA', 'cities' => ['La Canada Flintridge']],
    '91016' => ['state' => 'CA', 'cities' => ['Monrovia']],
    '91017' => ['state' => 'CA', 'cities' => ['Monrovia']],
    '91020' => ['state' => 'CA', 'cities' => ['Montrose']],
    '91021' => ['state' => 'CA', 'cities' => ['Montrose']],
    '91023' => ['state' => 'CA', 'cities' => ['Mount Wilson']],
    '91024' => ['state' => 'CA', 'cities' => ['Sierra Madre']],
    '91025' => ['state' => 'CA', 'cities' => ['Sierra Madre']],
    '91030' => ['state' => 'CA', 'cities' => ['South Pasadena']],
    '91031' => ['state' => 'CA', 'cities' => ['South Pasadena']],
    '91040' => ['state' => 'CA', 'cities' => ['Sunland']],
    '91041' => ['state' => 'CA', 'cities' => ['Sunland']],
    '91042' => ['state' => 'CA', 'cities' => ['Tujunga']],
    '91043' => ['state' => 'CA', 'cities' => ['Tujunga']],
    '91046' => ['state' => 'CA', 'cities' => ['Verdugo City']],
    '91066' => ['state' => 'CA', 'cities' => ['Arcadia']],
    '91077' => ['state' => 'CA', 'cities' => ['Arcadia']],
];
