<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91101' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91102' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91103' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91104' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91105' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91106' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91107' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91108' => ['state' => 'CA', 'cities' => ['San Marino']],
    '91109' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91110' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91114' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91115' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91116' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91117' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91118' => ['state' => 'CA', 'cities' => ['San Marino']],
    '91121' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91123' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91124' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91125' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91126' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91129' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91182' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91184' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91185' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91188' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91189' => ['state' => 'CA', 'cities' => ['Pasadena']],
    '91199' => ['state' => 'CA', 'cities' => ['Pasadena']],
];
