<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91201' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91202' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91203' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91204' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91205' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91206' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91207' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91208' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91209' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91210' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91214' => ['state' => 'CA', 'cities' => ['La Crescenta']],
    '91221' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91222' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91224' => ['state' => 'CA', 'cities' => ['La Crescenta']],
    '91225' => ['state' => 'CA', 'cities' => ['Glendale']],
    '91226' => ['state' => 'CA', 'cities' => ['Glendale']],
];
