<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91401' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91402' => ['state' => 'CA', 'cities' => ['Panorama City']],
    '91403' => ['state' => 'CA', 'cities' => ['Sherman Oaks']],
    '91404' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91405' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91406' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91407' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91408' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91409' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91410' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91411' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91412' => ['state' => 'CA', 'cities' => ['Panorama City']],
    '91413' => ['state' => 'CA', 'cities' => ['Sherman Oaks']],
    '91416' => ['state' => 'CA', 'cities' => ['Encino']],
    '91423' => ['state' => 'CA', 'cities' => ['Sherman Oaks']],
    '91426' => ['state' => 'CA', 'cities' => ['Encino']],
    '91436' => ['state' => 'CA', 'cities' => ['Encino']],
    '91470' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91482' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91495' => ['state' => 'CA', 'cities' => ['Sherman Oaks']],
    '91496' => ['state' => 'CA', 'cities' => ['Van Nuys']],
    '91499' => ['state' => 'CA', 'cities' => ['Van Nuys']],
];
