<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91501' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91502' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91503' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91504' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91505' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91506' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91507' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91508' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91510' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91521' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91522' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91523' => ['state' => 'CA', 'cities' => ['Burbank']],
    '91526' => ['state' => 'CA', 'cities' => ['Burbank']],
];
