<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91601' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91602' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91603' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91604' => ['state' => 'CA', 'cities' => ['Studio City']],
    '91605' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91606' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91607' => ['state' => 'CA', 'cities' => ['Valley Village']],
    '91608' => ['state' => 'CA', 'cities' => ['Universal City']],
    '91609' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91610' => ['state' => 'CA', 'cities' => ['Toluca Lake']],
    '91611' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91612' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91614' => ['state' => 'CA', 'cities' => ['Studio City']],
    '91615' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91616' => ['state' => 'CA', 'cities' => ['North Hollywood']],
    '91617' => ['state' => 'CA', 'cities' => ['Valley Village']],
    '91618' => ['state' => 'CA', 'cities' => ['North Hollywood']],
];
