<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '91801' => ['state' => 'CA', 'cities' => ['Alhambra']],
    '91802' => ['state' => 'CA', 'cities' => ['Alhambra']],
    '91803' => ['state' => 'CA', 'cities' => ['Alhambra']],
    '91804' => ['state' => 'CA', 'cities' => ['Alhambra']],
    '91896' => ['state' => 'CA', 'cities' => ['Alhambra']],
    '91899' => ['state' => 'CA', 'cities' => ['Alhambra']],
];
