<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '92701' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92702' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92703' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92704' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92705' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92706' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92707' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92708' => ['state' => 'CA', 'cities' => ['Fountain Valley']],
    '92711' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92712' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92728' => ['state' => 'CA', 'cities' => ['Fountain Valley']],
    '92735' => ['state' => 'CA', 'cities' => ['Santa Ana']],
    '92780' => ['state' => 'CA', 'cities' => ['Tustin']],
    '92781' => ['state' => 'CA', 'cities' => ['Tustin']],
    '92782' => ['state' => 'CA', 'cities' => ['Tustin']],
    '92799' => ['state' => 'CA', 'cities' => ['Santa Ana']],
];
