<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '93101' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93102' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93103' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93105' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93106' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93107' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93108' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93109' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93110' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93111' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93116' => ['state' => 'CA', 'cities' => ['Goleta']],
    '93117' => ['state' => 'CA', 'cities' => ['Goleta']],
    '93118' => ['state' => 'CA', 'cities' => ['Goleta']],
    '93120' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93121' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93130' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93140' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93150' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93160' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93190' => ['state' => 'CA', 'cities' => ['Santa Barbara']],
    '93199' => ['state' => 'CA', 'cities' => ['Goleta']],
];
