<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '93301' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93302' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93303' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93304' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93305' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93306' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93307' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93308' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93309' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93311' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93312' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93313' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93314' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93380' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93383' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93384' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93385' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93386' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93387' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93388' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93389' => ['state' => 'CA', 'cities' => ['Bakersfield']],
    '93390' => ['state' => 'CA', 'cities' => ['Bakersfield']],
];
