<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '93844' => ['state' => 'CA', 'cities' => ['Fresno']],
    '93888' => ['state' => 'CA', 'cities' => ['Fresno']],
];
