<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '94301' => ['state' => 'CA', 'cities' => ['Palo Alto']],
    '94302' => ['state' => 'CA', 'cities' => ['Palo Alto']],
    '94303' => ['state' => 'CA', 'cities' => ['Palo Alto']],
    '94304' => ['state' => 'CA', 'cities' => ['Palo Alto']],
    '94305' => ['state' => 'CA', 'cities' => ['Stanford']],
    '94306' => ['state' => 'CA', 'cities' => ['Palo Alto']],
    '94309' => ['state' => 'CA', 'cities' => ['Palo Alto']],
];
