<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '94401' => ['state' => 'CA', 'cities' => ['San Mateo']],
    '94402' => ['state' => 'CA', 'cities' => ['San Mateo']],
    '94403' => ['state' => 'CA', 'cities' => ['San Mateo']],
    '94404' => ['state' => 'CA', 'cities' => ['San Mateo']],
    '94497' => ['state' => 'CA', 'cities' => ['San Mateo']],
];
