<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '94701' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94702' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94703' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94704' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94705' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94706' => ['state' => 'CA', 'cities' => ['Albany']],
    '94707' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94708' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94709' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94710' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94712' => ['state' => 'CA', 'cities' => ['Berkeley']],
    '94720' => ['state' => 'CA', 'cities' => ['Berkeley']],
];
