<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '94801' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94802' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94803' => ['state' => 'CA', 'cities' => ['El Sobrante']],
    '94804' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94805' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94806' => ['state' => 'CA', 'cities' => ['San Pablo']],
    '94807' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94808' => ['state' => 'CA', 'cities' => ['Richmond']],
    '94820' => ['state' => 'CA', 'cities' => ['El Sobrante']],
    '94850' => ['state' => 'CA', 'cities' => ['Richmond']],
];
