<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '96910' => ['state' => 'GU', 'cities' => ['Hagatna']],
    '96911' => ['state' => 'GU', 'cities' => ['Tamuning']],
    '96912' => ['state' => 'GU', 'cities' => ['Dededo']],
    '96913' => ['state' => 'GU', 'cities' => ['Barrigada']],
    '96914' => ['state' => 'GU', 'cities' => ['Yona']],
    '96915' => ['state' => 'GU', 'cities' => ['Santa Rita']],
    '96916' => ['state' => 'GU', 'cities' => ['Merizo']],
    '96917' => ['state' => 'GU', 'cities' => ['Inarajan']],
    '96918' => ['state' => 'GU', 'cities' => ['Umatac']],
    '96919' => ['state' => 'GU', 'cities' => ['Agana Heights']],
    '96921' => ['state' => 'GU', 'cities' => ['Barrigada']],
    '96922' => ['state' => 'GU', 'cities' => ['Asan']],
    '96923' => ['state' => 'GU', 'cities' => ['Mangilao']],
    '96925' => ['state' => 'GU', 'cities' => ['Piti']],
    '96926' => ['state' => 'GU', 'cities' => ['Sinajana']],
    '96927' => ['state' => 'GU', 'cities' => ['Mongmong']],
    '96928' => ['state' => 'GU', 'cities' => ['Agat']],
    '96929' => ['state' => 'GU', 'cities' => ['Yigo']],
    '96930' => ['state' => 'GU', 'cities' => ['Talofofo']],
    '96931' => ['state' => 'GU', 'cities' => ['Tamuning']],
    '96932' => ['state' => 'GU', 'cities' => ['Hagatna']],
    '96950' => ['state' => 'MP', 'cities' => ['Saipan']],
    '96951' => ['state' => 'MP', 'cities' => ['Rota']],
    '96952' => ['state' => 'MP', 'cities' => ['Tinian']],
];
