<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '97501' => ['state' => 'OR', 'cities' => ['Medford']],
    '97502' => ['state' => 'OR', 'cities' => ['Central Point']],
    '97503' => ['state' => 'OR', 'cities' => ['White City']],
    '97504' => ['state' => 'OR', 'cities' => ['Medford']],
    '97520' => ['state' => 'OR', 'cities' => ['Ashland']],
    '97522' => ['state' => 'OR', 'cities' => ['Butte Falls']],
    '97523' => ['state' => 'OR', 'cities' => ['Cave Junction']],
    '97524' => ['state' => 'OR', 'cities' => ['Eagle Point']],
    '97525' => ['state' => 'OR', 'cities' => ['Gold Hill']],
    '97526' => ['state' => 'OR', 'cities' => ['Grants Pass']],
    '97527' => ['state' => 'OR', 'cities' => ['Grants Pass']],
    '97528' => ['state' => 'OR', 'cities' => ['Grants Pass']],
    '97530' => ['state' => 'OR', 'cities' => ['Jacksonville']],
    '97531' => ['state' => 'OR', 'cities' => ['Kerby']],
    '97532' => ['state' => 'OR', 'cities' => ['Merlin']],
    '97533' => ['state' => 'OR', 'cities' => ['Murphy']],
    '97534' => ['state' => 'OR', 'cities' => ['O Brien']],
    '97535' => ['state' => 'OR', 'cities' => ['Phoenix']],
    '97536' => ['state' => 'OR', 'cities' => ['Prospect']],
    '97537' => ['state' => 'OR', 'cities' => ['Rogue River']],
    '97538' => ['state' => 'OR', 'cities' => ['Selma']],
    '97539' => ['state' => 'OR', 'cities' => ['Shady Cove']],
    '97540' => ['state' => 'OR', 'cities' => ['Talent']],
    '97541' => ['state' => 'OR', 'cities' => ['Trail']],
    '97543' => ['state' => 'OR', 'cities' => ['Wilderville']],
    '97544' => ['state' => 'OR', 'cities' => ['Williams']],
];
