<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '97601' => ['state' => 'OR', 'cities' => ['Klamath Falls']],
    '97602' => ['state' => 'OR', 'cities' => ['Klamath Falls']],
    '97603' => ['state' => 'OR', 'cities' => ['Klamath Falls']],
    '97604' => ['state' => 'OR', 'cities' => ['Crater Lake']],
    '97620' => ['state' => 'OR', 'cities' => ['Adel']],
    '97621' => ['state' => 'OR', 'cities' => ['Beatty']],
    '97622' => ['state' => 'OR', 'cities' => ['Bly']],
    '97623' => ['state' => 'OR', 'cities' => ['Bonanza']],
    '97624' => ['state' => 'OR', 'cities' => ['Chiloquin']],
    '97625' => ['state' => 'OR', 'cities' => ['Dairy']],
    '97626' => ['state' => 'OR', 'cities' => ['Fort Klamath']],
    '97627' => ['state' => 'OR', 'cities' => ['Keno']],
    '97630' => ['state' => 'OR', 'cities' => ['Lakeview']],
    '97632' => ['state' => 'OR', 'cities' => ['Malin']],
    '97633' => ['state' => 'OR', 'cities' => ['Merrill']],
    '97634' => ['state' => 'OR', 'cities' => ['Midland']],
    '97635' => ['state' => 'OR', 'cities' => ['New Pine Creek']],
    '97636' => ['state' => 'OR', 'cities' => ['Paisley']],
    '97637' => ['state' => 'OR', 'cities' => ['Plush']],
    '97638' => ['state' => 'OR', 'cities' => ['Silver Lake']],
    '97639' => ['state' => 'OR', 'cities' => ['Sprague River']],
    '97640' => ['state' => 'OR', 'cities' => ['Summer Lake']],
    '97641' => ['state' => 'OR', 'cities' => ['Christmas Valley']],
];
