<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '97901' => ['state' => 'OR', 'cities' => ['Adrian']],
    '97902' => ['state' => 'OR', 'cities' => ['Arock']],
    '97903' => ['state' => 'OR', 'cities' => ['Brogan']],
    '97904' => ['state' => 'OR', 'cities' => ['Drewsey']],
    '97905' => ['state' => 'OR', 'cities' => ['Durkee']],
    '97906' => ['state' => 'OR', 'cities' => ['Harper']],
    '97907' => ['state' => 'OR', 'cities' => ['Huntington']],
    '97908' => ['state' => 'OR', 'cities' => ['Ironside']],
    '97909' => ['state' => 'OR', 'cities' => ['Jamieson']],
    '97910' => ['state' => 'OR', 'cities' => ['Jordan Valley']],
    '97911' => ['state' => 'OR', 'cities' => ['Juntura']],
    '97913' => ['state' => 'OR', 'cities' => ['Nyssa']],
    '97914' => ['state' => 'OR', 'cities' => ['Ontario']],
    '97917' => ['state' => 'OR', 'cities' => ['Riverside']],
    '97918' => ['state' => 'OR', 'cities' => ['Vale']],
    '97920' => ['state' => 'OR', 'cities' => ['Westfall']],
];
