<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '99201' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99202' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99203' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99204' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99205' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99206' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99207' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99208' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99209' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99210' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99211' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99212' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99213' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99214' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99215' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99216' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99217' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99218' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99219' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99220' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99223' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99224' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99228' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99251' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99252' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99256' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99258' => ['state' => 'WA', 'cities' => ['Spokane']],
    '99260' => ['state' => 'WA', 'cities' => ['Spokane']],
];
