<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '99401' => ['state' => 'WA', 'cities' => ['Anatone']],
    '99402' => ['state' => 'WA', 'cities' => ['Asotin']],
    '99403' => ['state' => 'WA', 'cities' => ['Clarkston']],
];
