<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '99801' => ['state' => 'AK', 'cities' => ['Juneau']],
    '99802' => ['state' => 'AK', 'cities' => ['Juneau']],
    '99803' => ['state' => 'AK', 'cities' => ['Juneau']],
    '99811' => ['state' => 'AK', 'cities' => ['Juneau']],
    '99812' => ['state' => 'AK', 'cities' => ['Juneau']],
    '99820' => ['state' => 'AK', 'cities' => ['Angoon']],
    '99821' => ['state' => 'AK', 'cities' => ['Auke Bay']],
    '99824' => ['state' => 'AK', 'cities' => ['Douglas']],
    '99825' => ['state' => 'AK', 'cities' => ['Elfin Cove']],
    '99826' => ['state' => 'AK', 'cities' => ['Gustavus']],
    '99827' => ['state' => 'AK', 'cities' => ['Haines']],
    '99829' => ['state' => 'AK', 'cities' => ['Hoonah']],
    '99830' => ['state' => 'AK', 'cities' => ['Kake']],
    '99832' => ['state' => 'AK', 'cities' => ['Pelican']],
    '99833' => ['state' => 'AK', 'cities' => ['Petersburg']],
    '99835' => ['state' => 'AK', 'cities' => ['Sitka']],
    '99836' => ['state' => 'AK', 'cities' => ['Port Alexander']],
    '99840' => ['state' => 'AK', 'cities' => ['Skagway']],
    '99841' => ['state' => 'AK', 'cities' => ['Tenakee Springs']],
    '99850' => ['state' => 'AK', 'cities' => ['Juneau']],
];
