<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: ../NOTICE.md

return [
    '99901' => ['state' => 'AK', 'cities' => ['Ketchikan']],
    '99903' => ['state' => 'AK', 'cities' => ['Meyers Chuck']],
    '99918' => ['state' => 'AK', 'cities' => ['Coffman Cove']],
    '99919' => ['state' => 'AK', 'cities' => ['Thorne Bay']],
    '99921' => ['state' => 'AK', 'cities' => ['Craig']],
    '99922' => ['state' => 'AK', 'cities' => ['Hydaburg']],
    '99923' => ['state' => 'AK', 'cities' => ['Hyder']],
    '99925' => ['state' => 'AK', 'cities' => ['Klawock']],
    '99926' => ['state' => 'AK', 'cities' => ['Metlakatla']],
    '99927' => ['state' => 'AK', 'cities' => ['Point Baker']],
    '99928' => ['state' => 'AK', 'cities' => ['Ward Cove']],
    '99929' => ['state' => 'AK', 'cities' => ['Wrangell']],
    '99950' => ['state' => 'AK', 'cities' => ['Ketchikan']],
];
