<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '00801' => ['state' => 'VI', 'city' => 'St Thomas'],
    '00802' => ['state' => 'VI', 'city' => 'St Thomas'],
    '00803' => ['state' => 'VI', 'city' => 'St Thomas'],
    '00804' => ['state' => 'VI', 'city' => 'St Thomas'],
    '00805' => ['state' => 'VI', 'city' => 'St Thomas'],
    '00820' => ['state' => 'VI', 'city' => 'Christiansted'],
    '00821' => ['state' => 'VI', 'city' => 'Christiansted'],
    '00822' => ['state' => 'VI', 'city' => 'Christiansted'],
    '00823' => ['state' => 'VI', 'city' => 'Christiansted'],
    '00824' => ['state' => 'VI', 'city' => 'Christiansted'],
    '00830' => ['state' => 'VI', 'city' => 'St John'],
    '00831' => ['state' => 'VI', 'city' => 'St John'],
    '00840' => ['state' => 'VI', 'city' => 'Frederiksted'],
    '00841' => ['state' => 'VI', 'city' => 'Frederiksted'],
    '00850' => ['state' => 'VI', 'city' => 'Kingshill'],
    '00851' => ['state' => 'VI', 'city' => 'Kingshill'],
];
