<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '01420' => ['state' => 'MA', 'city' => 'Fitchburg'],
    '01430' => ['state' => 'MA', 'city' => 'Ashburnham'],
    '01431' => ['state' => 'MA', 'city' => 'Ashby'],
    '01432' => ['state' => 'MA', 'city' => 'Ayer'],
    '01434' => ['state' => 'MA', 'city' => 'Devens'],
    '01436' => ['state' => 'MA', 'city' => 'Baldwinville'],
    '01438' => ['state' => 'MA', 'city' => 'East Templeton'],
    '01440' => ['state' => 'MA', 'city' => 'Gardner'],
    '01441' => ['state' => 'MA', 'city' => 'Westminster'],
    '01450' => ['state' => 'MA', 'city' => 'Groton'],
    '01451' => ['state' => 'MA', 'city' => 'Harvard'],
    '01452' => ['state' => 'MA', 'city' => 'Hubbardston'],
    '01453' => ['state' => 'MA', 'city' => 'Leominster'],
    '01460' => ['state' => 'MA', 'city' => 'Littleton'],
    '01462' => ['state' => 'MA', 'city' => 'Lunenburg'],
    '01463' => ['state' => 'MA', 'city' => 'Pepperell'],
    '01464' => ['state' => 'MA', 'city' => 'Shirley'],
    '01467' => ['state' => 'MA', 'city' => 'Still River'],
    '01468' => ['state' => 'MA', 'city' => 'Templeton'],
    '01469' => ['state' => 'MA', 'city' => 'Townsend'],
    '01470' => ['state' => 'MA', 'city' => 'Groton'],
    '01471' => ['state' => 'MA', 'city' => 'Groton'],
    '01472' => ['state' => 'MA', 'city' => 'West Groton'],
    '01473' => ['state' => 'MA', 'city' => 'Westminster'],
    '01474' => ['state' => 'MA', 'city' => 'West Townsend'],
    '01475' => ['state' => 'MA', 'city' => 'Winchendon'],
];
