<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '01601' => ['state' => 'MA', 'city' => 'Worcester'],
    '01602' => ['state' => 'MA', 'city' => 'Worcester'],
    '01603' => ['state' => 'MA', 'city' => 'Worcester'],
    '01604' => ['state' => 'MA', 'city' => 'Worcester'],
    '01605' => ['state' => 'MA', 'city' => 'Worcester'],
    '01606' => ['state' => 'MA', 'city' => 'Worcester'],
    '01607' => ['state' => 'MA', 'city' => 'Worcester'],
    '01608' => ['state' => 'MA', 'city' => 'Worcester'],
    '01609' => ['state' => 'MA', 'city' => 'Worcester'],
    '01610' => ['state' => 'MA', 'city' => 'Worcester'],
    '01611' => ['state' => 'MA', 'city' => 'Cherry Valley'],
    '01612' => ['state' => 'MA', 'city' => 'Paxton'],
    '01613' => ['state' => 'MA', 'city' => 'Worcester'],
    '01614' => ['state' => 'MA', 'city' => 'Worcester'],
    '01615' => ['state' => 'MA', 'city' => 'Worcester'],
    '01653' => ['state' => 'MA', 'city' => 'Worcester'],
    '01655' => ['state' => 'MA', 'city' => 'Worcester'],
];
