<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '02532' => ['state' => 'MA', 'city' => 'Buzzards Bay'],
    '02534' => ['state' => 'MA', 'city' => 'Cataumet'],
    '02535' => ['state' => 'MA', 'city' => 'Chilmark'],
    '02536' => ['state' => 'MA', 'city' => 'East Falmouth'],
    '02537' => ['state' => 'MA', 'city' => 'East Sandwich'],
    '02538' => ['state' => 'MA', 'city' => 'East Wareham'],
    '02539' => ['state' => 'MA', 'city' => 'Edgartown'],
    '02540' => ['state' => 'MA', 'city' => 'Falmouth'],
    '02541' => ['state' => 'MA', 'city' => 'Falmouth'],
    '02542' => ['state' => 'MA', 'city' => 'Buzzards Bay'],
    '02543' => ['state' => 'MA', 'city' => 'Woods Hole'],
    '02552' => ['state' => 'MA', 'city' => 'Menemsha'],
    '02553' => ['state' => 'MA', 'city' => 'Monument Beach'],
    '02554' => ['state' => 'MA', 'city' => 'Nantucket'],
    '02556' => ['state' => 'MA', 'city' => 'North Falmouth'],
    '02557' => ['state' => 'MA', 'city' => 'Oak Bluffs'],
    '02558' => ['state' => 'MA', 'city' => 'Onset'],
    '02559' => ['state' => 'MA', 'city' => 'Pocasset'],
    '02561' => ['state' => 'MA', 'city' => 'Sagamore'],
    '02562' => ['state' => 'MA', 'city' => 'Sagamore Beach'],
    '02563' => ['state' => 'MA', 'city' => 'Sandwich'],
    '02564' => ['state' => 'MA', 'city' => 'Siasconset'],
    '02568' => ['state' => 'MA', 'city' => 'Vineyard Haven'],
    '02571' => ['state' => 'MA', 'city' => 'Wareham'],
    '02574' => ['state' => 'MA', 'city' => 'West Falmouth'],
    '02575' => ['state' => 'MA', 'city' => 'West Tisbury'],
    '02576' => ['state' => 'MA', 'city' => 'West Wareham'],
    '02584' => ['state' => 'MA', 'city' => 'Nantucket'],
];
