<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '02901' => ['state' => 'RI', 'city' => 'Providence'],
    '02902' => ['state' => 'RI', 'city' => 'Providence'],
    '02903' => ['state' => 'RI', 'city' => 'Providence'],
    '02904' => ['state' => 'RI', 'city' => 'Providence'],
    '02905' => ['state' => 'RI', 'city' => 'Providence'],
    '02906' => ['state' => 'RI', 'city' => 'Providence'],
    '02907' => ['state' => 'RI', 'city' => 'Providence'],
    '02908' => ['state' => 'RI', 'city' => 'Providence'],
    '02909' => ['state' => 'RI', 'city' => 'Providence'],
    '02910' => ['state' => 'RI', 'city' => 'Cranston'],
    '02911' => ['state' => 'RI', 'city' => 'North Providence'],
    '02912' => ['state' => 'RI', 'city' => 'Providence'],
    '02914' => ['state' => 'RI', 'city' => 'East Providence'],
    '02915' => ['state' => 'RI', 'city' => 'Riverside'],
    '02916' => ['state' => 'RI', 'city' => 'Rumford'],
    '02917' => ['state' => 'RI', 'city' => 'Smithfield'],
    '02918' => ['state' => 'RI', 'city' => 'Providence'],
    '02919' => ['state' => 'RI', 'city' => 'Johnston'],
    '02920' => ['state' => 'RI', 'city' => 'Cranston'],
    '02921' => ['state' => 'RI', 'city' => 'Cranston'],
    '02940' => ['state' => 'RI', 'city' => 'Providence'],
];
