<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03101' => ['state' => 'NH', 'city' => 'Manchester'],
    '03102' => ['state' => 'NH', 'city' => 'Manchester'],
    '03103' => ['state' => 'NH', 'city' => 'Manchester'],
    '03104' => ['state' => 'NH', 'city' => 'Manchester'],
    '03105' => ['state' => 'NH', 'city' => 'Manchester'],
    '03106' => ['state' => 'NH', 'city' => 'Hooksett'],
    '03108' => ['state' => 'NH', 'city' => 'Manchester'],
    '03109' => ['state' => 'NH', 'city' => 'Manchester'],
    '03110' => ['state' => 'NH', 'city' => 'Bedford'],
    '03111' => ['state' => 'NH', 'city' => 'Manchester'],
];
