<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03301' => ['state' => 'NH', 'city' => 'Concord'],
    '03302' => ['state' => 'NH', 'city' => 'Concord'],
    '03303' => ['state' => 'NH', 'city' => 'Concord'],
    '03304' => ['state' => 'NH', 'city' => 'Bow'],
    '03305' => ['state' => 'NH', 'city' => 'Concord'],
    '03307' => ['state' => 'NH', 'city' => 'Loudon'],
];
