<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03431' => ['state' => 'NH', 'city' => 'Keene'],
    '03435' => ['state' => 'NH', 'city' => 'Keene'],
    '03440' => ['state' => 'NH', 'city' => 'Antrim'],
    '03441' => ['state' => 'NH', 'city' => 'Ashuelot'],
    '03442' => ['state' => 'NH', 'city' => 'Bennington'],
    '03443' => ['state' => 'NH', 'city' => 'Chesterfield'],
    '03444' => ['state' => 'NH', 'city' => 'Dublin'],
    '03445' => ['state' => 'NH', 'city' => 'Sullivan'],
    '03446' => ['state' => 'NH', 'city' => 'Swanzey'],
    '03447' => ['state' => 'NH', 'city' => 'Fitzwilliam'],
    '03448' => ['state' => 'NH', 'city' => 'Gilsum'],
    '03449' => ['state' => 'NH', 'city' => 'Hancock'],
    '03450' => ['state' => 'NH', 'city' => 'Harrisville'],
    '03451' => ['state' => 'NH', 'city' => 'Hinsdale'],
    '03452' => ['state' => 'NH', 'city' => 'Jaffrey'],
    '03455' => ['state' => 'NH', 'city' => 'Marlborough'],
    '03456' => ['state' => 'NH', 'city' => 'Marlow'],
    '03457' => ['state' => 'NH', 'city' => 'Nelson'],
    '03458' => ['state' => 'NH', 'city' => 'Peterborough'],
    '03461' => ['state' => 'NH', 'city' => 'Rindge'],
    '03462' => ['state' => 'NH', 'city' => 'Spofford'],
    '03464' => ['state' => 'NH', 'city' => 'Stoddard'],
    '03465' => ['state' => 'NH', 'city' => 'Troy'],
    '03466' => ['state' => 'NH', 'city' => 'West Chesterfield'],
    '03467' => ['state' => 'NH', 'city' => 'Westmoreland'],
    '03468' => ['state' => 'NH', 'city' => 'West Peterborough'],
    '03469' => ['state' => 'NH', 'city' => 'West Swanzey'],
    '03470' => ['state' => 'NH', 'city' => 'Winchester'],
];
