<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03561' => ['state' => 'NH', 'city' => 'Littleton'],
    '03570' => ['state' => 'NH', 'city' => 'Berlin'],
    '03574' => ['state' => 'NH', 'city' => 'Bethlehem'],
    '03575' => ['state' => 'NH', 'city' => 'Bretton Woods'],
    '03576' => ['state' => 'NH', 'city' => 'Colebrook'],
    '03579' => ['state' => 'NH', 'city' => 'Errol'],
    '03580' => ['state' => 'NH', 'city' => 'Franconia'],
    '03581' => ['state' => 'NH', 'city' => 'Gorham'],
    '03582' => ['state' => 'NH', 'city' => 'Groveton'],
    '03583' => ['state' => 'NH', 'city' => 'Jefferson'],
    '03584' => ['state' => 'NH', 'city' => 'Lancaster'],
    '03585' => ['state' => 'NH', 'city' => 'Lisbon'],
    '03586' => ['state' => 'NH', 'city' => 'Sugar Hill'],
    '03588' => ['state' => 'NH', 'city' => 'Milan'],
    '03589' => ['state' => 'NH', 'city' => 'Mount Washington'],
    '03590' => ['state' => 'NH', 'city' => 'North Stratford'],
    '03592' => ['state' => 'NH', 'city' => 'Pittsburg'],
    '03593' => ['state' => 'NH', 'city' => 'Randolph'],
    '03595' => ['state' => 'NH', 'city' => 'Twin Mountain'],
    '03597' => ['state' => 'NH', 'city' => 'West Stewartstown'],
    '03598' => ['state' => 'NH', 'city' => 'Whitefield'],
];
