<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03601' => ['state' => 'NH', 'city' => 'Acworth'],
    '03602' => ['state' => 'NH', 'city' => 'Alstead'],
    '03603' => ['state' => 'NH', 'city' => 'Charlestown'],
    '03604' => ['state' => 'NH', 'city' => 'Drewsville'],
    '03605' => ['state' => 'NH', 'city' => 'Lempster'],
    '03607' => ['state' => 'NH', 'city' => 'South Acworth'],
    '03608' => ['state' => 'NH', 'city' => 'Walpole'],
    '03609' => ['state' => 'NH', 'city' => 'North Walpole'],
];
