<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '03901' => ['state' => 'ME', 'city' => 'Berwick'],
    '03902' => ['state' => 'ME', 'city' => 'Cape Neddick'],
    '03903' => ['state' => 'ME', 'city' => 'Eliot'],
    '03904' => ['state' => 'ME', 'city' => 'Kittery'],
    '03905' => ['state' => 'ME', 'city' => 'Kittery Point'],
    '03906' => ['state' => 'ME', 'city' => 'North Berwick'],
    '03907' => ['state' => 'ME', 'city' => 'Ogunquit'],
    '03908' => ['state' => 'ME', 'city' => 'South Berwick'],
    '03909' => ['state' => 'ME', 'city' => 'York'],
    '03910' => ['state' => 'ME', 'city' => 'York Beach'],
    '03911' => ['state' => 'ME', 'city' => 'York Harbor'],
];
