<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '04101' => ['state' => 'ME', 'city' => 'Portland'],
    '04102' => ['state' => 'ME', 'city' => 'Portland'],
    '04103' => ['state' => 'ME', 'city' => 'Portland'],
    '04104' => ['state' => 'ME', 'city' => 'Portland'],
    '04105' => ['state' => 'ME', 'city' => 'Falmouth'],
    '04106' => ['state' => 'ME', 'city' => 'South Portland'],
    '04107' => ['state' => 'ME', 'city' => 'Cape Elizabeth'],
    '04108' => ['state' => 'ME', 'city' => 'Peaks Island'],
    '04109' => ['state' => 'ME', 'city' => 'Portland'],
    '04110' => ['state' => 'ME', 'city' => 'Cumberland Foreside'],
    '04112' => ['state' => 'ME', 'city' => 'Portland'],
    '04116' => ['state' => 'ME', 'city' => 'South Portland'],
    '04122' => ['state' => 'ME', 'city' => 'Portland'],
    '04123' => ['state' => 'ME', 'city' => 'Portland'],
    '04124' => ['state' => 'ME', 'city' => 'Portland'],
];
