<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '04330' => ['state' => 'ME', 'city' => 'Augusta'],
    '04332' => ['state' => 'ME', 'city' => 'Augusta'],
    '04333' => ['state' => 'ME', 'city' => 'Augusta'],
    '04336' => ['state' => 'ME', 'city' => 'Augusta'],
    '04338' => ['state' => 'ME', 'city' => 'Augusta'],
    '04341' => ['state' => 'ME', 'city' => 'Coopers Mills'],
    '04342' => ['state' => 'ME', 'city' => 'Dresden'],
    '04343' => ['state' => 'ME', 'city' => 'East Winthrop'],
    '04344' => ['state' => 'ME', 'city' => 'Farmingdale'],
    '04345' => ['state' => 'ME', 'city' => 'Gardiner'],
    '04346' => ['state' => 'ME', 'city' => 'Randolph'],
    '04347' => ['state' => 'ME', 'city' => 'Hallowell'],
    '04348' => ['state' => 'ME', 'city' => 'Jefferson'],
    '04349' => ['state' => 'ME', 'city' => 'Kents Hill'],
    '04350' => ['state' => 'ME', 'city' => 'Litchfield'],
    '04351' => ['state' => 'ME', 'city' => 'Manchester'],
    '04352' => ['state' => 'ME', 'city' => 'Mount Vernon'],
    '04353' => ['state' => 'ME', 'city' => 'Whitefield'],
    '04354' => ['state' => 'ME', 'city' => 'Palermo'],
    '04355' => ['state' => 'ME', 'city' => 'Readfield'],
    '04357' => ['state' => 'ME', 'city' => 'Richmond'],
    '04358' => ['state' => 'ME', 'city' => 'South China'],
    '04359' => ['state' => 'ME', 'city' => 'South Gardiner'],
    '04360' => ['state' => 'ME', 'city' => 'Vienna'],
    '04363' => ['state' => 'ME', 'city' => 'Windsor'],
    '04364' => ['state' => 'ME', 'city' => 'Winthrop'],
];
