<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '04841' => ['state' => 'ME', 'city' => 'Rockland'],
    '04843' => ['state' => 'ME', 'city' => 'Camden'],
    '04847' => ['state' => 'ME', 'city' => 'Hope'],
    '04848' => ['state' => 'ME', 'city' => 'Islesboro'],
    '04849' => ['state' => 'ME', 'city' => 'Lincolnville'],
    '04850' => ['state' => 'ME', 'city' => 'Lincolnville Center'],
    '04851' => ['state' => 'ME', 'city' => 'Matinicus'],
    '04852' => ['state' => 'ME', 'city' => 'Monhegan'],
    '04853' => ['state' => 'ME', 'city' => 'North Haven'],
    '04854' => ['state' => 'ME', 'city' => 'Owls Head'],
    '04855' => ['state' => 'ME', 'city' => 'Port Clyde'],
    '04856' => ['state' => 'ME', 'city' => 'Rockport'],
    '04858' => ['state' => 'ME', 'city' => 'South Thomaston'],
    '04859' => ['state' => 'ME', 'city' => 'Spruce Head'],
    '04860' => ['state' => 'ME', 'city' => 'Tenants Harbor'],
    '04861' => ['state' => 'ME', 'city' => 'Thomaston'],
    '04862' => ['state' => 'ME', 'city' => 'Union'],
    '04863' => ['state' => 'ME', 'city' => 'Vinalhaven'],
    '04864' => ['state' => 'ME', 'city' => 'Warren'],
    '04865' => ['state' => 'ME', 'city' => 'West Rockport'],
];
