<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '05101' => ['state' => 'VT', 'city' => 'Bellows Falls'],
    '05141' => ['state' => 'VT', 'city' => 'Cambridgeport'],
    '05142' => ['state' => 'VT', 'city' => 'Cavendish'],
    '05143' => ['state' => 'VT', 'city' => 'Chester'],
    '05146' => ['state' => 'VT', 'city' => 'Grafton'],
    '05148' => ['state' => 'VT', 'city' => 'Londonderry'],
    '05149' => ['state' => 'VT', 'city' => 'Ludlow'],
    '05150' => ['state' => 'VT', 'city' => 'North Springfield'],
    '05151' => ['state' => 'VT', 'city' => 'Perkinsville'],
    '05152' => ['state' => 'VT', 'city' => 'Peru'],
    '05153' => ['state' => 'VT', 'city' => 'Proctorsville'],
    '05154' => ['state' => 'VT', 'city' => 'Saxtons River'],
    '05155' => ['state' => 'VT', 'city' => 'South Londonderry'],
    '05156' => ['state' => 'VT', 'city' => 'Springfield'],
    '05158' => ['state' => 'VT', 'city' => 'Westminster'],
    '05159' => ['state' => 'VT', 'city' => 'Westminster Station'],
    '05161' => ['state' => 'VT', 'city' => 'Weston'],
];
