<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '05201' => ['state' => 'VT', 'city' => 'Bennington'],
    '05250' => ['state' => 'VT', 'city' => 'Arlington'],
    '05251' => ['state' => 'VT', 'city' => 'Dorset'],
    '05252' => ['state' => 'VT', 'city' => 'East Arlington'],
    '05253' => ['state' => 'VT', 'city' => 'East Dorset'],
    '05254' => ['state' => 'VT', 'city' => 'Manchester'],
    '05255' => ['state' => 'VT', 'city' => 'Manchester Center'],
    '05257' => ['state' => 'VT', 'city' => 'North Bennington'],
    '05260' => ['state' => 'VT', 'city' => 'North Pownal'],
    '05261' => ['state' => 'VT', 'city' => 'Pownal'],
    '05262' => ['state' => 'VT', 'city' => 'Shaftsbury'],
];
