<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '05301' => ['state' => 'VT', 'city' => 'Brattleboro'],
    '05302' => ['state' => 'VT', 'city' => 'Brattleboro'],
    '05303' => ['state' => 'VT', 'city' => 'Brattleboro'],
    '05304' => ['state' => 'VT', 'city' => 'Brattleboro'],
    '05340' => ['state' => 'VT', 'city' => 'Bondville'],
    '05341' => ['state' => 'VT', 'city' => 'East Dover'],
    '05342' => ['state' => 'VT', 'city' => 'Jacksonville'],
    '05343' => ['state' => 'VT', 'city' => 'Jamaica'],
    '05344' => ['state' => 'VT', 'city' => 'Marlboro'],
    '05345' => ['state' => 'VT', 'city' => 'Newfane'],
    '05346' => ['state' => 'VT', 'city' => 'Putney'],
    '05350' => ['state' => 'VT', 'city' => 'Readsboro'],
    '05351' => ['state' => 'VT', 'city' => 'South Newfane'],
    '05352' => ['state' => 'VT', 'city' => 'Stamford'],
    '05353' => ['state' => 'VT', 'city' => 'Townshend'],
    '05354' => ['state' => 'VT', 'city' => 'Vernon'],
    '05355' => ['state' => 'VT', 'city' => 'Wardsboro'],
    '05356' => ['state' => 'VT', 'city' => 'West Dover'],
    '05357' => ['state' => 'VT', 'city' => 'West Dummerston'],
    '05358' => ['state' => 'VT', 'city' => 'West Halifax'],
    '05359' => ['state' => 'VT', 'city' => 'West Townshend'],
    '05360' => ['state' => 'VT', 'city' => 'West Wardsboro'],
    '05361' => ['state' => 'VT', 'city' => 'Whitingham'],
    '05362' => ['state' => 'VT', 'city' => 'Williamsville'],
    '05363' => ['state' => 'VT', 'city' => 'Wilmington'],
];
