<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '05901' => ['state' => 'VT', 'city' => 'Averill'],
    '05902' => ['state' => 'VT', 'city' => 'Beecher Falls'],
    '05903' => ['state' => 'VT', 'city' => 'Canaan'],
    '05904' => ['state' => 'VT', 'city' => 'Gilman'],
    '05905' => ['state' => 'VT', 'city' => 'Guildhall'],
    '05906' => ['state' => 'VT', 'city' => 'Lunenburg'],
    '05907' => ['state' => 'VT', 'city' => 'Norton'],
];
