<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '07101' => ['state' => 'NJ', 'city' => 'Newark'],
    '07102' => ['state' => 'NJ', 'city' => 'Newark'],
    '07103' => ['state' => 'NJ', 'city' => 'Newark'],
    '07104' => ['state' => 'NJ', 'city' => 'Newark'],
    '07105' => ['state' => 'NJ', 'city' => 'Newark'],
    '07106' => ['state' => 'NJ', 'city' => 'Newark'],
    '07107' => ['state' => 'NJ', 'city' => 'Newark'],
    '07108' => ['state' => 'NJ', 'city' => 'Newark'],
    '07109' => ['state' => 'NJ', 'city' => 'Belleville'],
    '07110' => ['state' => 'NJ', 'city' => 'Nutley'],
    '07111' => ['state' => 'NJ', 'city' => 'Irvington'],
    '07112' => ['state' => 'NJ', 'city' => 'Newark'],
    '07114' => ['state' => 'NJ', 'city' => 'Newark'],
    '07175' => ['state' => 'NJ', 'city' => 'Newark'],
    '07184' => ['state' => 'NJ', 'city' => 'Newark'],
    '07188' => ['state' => 'NJ', 'city' => 'Newark'],
    '07189' => ['state' => 'NJ', 'city' => 'Newark'],
    '07191' => ['state' => 'NJ', 'city' => 'Newark'],
    '07192' => ['state' => 'NJ', 'city' => 'Newark'],
    '07193' => ['state' => 'NJ', 'city' => 'Newark'],
    '07195' => ['state' => 'NJ', 'city' => 'Newark'],
    '07198' => ['state' => 'NJ', 'city' => 'Newark'],
    '07199' => ['state' => 'NJ', 'city' => 'Newark'],
];
