<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '07201' => ['state' => 'NJ', 'city' => 'Elizabeth'],
    '07202' => ['state' => 'NJ', 'city' => 'Elizabeth'],
    '07203' => ['state' => 'NJ', 'city' => 'Roselle'],
    '07204' => ['state' => 'NJ', 'city' => 'Roselle Park'],
    '07205' => ['state' => 'NJ', 'city' => 'Hillside'],
    '07206' => ['state' => 'NJ', 'city' => 'Elizabethport'],
    '07207' => ['state' => 'NJ', 'city' => 'Elizabeth'],
    '07208' => ['state' => 'NJ', 'city' => 'Elizabeth'],
];
