<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '07302' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07303' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07304' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07305' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07306' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07307' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07308' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07310' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07311' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07395' => ['state' => 'NJ', 'city' => 'Jersey City'],
    '07399' => ['state' => 'NJ', 'city' => 'Jersey City'],
];
