<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '08101' => ['state' => 'NJ', 'city' => 'Camden'],
    '08102' => ['state' => 'NJ', 'city' => 'Camden'],
    '08103' => ['state' => 'NJ', 'city' => 'Camden'],
    '08104' => ['state' => 'NJ', 'city' => 'Camden'],
    '08105' => ['state' => 'NJ', 'city' => 'Camden'],
    '08106' => ['state' => 'NJ', 'city' => 'Audubon'],
    '08107' => ['state' => 'NJ', 'city' => 'Oaklyn'],
    '08108' => ['state' => 'NJ', 'city' => 'Collingswood'],
    '08109' => ['state' => 'NJ', 'city' => 'Merchantville'],
    '08110' => ['state' => 'NJ', 'city' => 'Pennsauken'],
];
