<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '08401' => ['state' => 'NJ', 'city' => 'Atlantic City'],
    '08402' => ['state' => 'NJ', 'city' => 'Margate City'],
    '08403' => ['state' => 'NJ', 'city' => 'Longport'],
    '08404' => ['state' => 'NJ', 'city' => 'Atlantic City'],
    '08405' => ['state' => 'NJ', 'city' => 'Atlantic City'],
    '08406' => ['state' => 'NJ', 'city' => 'Ventnor City'],
];
