<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '08701' => ['state' => 'NJ', 'city' => 'Lakewood'],
    '08720' => ['state' => 'NJ', 'city' => 'Allenwood'],
    '08721' => ['state' => 'NJ', 'city' => 'Bayville'],
    '08722' => ['state' => 'NJ', 'city' => 'Beachwood'],
    '08723' => ['state' => 'NJ', 'city' => 'Brick'],
    '08724' => ['state' => 'NJ', 'city' => 'Brick'],
    '08730' => ['state' => 'NJ', 'city' => 'Brielle'],
    '08731' => ['state' => 'NJ', 'city' => 'Forked River'],
    '08732' => ['state' => 'NJ', 'city' => 'Island Heights'],
    '08733' => ['state' => 'NJ', 'city' => 'Lakehurst'],
    '08734' => ['state' => 'NJ', 'city' => 'Lanoka Harbor'],
    '08735' => ['state' => 'NJ', 'city' => 'Lavallette'],
    '08736' => ['state' => 'NJ', 'city' => 'Manasquan'],
    '08738' => ['state' => 'NJ', 'city' => 'Mantoloking'],
    '08739' => ['state' => 'NJ', 'city' => 'Normandy Beach'],
    '08740' => ['state' => 'NJ', 'city' => 'Ocean Gate'],
    '08741' => ['state' => 'NJ', 'city' => 'Pine Beach'],
    '08742' => ['state' => 'NJ', 'city' => 'Point Pleasant Beach'],
    '08750' => ['state' => 'NJ', 'city' => 'Sea Girt'],
    '08751' => ['state' => 'NJ', 'city' => 'Seaside Heights'],
    '08752' => ['state' => 'NJ', 'city' => 'Seaside Park'],
    '08753' => ['state' => 'NJ', 'city' => 'Toms River'],
    '08754' => ['state' => 'NJ', 'city' => 'Toms River'],
    '08755' => ['state' => 'NJ', 'city' => 'Toms River'],
    '08756' => ['state' => 'NJ', 'city' => 'Toms River'],
    '08757' => ['state' => 'NJ', 'city' => 'Toms River'],
    '08758' => ['state' => 'NJ', 'city' => 'Waretown'],
    '08759' => ['state' => 'NJ', 'city' => 'Manchester Township'],
];
