<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '08901' => ['state' => 'NJ', 'city' => 'New Brunswick'],
    '08902' => ['state' => 'NJ', 'city' => 'North Brunswick'],
    '08903' => ['state' => 'NJ', 'city' => 'New Brunswick'],
    '08904' => ['state' => 'NJ', 'city' => 'Highland Park'],
    '08906' => ['state' => 'NJ', 'city' => 'New Brunswick'],
    '08933' => ['state' => 'NJ', 'city' => 'New Brunswick'],
    '08989' => ['state' => 'NJ', 'city' => 'New Brunswick'],
];
