<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '10301' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10302' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10303' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10304' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10305' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10306' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10307' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10308' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10309' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10310' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10311' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10312' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10313' => ['state' => 'NY', 'city' => 'Staten Island'],
    '10314' => ['state' => 'NY', 'city' => 'Staten Island'],
];
