<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '10601' => ['state' => 'NY', 'city' => 'White Plains'],
    '10602' => ['state' => 'NY', 'city' => 'White Plains'],
    '10603' => ['state' => 'NY', 'city' => 'White Plains'],
    '10604' => ['state' => 'NY', 'city' => 'West Harrison'],
    '10605' => ['state' => 'NY', 'city' => 'White Plains'],
    '10606' => ['state' => 'NY', 'city' => 'White Plains'],
    '10607' => ['state' => 'NY', 'city' => 'White Plains'],
    '10610' => ['state' => 'NY', 'city' => 'White Plains'],
];
