<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '10701' => ['state' => 'NY', 'city' => 'Yonkers'],
    '10702' => ['state' => 'NY', 'city' => 'Yonkers'],
    '10703' => ['state' => 'NY', 'city' => 'Yonkers'],
    '10704' => ['state' => 'NY', 'city' => 'Yonkers'],
    '10705' => ['state' => 'NY', 'city' => 'Yonkers'],
    '10706' => ['state' => 'NY', 'city' => 'Hastings On Hudson'],
    '10707' => ['state' => 'NY', 'city' => 'Tuckahoe'],
    '10708' => ['state' => 'NY', 'city' => 'Bronxville'],
    '10709' => ['state' => 'NY', 'city' => 'Eastchester'],
    '10710' => ['state' => 'NY', 'city' => 'Yonkers'],
];
