<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '10801' => ['state' => 'NY', 'city' => 'New Rochelle'],
    '10802' => ['state' => 'NY', 'city' => 'New Rochelle'],
    '10803' => ['state' => 'NY', 'city' => 'Pelham'],
    '10804' => ['state' => 'NY', 'city' => 'New Rochelle'],
    '10805' => ['state' => 'NY', 'city' => 'New Rochelle'],
];
