<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '11001' => ['state' => 'NY', 'city' => 'Floral Park'],
    '11002' => ['state' => 'NY', 'city' => 'Floral Park'],
    '11003' => ['state' => 'NY', 'city' => 'Elmont'],
    '11004' => ['state' => 'NY', 'city' => 'Glen Oaks'],
    '11005' => ['state' => 'NY', 'city' => 'Floral Park'],
    '11010' => ['state' => 'NY', 'city' => 'Franklin Square'],
    '11020' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11021' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11022' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11023' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11024' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11026' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11027' => ['state' => 'NY', 'city' => 'Great Neck'],
    '11030' => ['state' => 'NY', 'city' => 'Manhasset'],
    '11040' => ['state' => 'NY', 'city' => 'New Hyde Park'],
    '11042' => ['state' => 'NY', 'city' => 'New Hyde Park'],
    '11050' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11051' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11052' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11053' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11054' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11055' => ['state' => 'NY', 'city' => 'Port Washington'],
    '11096' => ['state' => 'NY', 'city' => 'Inwood'],
];
