<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '11101' => ['state' => 'NY', 'city' => 'Long Island City'],
    '11102' => ['state' => 'NY', 'city' => 'Astoria'],
    '11103' => ['state' => 'NY', 'city' => 'Astoria'],
    '11104' => ['state' => 'NY', 'city' => 'Sunnyside'],
    '11105' => ['state' => 'NY', 'city' => 'Astoria'],
    '11106' => ['state' => 'NY', 'city' => 'Astoria'],
    '11109' => ['state' => 'NY', 'city' => 'Long Island City'],
    '11120' => ['state' => 'NY', 'city' => 'Long Island City'],
];
