<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '11690' => ['state' => 'NY', 'city' => 'Far Rockaway'],
    '11691' => ['state' => 'NY', 'city' => 'Far Rockaway'],
    '11692' => ['state' => 'NY', 'city' => 'Arverne'],
    '11693' => ['state' => 'NY', 'city' => 'Far Rockaway'],
    '11694' => ['state' => 'NY', 'city' => 'Rockaway Park'],
    '11695' => ['state' => 'NY', 'city' => 'Far Rockaway'],
    '11697' => ['state' => 'NY', 'city' => 'Breezy Point'],
];
