<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '11801' => ['state' => 'NY', 'city' => 'Hicksville'],
    '11802' => ['state' => 'NY', 'city' => 'Hicksville'],
    '11803' => ['state' => 'NY', 'city' => 'Plainview'],
    '11804' => ['state' => 'NY', 'city' => 'Old Bethpage'],
    '11815' => ['state' => 'NY', 'city' => 'Hicksville'],
    '11819' => ['state' => 'NY', 'city' => 'Hicksville'],
    '11853' => ['state' => 'NY', 'city' => 'Jericho'],
];
