<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '12601' => ['state' => 'NY', 'city' => 'Poughkeepsie'],
    '12602' => ['state' => 'NY', 'city' => 'Poughkeepsie'],
    '12603' => ['state' => 'NY', 'city' => 'Poughkeepsie'],
    '12604' => ['state' => 'NY', 'city' => 'Poughkeepsie'],
];
