<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '13501' => ['state' => 'NY', 'city' => 'Utica'],
    '13502' => ['state' => 'NY', 'city' => 'Utica'],
    '13503' => ['state' => 'NY', 'city' => 'Utica'],
    '13504' => ['state' => 'NY', 'city' => 'Utica'],
    '13505' => ['state' => 'NY', 'city' => 'Utica'],
    '13599' => ['state' => 'NY', 'city' => 'Utica'],
];
