<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '13901' => ['state' => 'NY', 'city' => 'Binghamton'],
    '13902' => ['state' => 'NY', 'city' => 'Binghamton'],
    '13903' => ['state' => 'NY', 'city' => 'Binghamton'],
    '13904' => ['state' => 'NY', 'city' => 'Binghamton'],
    '13905' => ['state' => 'NY', 'city' => 'Binghamton'],
];
