<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '14301' => ['state' => 'NY', 'city' => 'Niagara Falls'],
    '14302' => ['state' => 'NY', 'city' => 'Niagara Falls'],
    '14303' => ['state' => 'NY', 'city' => 'Niagara Falls'],
    '14304' => ['state' => 'NY', 'city' => 'Niagara Falls'],
    '14305' => ['state' => 'NY', 'city' => 'Niagara Falls'],
];
