<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '16701' => ['state' => 'PA', 'city' => 'Bradford'],
    '16720' => ['state' => 'PA', 'city' => 'Austin'],
    '16724' => ['state' => 'PA', 'city' => 'Crosby'],
    '16725' => ['state' => 'PA', 'city' => 'Custer City'],
    '16726' => ['state' => 'PA', 'city' => 'Cyclone'],
    '16727' => ['state' => 'PA', 'city' => 'Derrick City'],
    '16728' => ['state' => 'PA', 'city' => 'De Young'],
    '16729' => ['state' => 'PA', 'city' => 'Duke Center'],
    '16730' => ['state' => 'PA', 'city' => 'East Smethport'],
    '16731' => ['state' => 'PA', 'city' => 'Eldred'],
    '16732' => ['state' => 'PA', 'city' => 'Gifford'],
    '16733' => ['state' => 'PA', 'city' => 'Hazel Hurst'],
    '16734' => ['state' => 'PA', 'city' => 'James City'],
    '16735' => ['state' => 'PA', 'city' => 'Kane'],
    '16738' => ['state' => 'PA', 'city' => 'Lewis Run'],
    '16740' => ['state' => 'PA', 'city' => 'Mount Jewett'],
    '16743' => ['state' => 'PA', 'city' => 'Port Allegany'],
    '16744' => ['state' => 'PA', 'city' => 'Rew'],
    '16745' => ['state' => 'PA', 'city' => 'Rixford'],
    '16746' => ['state' => 'PA', 'city' => 'Roulette'],
    '16748' => ['state' => 'PA', 'city' => 'Shinglehouse'],
    '16749' => ['state' => 'PA', 'city' => 'Smethport'],
    '16750' => ['state' => 'PA', 'city' => 'Turtlepoint'],
];
