<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '17401' => ['state' => 'PA', 'city' => 'York'],
    '17402' => ['state' => 'PA', 'city' => 'York'],
    '17403' => ['state' => 'PA', 'city' => 'York'],
    '17404' => ['state' => 'PA', 'city' => 'York'],
    '17405' => ['state' => 'PA', 'city' => 'York'],
    '17406' => ['state' => 'PA', 'city' => 'York'],
    '17407' => ['state' => 'PA', 'city' => 'York'],
    '17408' => ['state' => 'PA', 'city' => 'York'],
];
