<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '17601' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17602' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17603' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17604' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17605' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17606' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17607' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17608' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17611' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17622' => ['state' => 'PA', 'city' => 'Lancaster'],
    '17699' => ['state' => 'PA', 'city' => 'Lancaster'],
];
