<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '18501' => ['state' => 'PA', 'city' => 'Scranton'],
    '18502' => ['state' => 'PA', 'city' => 'Scranton'],
    '18503' => ['state' => 'PA', 'city' => 'Scranton'],
    '18504' => ['state' => 'PA', 'city' => 'Scranton'],
    '18505' => ['state' => 'PA', 'city' => 'Scranton'],
    '18507' => ['state' => 'PA', 'city' => 'Moosic'],
    '18508' => ['state' => 'PA', 'city' => 'Scranton'],
    '18509' => ['state' => 'PA', 'city' => 'Scranton'],
    '18510' => ['state' => 'PA', 'city' => 'Scranton'],
    '18512' => ['state' => 'PA', 'city' => 'Scranton'],
    '18515' => ['state' => 'PA', 'city' => 'Scranton'],
    '18517' => ['state' => 'PA', 'city' => 'Taylor'],
    '18518' => ['state' => 'PA', 'city' => 'Old Forge'],
    '18519' => ['state' => 'PA', 'city' => 'Scranton'],
    '18540' => ['state' => 'PA', 'city' => 'Scranton'],
    '18577' => ['state' => 'PA', 'city' => 'Scranton'],
];
