<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '19601' => ['state' => 'PA', 'city' => 'Reading'],
    '19602' => ['state' => 'PA', 'city' => 'Reading'],
    '19603' => ['state' => 'PA', 'city' => 'Reading'],
    '19604' => ['state' => 'PA', 'city' => 'Reading'],
    '19605' => ['state' => 'PA', 'city' => 'Reading'],
    '19606' => ['state' => 'PA', 'city' => 'Reading'],
    '19607' => ['state' => 'PA', 'city' => 'Reading'],
    '19608' => ['state' => 'PA', 'city' => 'Reading'],
    '19609' => ['state' => 'PA', 'city' => 'Reading'],
    '19610' => ['state' => 'PA', 'city' => 'Reading'],
    '19611' => ['state' => 'PA', 'city' => 'Reading'],
    '19612' => ['state' => 'PA', 'city' => 'Reading'],
];
