<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '19701' => ['state' => 'DE', 'city' => 'Bear'],
    '19702' => ['state' => 'DE', 'city' => 'Newark'],
    '19703' => ['state' => 'DE', 'city' => 'Claymont'],
    '19706' => ['state' => 'DE', 'city' => 'Delaware City'],
    '19707' => ['state' => 'DE', 'city' => 'Hockessin'],
    '19708' => ['state' => 'DE', 'city' => 'Kirkwood'],
    '19709' => ['state' => 'DE', 'city' => 'Middletown'],
    '19710' => ['state' => 'DE', 'city' => 'Montchanin'],
    '19711' => ['state' => 'DE', 'city' => 'Newark'],
    '19712' => ['state' => 'DE', 'city' => 'Newark'],
    '19713' => ['state' => 'DE', 'city' => 'Newark'],
    '19714' => ['state' => 'DE', 'city' => 'Newark'],
    '19715' => ['state' => 'DE', 'city' => 'Newark'],
    '19716' => ['state' => 'DE', 'city' => 'Newark'],
    '19717' => ['state' => 'DE', 'city' => 'Newark'],
    '19718' => ['state' => 'DE', 'city' => 'Newark'],
    '19720' => ['state' => 'DE', 'city' => 'New Castle'],
    '19721' => ['state' => 'DE', 'city' => 'New Castle'],
    '19725' => ['state' => 'DE', 'city' => 'Newark'],
    '19726' => ['state' => 'DE', 'city' => 'New Castle'],
    '19730' => ['state' => 'DE', 'city' => 'Odessa'],
    '19731' => ['state' => 'DE', 'city' => 'Port Penn'],
    '19732' => ['state' => 'DE', 'city' => 'Rockland'],
    '19733' => ['state' => 'DE', 'city' => 'Saint Georges'],
    '19734' => ['state' => 'DE', 'city' => 'Townsend'],
    '19735' => ['state' => 'DE', 'city' => 'Winterthur'],
    '19736' => ['state' => 'DE', 'city' => 'Yorklyn'],
];
