<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '21901' => ['state' => 'MD', 'city' => 'North East'],
    '21902' => ['state' => 'MD', 'city' => 'Perry Point'],
    '21903' => ['state' => 'MD', 'city' => 'Perryville'],
    '21904' => ['state' => 'MD', 'city' => 'Port Deposit'],
    '21911' => ['state' => 'MD', 'city' => 'Rising Sun'],
    '21912' => ['state' => 'MD', 'city' => 'Warwick'],
    '21913' => ['state' => 'MD', 'city' => 'Cecilton'],
    '21914' => ['state' => 'MD', 'city' => 'Charlestown'],
    '21915' => ['state' => 'MD', 'city' => 'Chesapeake City'],
    '21916' => ['state' => 'MD', 'city' => 'Childs'],
    '21917' => ['state' => 'MD', 'city' => 'Colora'],
    '21918' => ['state' => 'MD', 'city' => 'Conowingo'],
    '21919' => ['state' => 'MD', 'city' => 'Earleville'],
    '21920' => ['state' => 'MD', 'city' => 'Elk Mills'],
    '21921' => ['state' => 'MD', 'city' => 'Elkton'],
    '21922' => ['state' => 'MD', 'city' => 'Elkton'],
    '21930' => ['state' => 'MD', 'city' => 'Georgetown'],
];
