<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '22201' => ['state' => 'VA', 'city' => 'Arlington'],
    '22202' => ['state' => 'VA', 'city' => 'Arlington'],
    '22203' => ['state' => 'VA', 'city' => 'Arlington'],
    '22204' => ['state' => 'VA', 'city' => 'Arlington'],
    '22205' => ['state' => 'VA', 'city' => 'Arlington'],
    '22206' => ['state' => 'VA', 'city' => 'Arlington'],
    '22207' => ['state' => 'VA', 'city' => 'Arlington'],
    '22209' => ['state' => 'VA', 'city' => 'Arlington'],
    '22210' => ['state' => 'VA', 'city' => 'Arlington'],
    '22211' => ['state' => 'VA', 'city' => 'Fort Myer'],
    '22212' => ['state' => 'VA', 'city' => 'Arlington'],
    '22213' => ['state' => 'VA', 'city' => 'Arlington'],
    '22214' => ['state' => 'VA', 'city' => 'Arlington'],
    '22215' => ['state' => 'VA', 'city' => 'Arlington'],
    '22216' => ['state' => 'VA', 'city' => 'Arlington'],
    '22217' => ['state' => 'VA', 'city' => 'Arlington'],
    '22219' => ['state' => 'VA', 'city' => 'Arlington'],
    '22225' => ['state' => 'VA', 'city' => 'Arlington'],
    '22226' => ['state' => 'VA', 'city' => 'Arlington'],
    '22227' => ['state' => 'VA', 'city' => 'Arlington'],
    '22230' => ['state' => 'VA', 'city' => 'Arlington'],
    '22240' => ['state' => 'VA', 'city' => 'Arlington'],
    '22241' => ['state' => 'VA', 'city' => 'Arlington'],
    '22242' => ['state' => 'VA', 'city' => 'Arlington'],
    '22243' => ['state' => 'VA', 'city' => 'Arlington'],
    '22244' => ['state' => 'VA', 'city' => 'Arlington'],
    '22245' => ['state' => 'VA', 'city' => 'Arlington'],
    '22246' => ['state' => 'VA', 'city' => 'Arlington'],
];
