<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '23701' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23702' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23703' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23704' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23705' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23707' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23708' => ['state' => 'VA', 'city' => 'Portsmouth'],
    '23709' => ['state' => 'VA', 'city' => 'Portsmouth'],
];
