<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '24701' => ['state' => 'WV', 'city' => 'Bluefield'],
    '24712' => ['state' => 'WV', 'city' => 'Athens'],
    '24714' => ['state' => 'WV', 'city' => 'Beeson'],
    '24715' => ['state' => 'WV', 'city' => 'Bramwell'],
    '24716' => ['state' => 'WV', 'city' => 'Bud'],
    '24719' => ['state' => 'WV', 'city' => 'Covel'],
    '24724' => ['state' => 'WV', 'city' => 'Freeman'],
    '24726' => ['state' => 'WV', 'city' => 'Herndon'],
    '24729' => ['state' => 'WV', 'city' => 'Hiawatha'],
    '24731' => ['state' => 'WV', 'city' => 'Kegley'],
    '24732' => ['state' => 'WV', 'city' => 'Kellysville'],
    '24733' => ['state' => 'WV', 'city' => 'Lashmeet'],
    '24736' => ['state' => 'WV', 'city' => 'Matoaka'],
    '24737' => ['state' => 'WV', 'city' => 'Montcalm'],
    '24738' => ['state' => 'WV', 'city' => 'Nemours'],
    '24739' => ['state' => 'WV', 'city' => 'Princeton'],
    '24740' => ['state' => 'WV', 'city' => 'Princeton'],
    '24747' => ['state' => 'WV', 'city' => 'Rock'],
    '24751' => ['state' => 'WV', 'city' => 'Wolfe'],
];
