<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '26003' => ['state' => 'WV', 'city' => 'Wheeling'],
    '26030' => ['state' => 'WV', 'city' => 'Beech Bottom'],
    '26031' => ['state' => 'WV', 'city' => 'Benwood'],
    '26032' => ['state' => 'WV', 'city' => 'Bethany'],
    '26033' => ['state' => 'WV', 'city' => 'Cameron'],
    '26034' => ['state' => 'WV', 'city' => 'Chester'],
    '26035' => ['state' => 'WV', 'city' => 'Colliers'],
    '26036' => ['state' => 'WV', 'city' => 'Dallas'],
    '26037' => ['state' => 'WV', 'city' => 'Follansbee'],
    '26038' => ['state' => 'WV', 'city' => 'Glen Dale'],
    '26039' => ['state' => 'WV', 'city' => 'Glen Easton'],
    '26040' => ['state' => 'WV', 'city' => 'Mcmechen'],
    '26041' => ['state' => 'WV', 'city' => 'Moundsville'],
    '26047' => ['state' => 'WV', 'city' => 'New Cumberland'],
    '26050' => ['state' => 'WV', 'city' => 'Newell'],
    '26055' => ['state' => 'WV', 'city' => 'Proctor'],
    '26056' => ['state' => 'WV', 'city' => 'New Manchester'],
    '26058' => ['state' => 'WV', 'city' => 'Short Creek'],
    '26059' => ['state' => 'WV', 'city' => 'Triadelphia'],
    '26060' => ['state' => 'WV', 'city' => 'Valley Grove'],
    '26062' => ['state' => 'WV', 'city' => 'Weirton'],
    '26070' => ['state' => 'WV', 'city' => 'Wellsburg'],
    '26074' => ['state' => 'WV', 'city' => 'West Liberty'],
    '26075' => ['state' => 'WV', 'city' => 'Windsor Heights'],
];
