<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '26704' => ['state' => 'WV', 'city' => 'Augusta'],
    '26705' => ['state' => 'WV', 'city' => 'Aurora'],
    '26707' => ['state' => 'WV', 'city' => 'Bayard'],
    '26710' => ['state' => 'WV', 'city' => 'Burlington'],
    '26711' => ['state' => 'WV', 'city' => 'Capon Bridge'],
    '26714' => ['state' => 'WV', 'city' => 'Delray'],
    '26716' => ['state' => 'WV', 'city' => 'Eglon'],
    '26717' => ['state' => 'WV', 'city' => 'Elk Garden'],
    '26719' => ['state' => 'WV', 'city' => 'Fort Ashby'],
    '26720' => ['state' => 'WV', 'city' => 'Gormania'],
    '26722' => ['state' => 'WV', 'city' => 'Green Spring'],
    '26726' => ['state' => 'WV', 'city' => 'Keyser'],
    '26731' => ['state' => 'WV', 'city' => 'Lahmansville'],
    '26739' => ['state' => 'WV', 'city' => 'Mount Storm'],
    '26743' => ['state' => 'WV', 'city' => 'New Creek'],
    '26750' => ['state' => 'WV', 'city' => 'Piedmont'],
    '26753' => ['state' => 'WV', 'city' => 'Ridgeley'],
    '26755' => ['state' => 'WV', 'city' => 'Rio'],
    '26757' => ['state' => 'WV', 'city' => 'Romney'],
    '26761' => ['state' => 'WV', 'city' => 'Shanks'],
    '26763' => ['state' => 'WV', 'city' => 'Springfield'],
    '26764' => ['state' => 'WV', 'city' => 'Terra Alta'],
    '26767' => ['state' => 'WV', 'city' => 'Wiley Ford'],
];
