<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '26801' => ['state' => 'WV', 'city' => 'Baker'],
    '26802' => ['state' => 'WV', 'city' => 'Brandywine'],
    '26804' => ['state' => 'WV', 'city' => 'Circleville'],
    '26807' => ['state' => 'WV', 'city' => 'Franklin'],
    '26808' => ['state' => 'WV', 'city' => 'High View'],
    '26810' => ['state' => 'WV', 'city' => 'Lost City'],
    '26812' => ['state' => 'WV', 'city' => 'Mathias'],
    '26814' => ['state' => 'WV', 'city' => 'Riverton'],
    '26815' => ['state' => 'WV', 'city' => 'Sugar Grove'],
    '26817' => ['state' => 'WV', 'city' => 'Bloomery'],
    '26818' => ['state' => 'WV', 'city' => 'Fisher'],
    '26823' => ['state' => 'WV', 'city' => 'Capon Springs'],
    '26833' => ['state' => 'WV', 'city' => 'Maysville'],
    '26836' => ['state' => 'WV', 'city' => 'Moorefield'],
    '26838' => ['state' => 'WV', 'city' => 'Milam'],
    '26845' => ['state' => 'WV', 'city' => 'Old Fields'],
    '26847' => ['state' => 'WV', 'city' => 'Petersburg'],
    '26851' => ['state' => 'WV', 'city' => 'Wardensville'],
    '26852' => ['state' => 'WV', 'city' => 'Purgitsville'],
    '26855' => ['state' => 'WV', 'city' => 'Cabins'],
    '26865' => ['state' => 'WV', 'city' => 'Yellow Spring'],
    '26866' => ['state' => 'WV', 'city' => 'Upper Tract'],
    '26884' => ['state' => 'WV', 'city' => 'Seneca Rocks'],
    '26886' => ['state' => 'WV', 'city' => 'Onego'],
];
