<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '27701' => ['state' => 'NC', 'city' => 'Durham'],
    '27702' => ['state' => 'NC', 'city' => 'Durham'],
    '27703' => ['state' => 'NC', 'city' => 'Durham'],
    '27704' => ['state' => 'NC', 'city' => 'Durham'],
    '27705' => ['state' => 'NC', 'city' => 'Durham'],
    '27706' => ['state' => 'NC', 'city' => 'Durham'],
    '27707' => ['state' => 'NC', 'city' => 'Durham'],
    '27708' => ['state' => 'NC', 'city' => 'Durham'],
    '27709' => ['state' => 'NC', 'city' => 'Durham'],
    '27710' => ['state' => 'NC', 'city' => 'Durham'],
    '27711' => ['state' => 'NC', 'city' => 'Durham'],
    '27712' => ['state' => 'NC', 'city' => 'Durham'],
    '27713' => ['state' => 'NC', 'city' => 'Durham'],
    '27715' => ['state' => 'NC', 'city' => 'Durham'],
    '27717' => ['state' => 'NC', 'city' => 'Durham'],
    '27722' => ['state' => 'NC', 'city' => 'Durham'],
];
