<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '28801' => ['state' => 'NC', 'city' => 'Asheville'],
    '28802' => ['state' => 'NC', 'city' => 'Asheville'],
    '28803' => ['state' => 'NC', 'city' => 'Asheville'],
    '28804' => ['state' => 'NC', 'city' => 'Asheville'],
    '28805' => ['state' => 'NC', 'city' => 'Asheville'],
    '28806' => ['state' => 'NC', 'city' => 'Asheville'],
    '28810' => ['state' => 'NC', 'city' => 'Asheville'],
    '28813' => ['state' => 'NC', 'city' => 'Asheville'],
    '28814' => ['state' => 'NC', 'city' => 'Asheville'],
    '28815' => ['state' => 'NC', 'city' => 'Asheville'],
    '28816' => ['state' => 'NC', 'city' => 'Asheville'],
];
