<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '30802' => ['state' => 'GA', 'city' => 'Appling'],
    '30803' => ['state' => 'GA', 'city' => 'Avera'],
    '30805' => ['state' => 'GA', 'city' => 'Blythe'],
    '30806' => ['state' => 'GA', 'city' => 'Boneville'],
    '30807' => ['state' => 'GA', 'city' => 'Camak'],
    '30808' => ['state' => 'GA', 'city' => 'Dearing'],
    '30809' => ['state' => 'GA', 'city' => 'Evans'],
    '30810' => ['state' => 'GA', 'city' => 'Gibson'],
    '30811' => ['state' => 'GA', 'city' => 'Gough'],
    '30812' => ['state' => 'GA', 'city' => 'Gracewood'],
    '30813' => ['state' => 'GA', 'city' => 'Grovetown'],
    '30814' => ['state' => 'GA', 'city' => 'Harlem'],
    '30815' => ['state' => 'GA', 'city' => 'Hephzibah'],
    '30816' => ['state' => 'GA', 'city' => 'Keysville'],
    '30817' => ['state' => 'GA', 'city' => 'Lincolnton'],
    '30818' => ['state' => 'GA', 'city' => 'Matthews'],
    '30819' => ['state' => 'GA', 'city' => 'Mesena'],
    '30820' => ['state' => 'GA', 'city' => 'Mitchell'],
    '30821' => ['state' => 'GA', 'city' => 'Norwood'],
    '30822' => ['state' => 'GA', 'city' => 'Perkins'],
    '30823' => ['state' => 'GA', 'city' => 'Stapleton'],
    '30824' => ['state' => 'GA', 'city' => 'Thomson'],
    '30828' => ['state' => 'GA', 'city' => 'Warrenton'],
    '30830' => ['state' => 'GA', 'city' => 'Waynesboro'],
    '30833' => ['state' => 'GA', 'city' => 'Wrens'],
];
