<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '30901' => ['state' => 'GA', 'city' => 'Augusta'],
    '30903' => ['state' => 'GA', 'city' => 'Augusta'],
    '30904' => ['state' => 'GA', 'city' => 'Augusta'],
    '30905' => ['state' => 'GA', 'city' => 'Augusta'],
    '30906' => ['state' => 'GA', 'city' => 'Augusta'],
    '30907' => ['state' => 'GA', 'city' => 'Augusta'],
    '30909' => ['state' => 'GA', 'city' => 'Augusta'],
    '30912' => ['state' => 'GA', 'city' => 'Augusta'],
    '30914' => ['state' => 'GA', 'city' => 'Augusta'],
    '30916' => ['state' => 'GA', 'city' => 'Augusta'],
    '30917' => ['state' => 'GA', 'city' => 'Augusta'],
    '30919' => ['state' => 'GA', 'city' => 'Augusta'],
    '30999' => ['state' => 'GA', 'city' => 'Augusta'],
];
