<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '31106' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31107' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31119' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31126' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31131' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31136' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31139' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31141' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31144' => ['state' => 'GA', 'city' => 'Kennesaw'],
    '31145' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31146' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31150' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31156' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31169' => ['state' => 'GA', 'city' => 'Peachtree City'],
    '31192' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31193' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31195' => ['state' => 'GA', 'city' => 'Atlanta'],
    '31196' => ['state' => 'GA', 'city' => 'Atlanta'],
];
