<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '31301' => ['state' => 'GA', 'city' => 'Allenhurst'],
    '31302' => ['state' => 'GA', 'city' => 'Bloomingdale'],
    '31303' => ['state' => 'GA', 'city' => 'Clyo'],
    '31304' => ['state' => 'GA', 'city' => 'Crescent'],
    '31305' => ['state' => 'GA', 'city' => 'Darien'],
    '31307' => ['state' => 'GA', 'city' => 'Eden'],
    '31308' => ['state' => 'GA', 'city' => 'Ellabell'],
    '31309' => ['state' => 'GA', 'city' => 'Fleming'],
    '31310' => ['state' => 'GA', 'city' => 'Hinesville'],
    '31312' => ['state' => 'GA', 'city' => 'Guyton'],
    '31313' => ['state' => 'GA', 'city' => 'Hinesville'],
    '31314' => ['state' => 'GA', 'city' => 'Fort Stewart'],
    '31315' => ['state' => 'GA', 'city' => 'Fort Stewart'],
    '31316' => ['state' => 'GA', 'city' => 'Ludowici'],
    '31318' => ['state' => 'GA', 'city' => 'Meldrim'],
    '31319' => ['state' => 'GA', 'city' => 'Meridian'],
    '31320' => ['state' => 'GA', 'city' => 'Midway'],
    '31321' => ['state' => 'GA', 'city' => 'Pembroke'],
    '31322' => ['state' => 'GA', 'city' => 'Pooler'],
    '31323' => ['state' => 'GA', 'city' => 'Riceboro'],
    '31324' => ['state' => 'GA', 'city' => 'Richmond Hill'],
    '31326' => ['state' => 'GA', 'city' => 'Rincon'],
    '31327' => ['state' => 'GA', 'city' => 'Sapelo Island'],
    '31328' => ['state' => 'GA', 'city' => 'Tybee Island'],
    '31329' => ['state' => 'GA', 'city' => 'Springfield'],
    '31331' => ['state' => 'GA', 'city' => 'Townsend'],
    '31333' => ['state' => 'GA', 'city' => 'Walthourville'],
];
