<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '31801' => ['state' => 'GA', 'city' => 'Box Springs'],
    '31803' => ['state' => 'GA', 'city' => 'Buena Vista'],
    '31804' => ['state' => 'GA', 'city' => 'Cataula'],
    '31805' => ['state' => 'GA', 'city' => 'Cusseta'],
    '31806' => ['state' => 'GA', 'city' => 'Ellaville'],
    '31807' => ['state' => 'GA', 'city' => 'Ellerslie'],
    '31808' => ['state' => 'GA', 'city' => 'Fortson'],
    '31810' => ['state' => 'GA', 'city' => 'Geneva'],
    '31811' => ['state' => 'GA', 'city' => 'Hamilton'],
    '31812' => ['state' => 'GA', 'city' => 'Junction City'],
    '31814' => ['state' => 'GA', 'city' => 'Louvale'],
    '31815' => ['state' => 'GA', 'city' => 'Lumpkin'],
    '31816' => ['state' => 'GA', 'city' => 'Manchester'],
    '31820' => ['state' => 'GA', 'city' => 'Midland'],
    '31821' => ['state' => 'GA', 'city' => 'Omaha'],
    '31822' => ['state' => 'GA', 'city' => 'Pine Mountain'],
    '31823' => ['state' => 'GA', 'city' => 'Pine Mountain Valley'],
    '31824' => ['state' => 'GA', 'city' => 'Preston'],
    '31825' => ['state' => 'GA', 'city' => 'Richland'],
    '31826' => ['state' => 'GA', 'city' => 'Shiloh'],
    '31827' => ['state' => 'GA', 'city' => 'Talbotton'],
    '31829' => ['state' => 'GA', 'city' => 'Upatoi'],
    '31830' => ['state' => 'GA', 'city' => 'Warm Springs'],
    '31831' => ['state' => 'GA', 'city' => 'Waverly Hall'],
    '31832' => ['state' => 'GA', 'city' => 'Weston'],
    '31833' => ['state' => 'GA', 'city' => 'West Point'],
    '31836' => ['state' => 'GA', 'city' => 'Woodland'],
];
