<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '31901' => ['state' => 'GA', 'city' => 'Columbus'],
    '31902' => ['state' => 'GA', 'city' => 'Columbus'],
    '31903' => ['state' => 'GA', 'city' => 'Columbus'],
    '31904' => ['state' => 'GA', 'city' => 'Columbus'],
    '31905' => ['state' => 'GA', 'city' => 'Fort Benning'],
    '31906' => ['state' => 'GA', 'city' => 'Columbus'],
    '31907' => ['state' => 'GA', 'city' => 'Columbus'],
    '31908' => ['state' => 'GA', 'city' => 'Columbus'],
    '31909' => ['state' => 'GA', 'city' => 'Columbus'],
    '31914' => ['state' => 'GA', 'city' => 'Columbus'],
    '31917' => ['state' => 'GA', 'city' => 'Columbus'],
    '31993' => ['state' => 'GA', 'city' => 'Columbus'],
    '31995' => ['state' => 'GA', 'city' => 'Fort Benning'],
    '31997' => ['state' => 'GA', 'city' => 'Columbus'],
    '31998' => ['state' => 'GA', 'city' => 'Columbus'],
    '31999' => ['state' => 'GA', 'city' => 'Columbus'],
];
