<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '36901' => ['state' => 'AL', 'city' => 'Bellamy'],
    '36904' => ['state' => 'AL', 'city' => 'Butler'],
    '36907' => ['state' => 'AL', 'city' => 'Cuba'],
    '36908' => ['state' => 'AL', 'city' => 'Gilbertown'],
    '36910' => ['state' => 'AL', 'city' => 'Jachin'],
    '36912' => ['state' => 'AL', 'city' => 'Lisman'],
    '36913' => ['state' => 'AL', 'city' => 'Melvin'],
    '36915' => ['state' => 'AL', 'city' => 'Needham'],
    '36916' => ['state' => 'AL', 'city' => 'Pennington'],
    '36919' => ['state' => 'AL', 'city' => 'Silas'],
    '36921' => ['state' => 'AL', 'city' => 'Toxey'],
    '36922' => ['state' => 'AL', 'city' => 'Ward'],
    '36925' => ['state' => 'AL', 'city' => 'York'],
];
