<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '37501' => ['state' => 'TN', 'city' => 'Memphis'],
    '37544' => ['state' => 'TN', 'city' => 'Memphis'],
];
