<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '40601' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40602' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40603' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40604' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40618' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40619' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40620' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40621' => ['state' => 'KY', 'city' => 'Frankfort'],
    '40622' => ['state' => 'KY', 'city' => 'Frankfort'],
];
