<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '40701' => ['state' => 'KY', 'city' => 'Corbin'],
    '40702' => ['state' => 'KY', 'city' => 'Corbin'],
    '40724' => ['state' => 'KY', 'city' => 'Bush'],
    '40729' => ['state' => 'KY', 'city' => 'East Bernstadt'],
    '40730' => ['state' => 'KY', 'city' => 'Emlyn'],
    '40734' => ['state' => 'KY', 'city' => 'Gray'],
    '40737' => ['state' => 'KY', 'city' => 'Keavy'],
    '40740' => ['state' => 'KY', 'city' => 'Lily'],
    '40741' => ['state' => 'KY', 'city' => 'London'],
    '40742' => ['state' => 'KY', 'city' => 'London'],
    '40743' => ['state' => 'KY', 'city' => 'London'],
    '40744' => ['state' => 'KY', 'city' => 'London'],
    '40745' => ['state' => 'KY', 'city' => 'London'],
    '40750' => ['state' => 'KY', 'city' => 'London'],
    '40755' => ['state' => 'KY', 'city' => 'Pittsburg'],
    '40759' => ['state' => 'KY', 'city' => 'Rockholds'],
    '40763' => ['state' => 'KY', 'city' => 'Siler'],
    '40769' => ['state' => 'KY', 'city' => 'Williamsburg'],
    '40771' => ['state' => 'KY', 'city' => 'Woodbine'],
];
