<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '41301' => ['state' => 'KY', 'city' => 'Campton'],
    '41310' => ['state' => 'KY', 'city' => 'Bays'],
    '41311' => ['state' => 'KY', 'city' => 'Beattyville'],
    '41314' => ['state' => 'KY', 'city' => 'Booneville'],
    '41317' => ['state' => 'KY', 'city' => 'Clayhole'],
    '41332' => ['state' => 'KY', 'city' => 'Hazel Green'],
    '41339' => ['state' => 'KY', 'city' => 'Jackson'],
    '41347' => ['state' => 'KY', 'city' => 'Lone'],
    '41348' => ['state' => 'KY', 'city' => 'Lost Creek'],
    '41351' => ['state' => 'KY', 'city' => 'Mistletoe'],
    '41352' => ['state' => 'KY', 'city' => 'Mize'],
    '41360' => ['state' => 'KY', 'city' => 'Pine Ridge'],
    '41364' => ['state' => 'KY', 'city' => 'Ricetown'],
    '41365' => ['state' => 'KY', 'city' => 'Rogers'],
    '41366' => ['state' => 'KY', 'city' => 'Rousseau'],
    '41367' => ['state' => 'KY', 'city' => 'Rowdy'],
    '41368' => ['state' => 'KY', 'city' => 'Saint Helens'],
    '41385' => ['state' => 'KY', 'city' => 'Vancleve'],
    '41386' => ['state' => 'KY', 'city' => 'Vincent'],
    '41390' => ['state' => 'KY', 'city' => 'Whick'],
    '41397' => ['state' => 'KY', 'city' => 'Zoe'],
];
