<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '41408' => ['state' => 'KY', 'city' => 'Cannel City'],
    '41413' => ['state' => 'KY', 'city' => 'Crockett'],
    '41421' => ['state' => 'KY', 'city' => 'Elkfork'],
    '41425' => ['state' => 'KY', 'city' => 'Ezel'],
    '41426' => ['state' => 'KY', 'city' => 'Falcon'],
    '41451' => ['state' => 'KY', 'city' => 'Malone'],
    '41464' => ['state' => 'KY', 'city' => 'Royalton'],
    '41465' => ['state' => 'KY', 'city' => 'Salyersville'],
    '41472' => ['state' => 'KY', 'city' => 'West Liberty'],
    '41477' => ['state' => 'KY', 'city' => 'Wrigley'],
];
