<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '42501' => ['state' => 'KY', 'city' => 'Somerset'],
    '42502' => ['state' => 'KY', 'city' => 'Somerset'],
    '42503' => ['state' => 'KY', 'city' => 'Somerset'],
    '42516' => ['state' => 'KY', 'city' => 'Bethelridge'],
    '42518' => ['state' => 'KY', 'city' => 'Bronston'],
    '42519' => ['state' => 'KY', 'city' => 'Burnside'],
    '42528' => ['state' => 'KY', 'city' => 'Dunnville'],
    '42533' => ['state' => 'KY', 'city' => 'Ferguson'],
    '42539' => ['state' => 'KY', 'city' => 'Liberty'],
    '42541' => ['state' => 'KY', 'city' => 'Middleburg'],
    '42544' => ['state' => 'KY', 'city' => 'Nancy'],
    '42553' => ['state' => 'KY', 'city' => 'Science Hill'],
    '42558' => ['state' => 'KY', 'city' => 'Tateville'],
    '42564' => ['state' => 'KY', 'city' => 'West Somerset'],
    '42565' => ['state' => 'KY', 'city' => 'Windsor'],
    '42566' => ['state' => 'KY', 'city' => 'Yosemite'],
    '42567' => ['state' => 'KY', 'city' => 'Eubank'],
];
