<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '42602' => ['state' => 'KY', 'city' => 'Albany'],
    '42603' => ['state' => 'KY', 'city' => 'Alpha'],
    '42629' => ['state' => 'KY', 'city' => 'Jamestown'],
    '42631' => ['state' => 'KY', 'city' => 'Marshes Siding'],
    '42633' => ['state' => 'KY', 'city' => 'Monticello'],
    '42634' => ['state' => 'KY', 'city' => 'Parkers Lake'],
    '42635' => ['state' => 'KY', 'city' => 'Pine Knot'],
    '42638' => ['state' => 'KY', 'city' => 'Revelo'],
    '42642' => ['state' => 'KY', 'city' => 'Russell Springs'],
    '42647' => ['state' => 'KY', 'city' => 'Stearns'],
    '42649' => ['state' => 'KY', 'city' => 'Strunk'],
    '42653' => ['state' => 'KY', 'city' => 'Whitley City'],
];
