<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '43802' => ['state' => 'OH', 'city' => 'Adamsville'],
    '43803' => ['state' => 'OH', 'city' => 'Bakersville'],
    '43804' => ['state' => 'OH', 'city' => 'Baltic'],
    '43805' => ['state' => 'OH', 'city' => 'Blissfield'],
    '43811' => ['state' => 'OH', 'city' => 'Conesville'],
    '43812' => ['state' => 'OH', 'city' => 'Coshocton'],
    '43821' => ['state' => 'OH', 'city' => 'Dresden'],
    '43822' => ['state' => 'OH', 'city' => 'Frazeysburg'],
    '43824' => ['state' => 'OH', 'city' => 'Fresno'],
    '43828' => ['state' => 'OH', 'city' => 'Keene'],
    '43830' => ['state' => 'OH', 'city' => 'Nashport'],
    '43832' => ['state' => 'OH', 'city' => 'Newcomerstown'],
    '43836' => ['state' => 'OH', 'city' => 'Plainfield'],
    '43837' => ['state' => 'OH', 'city' => 'Port Washington'],
    '43840' => ['state' => 'OH', 'city' => 'Stone Creek'],
    '43842' => ['state' => 'OH', 'city' => 'Trinway'],
    '43843' => ['state' => 'OH', 'city' => 'Walhonding'],
    '43844' => ['state' => 'OH', 'city' => 'Warsaw'],
    '43845' => ['state' => 'OH', 'city' => 'West Lafayette'],
];
