<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '44301' => ['state' => 'OH', 'city' => 'Akron'],
    '44302' => ['state' => 'OH', 'city' => 'Akron'],
    '44303' => ['state' => 'OH', 'city' => 'Akron'],
    '44304' => ['state' => 'OH', 'city' => 'Akron'],
    '44305' => ['state' => 'OH', 'city' => 'Akron'],
    '44306' => ['state' => 'OH', 'city' => 'Akron'],
    '44307' => ['state' => 'OH', 'city' => 'Akron'],
    '44308' => ['state' => 'OH', 'city' => 'Akron'],
    '44309' => ['state' => 'OH', 'city' => 'Akron'],
    '44310' => ['state' => 'OH', 'city' => 'Akron'],
    '44311' => ['state' => 'OH', 'city' => 'Akron'],
    '44312' => ['state' => 'OH', 'city' => 'Akron'],
    '44313' => ['state' => 'OH', 'city' => 'Akron'],
    '44314' => ['state' => 'OH', 'city' => 'Akron'],
    '44315' => ['state' => 'OH', 'city' => 'Akron'],
    '44316' => ['state' => 'OH', 'city' => 'Akron'],
    '44317' => ['state' => 'OH', 'city' => 'Akron'],
    '44319' => ['state' => 'OH', 'city' => 'Akron'],
    '44320' => ['state' => 'OH', 'city' => 'Akron'],
    '44321' => ['state' => 'OH', 'city' => 'Akron'],
    '44325' => ['state' => 'OH', 'city' => 'Akron'],
    '44326' => ['state' => 'OH', 'city' => 'Akron'],
    '44328' => ['state' => 'OH', 'city' => 'Akron'],
    '44333' => ['state' => 'OH', 'city' => 'Akron'],
    '44334' => ['state' => 'OH', 'city' => 'Fairlawn'],
    '44372' => ['state' => 'OH', 'city' => 'Akron'],
    '44396' => ['state' => 'OH', 'city' => 'Akron'],
    '44398' => ['state' => 'OH', 'city' => 'Akron'],
];
