<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '44701' => ['state' => 'OH', 'city' => 'Canton'],
    '44702' => ['state' => 'OH', 'city' => 'Canton'],
    '44703' => ['state' => 'OH', 'city' => 'Canton'],
    '44704' => ['state' => 'OH', 'city' => 'Canton'],
    '44705' => ['state' => 'OH', 'city' => 'Canton'],
    '44706' => ['state' => 'OH', 'city' => 'Canton'],
    '44707' => ['state' => 'OH', 'city' => 'Canton'],
    '44708' => ['state' => 'OH', 'city' => 'Canton'],
    '44709' => ['state' => 'OH', 'city' => 'Canton'],
    '44710' => ['state' => 'OH', 'city' => 'Canton'],
    '44711' => ['state' => 'OH', 'city' => 'Canton'],
    '44714' => ['state' => 'OH', 'city' => 'Canton'],
    '44718' => ['state' => 'OH', 'city' => 'Canton'],
    '44720' => ['state' => 'OH', 'city' => 'North Canton'],
    '44721' => ['state' => 'OH', 'city' => 'Canton'],
    '44730' => ['state' => 'OH', 'city' => 'East Canton'],
    '44735' => ['state' => 'OH', 'city' => 'Canton'],
    '44750' => ['state' => 'OH', 'city' => 'Canton'],
    '44767' => ['state' => 'OH', 'city' => 'Canton'],
    '44799' => ['state' => 'OH', 'city' => 'Canton'],
];
