<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '44901' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44902' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44903' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44904' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44905' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44906' => ['state' => 'OH', 'city' => 'Mansfield'],
    '44907' => ['state' => 'OH', 'city' => 'Mansfield'],
];
