<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '46401' => ['state' => 'IN', 'city' => 'Gary'],
    '46402' => ['state' => 'IN', 'city' => 'Gary'],
    '46403' => ['state' => 'IN', 'city' => 'Gary'],
    '46404' => ['state' => 'IN', 'city' => 'Gary'],
    '46405' => ['state' => 'IN', 'city' => 'Lake Station'],
    '46406' => ['state' => 'IN', 'city' => 'Gary'],
    '46407' => ['state' => 'IN', 'city' => 'Gary'],
    '46408' => ['state' => 'IN', 'city' => 'Gary'],
    '46409' => ['state' => 'IN', 'city' => 'Gary'],
    '46410' => ['state' => 'IN', 'city' => 'Merrillville'],
    '46411' => ['state' => 'IN', 'city' => 'Merrillville'],
];
