<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '49101' => ['state' => 'MI', 'city' => 'Baroda'],
    '49102' => ['state' => 'MI', 'city' => 'Berrien Center'],
    '49103' => ['state' => 'MI', 'city' => 'Berrien Springs'],
    '49104' => ['state' => 'MI', 'city' => 'Berrien Springs'],
    '49106' => ['state' => 'MI', 'city' => 'Bridgman'],
    '49107' => ['state' => 'MI', 'city' => 'Buchanan'],
    '49111' => ['state' => 'MI', 'city' => 'Eau Claire'],
    '49112' => ['state' => 'MI', 'city' => 'Edwardsburg'],
    '49113' => ['state' => 'MI', 'city' => 'Galien'],
    '49115' => ['state' => 'MI', 'city' => 'Harbert'],
    '49116' => ['state' => 'MI', 'city' => 'Lakeside'],
    '49117' => ['state' => 'MI', 'city' => 'New Buffalo'],
    '49119' => ['state' => 'MI', 'city' => 'New Troy'],
    '49120' => ['state' => 'MI', 'city' => 'Niles'],
    '49125' => ['state' => 'MI', 'city' => 'Sawyer'],
    '49126' => ['state' => 'MI', 'city' => 'Sodus'],
    '49127' => ['state' => 'MI', 'city' => 'Stevensville'],
    '49128' => ['state' => 'MI', 'city' => 'Three Oaks'],
    '49129' => ['state' => 'MI', 'city' => 'Union Pier'],
    '49130' => ['state' => 'MI', 'city' => 'Union'],
];
