<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '50801' => ['state' => 'IA', 'city' => 'Creston'],
    '50830' => ['state' => 'IA', 'city' => 'Afton'],
    '50831' => ['state' => 'IA', 'city' => 'Arispe'],
    '50833' => ['state' => 'IA', 'city' => 'Bedford'],
    '50835' => ['state' => 'IA', 'city' => 'Benton'],
    '50836' => ['state' => 'IA', 'city' => 'Blockton'],
    '50837' => ['state' => 'IA', 'city' => 'Bridgewater'],
    '50839' => ['state' => 'IA', 'city' => 'Carbon'],
    '50840' => ['state' => 'IA', 'city' => 'Clearfield'],
    '50841' => ['state' => 'IA', 'city' => 'Corning'],
    '50842' => ['state' => 'IA', 'city' => 'Cromwell'],
    '50843' => ['state' => 'IA', 'city' => 'Cumberland'],
    '50845' => ['state' => 'IA', 'city' => 'Diagonal'],
    '50846' => ['state' => 'IA', 'city' => 'Fontanelle'],
    '50847' => ['state' => 'IA', 'city' => 'Grant'],
    '50848' => ['state' => 'IA', 'city' => 'Gravity'],
    '50849' => ['state' => 'IA', 'city' => 'Greenfield'],
    '50851' => ['state' => 'IA', 'city' => 'Lenox'],
    '50853' => ['state' => 'IA', 'city' => 'Massena'],
    '50854' => ['state' => 'IA', 'city' => 'Mount Ayr'],
    '50857' => ['state' => 'IA', 'city' => 'Nodaway'],
    '50858' => ['state' => 'IA', 'city' => 'Orient'],
    '50859' => ['state' => 'IA', 'city' => 'Prescott'],
    '50860' => ['state' => 'IA', 'city' => 'Redding'],
    '50861' => ['state' => 'IA', 'city' => 'Shannon City'],
    '50862' => ['state' => 'IA', 'city' => 'Sharpsburg'],
    '50863' => ['state' => 'IA', 'city' => 'Tingley'],
    '50864' => ['state' => 'IA', 'city' => 'Villisca'],
];
