<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '51201' => ['state' => 'IA', 'city' => 'Sheldon'],
    '51230' => ['state' => 'IA', 'city' => 'Alvord'],
    '51231' => ['state' => 'IA', 'city' => 'Archer'],
    '51232' => ['state' => 'IA', 'city' => 'Ashton'],
    '51234' => ['state' => 'IA', 'city' => 'Boyden'],
    '51235' => ['state' => 'IA', 'city' => 'Doon'],
    '51237' => ['state' => 'IA', 'city' => 'George'],
    '51238' => ['state' => 'IA', 'city' => 'Hospers'],
    '51239' => ['state' => 'IA', 'city' => 'Hull'],
    '51240' => ['state' => 'IA', 'city' => 'Inwood'],
    '51241' => ['state' => 'IA', 'city' => 'Larchwood'],
    '51242' => ['state' => 'IA', 'city' => 'Lester'],
    '51243' => ['state' => 'IA', 'city' => 'Little Rock'],
    '51244' => ['state' => 'IA', 'city' => 'Matlock'],
    '51245' => ['state' => 'IA', 'city' => 'Primghar'],
    '51246' => ['state' => 'IA', 'city' => 'Rock Rapids'],
    '51247' => ['state' => 'IA', 'city' => 'Rock Valley'],
    '51248' => ['state' => 'IA', 'city' => 'Sanborn'],
    '51249' => ['state' => 'IA', 'city' => 'Sibley'],
    '51250' => ['state' => 'IA', 'city' => 'Sioux Center'],
];
