<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '51301' => ['state' => 'IA', 'city' => 'Spencer'],
    '51331' => ['state' => 'IA', 'city' => 'Arnolds Park'],
    '51333' => ['state' => 'IA', 'city' => 'Dickens'],
    '51334' => ['state' => 'IA', 'city' => 'Estherville'],
    '51338' => ['state' => 'IA', 'city' => 'Everly'],
    '51340' => ['state' => 'IA', 'city' => 'Fostoria'],
    '51341' => ['state' => 'IA', 'city' => 'Gillett Grove'],
    '51342' => ['state' => 'IA', 'city' => 'Graettinger'],
    '51343' => ['state' => 'IA', 'city' => 'Greenville'],
    '51345' => ['state' => 'IA', 'city' => 'Harris'],
    '51346' => ['state' => 'IA', 'city' => 'Hartley'],
    '51347' => ['state' => 'IA', 'city' => 'Lake Park'],
    '51350' => ['state' => 'IA', 'city' => 'Melvin'],
    '51351' => ['state' => 'IA', 'city' => 'Milford'],
    '51354' => ['state' => 'IA', 'city' => 'Ocheyedan'],
    '51355' => ['state' => 'IA', 'city' => 'Okoboji'],
    '51357' => ['state' => 'IA', 'city' => 'Royal'],
    '51358' => ['state' => 'IA', 'city' => 'Ruthven'],
    '51360' => ['state' => 'IA', 'city' => 'Spirit Lake'],
    '51363' => ['state' => 'IA', 'city' => 'Superior'],
    '51364' => ['state' => 'IA', 'city' => 'Terril'],
    '51365' => ['state' => 'IA', 'city' => 'Wallingford'],
    '51366' => ['state' => 'IA', 'city' => 'Webb'],
];
