<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '51601' => ['state' => 'IA', 'city' => 'Shenandoah'],
    '51603' => ['state' => 'IA', 'city' => 'Shenandoah'],
    '51630' => ['state' => 'IA', 'city' => 'Blanchard'],
    '51631' => ['state' => 'IA', 'city' => 'Braddyville'],
    '51632' => ['state' => 'IA', 'city' => 'Clarinda'],
    '51636' => ['state' => 'IA', 'city' => 'Coin'],
    '51637' => ['state' => 'IA', 'city' => 'College Springs'],
    '51638' => ['state' => 'IA', 'city' => 'Essex'],
    '51639' => ['state' => 'IA', 'city' => 'Farragut'],
    '51640' => ['state' => 'IA', 'city' => 'Hamburg'],
    '51645' => ['state' => 'IA', 'city' => 'Imogene'],
    '51646' => ['state' => 'IA', 'city' => 'New Market'],
    '51647' => ['state' => 'IA', 'city' => 'Northboro'],
    '51648' => ['state' => 'IA', 'city' => 'Percival'],
    '51649' => ['state' => 'IA', 'city' => 'Randolph'],
    '51650' => ['state' => 'IA', 'city' => 'Riverton'],
    '51651' => ['state' => 'IA', 'city' => 'Shambaugh'],
    '51652' => ['state' => 'IA', 'city' => 'Sidney'],
    '51653' => ['state' => 'IA', 'city' => 'Tabor'],
    '51654' => ['state' => 'IA', 'city' => 'Thurman'],
    '51656' => ['state' => 'IA', 'city' => 'Yorktown'],
];
