<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '52801' => ['state' => 'IA', 'city' => 'Davenport'],
    '52802' => ['state' => 'IA', 'city' => 'Davenport'],
    '52803' => ['state' => 'IA', 'city' => 'Davenport'],
    '52804' => ['state' => 'IA', 'city' => 'Davenport'],
    '52805' => ['state' => 'IA', 'city' => 'Davenport'],
    '52806' => ['state' => 'IA', 'city' => 'Davenport'],
    '52807' => ['state' => 'IA', 'city' => 'Davenport'],
    '52808' => ['state' => 'IA', 'city' => 'Davenport'],
    '52809' => ['state' => 'IA', 'city' => 'Davenport'],
];
