<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '53801' => ['state' => 'WI', 'city' => 'Bagley'],
    '53802' => ['state' => 'WI', 'city' => 'Beetown'],
    '53803' => ['state' => 'WI', 'city' => 'Benton'],
    '53804' => ['state' => 'WI', 'city' => 'Bloomington'],
    '53805' => ['state' => 'WI', 'city' => 'Boscobel'],
    '53806' => ['state' => 'WI', 'city' => 'Cassville'],
    '53807' => ['state' => 'WI', 'city' => 'Cuba City'],
    '53808' => ['state' => 'WI', 'city' => 'Dickeyville'],
    '53809' => ['state' => 'WI', 'city' => 'Fennimore'],
    '53810' => ['state' => 'WI', 'city' => 'Glen Haven'],
    '53811' => ['state' => 'WI', 'city' => 'Hazel Green'],
    '53812' => ['state' => 'WI', 'city' => 'Kieler'],
    '53813' => ['state' => 'WI', 'city' => 'Lancaster'],
    '53816' => ['state' => 'WI', 'city' => 'Mount Hope'],
    '53817' => ['state' => 'WI', 'city' => 'Patch Grove'],
    '53818' => ['state' => 'WI', 'city' => 'Platteville'],
    '53820' => ['state' => 'WI', 'city' => 'Potosi'],
    '53821' => ['state' => 'WI', 'city' => 'Prairie Du Chien'],
    '53824' => ['state' => 'WI', 'city' => 'Sinsinawa'],
    '53825' => ['state' => 'WI', 'city' => 'Stitzer'],
    '53826' => ['state' => 'WI', 'city' => 'Wauzeka'],
    '53827' => ['state' => 'WI', 'city' => 'Woodman'],
];
