<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '54001' => ['state' => 'WI', 'city' => 'Amery'],
    '54002' => ['state' => 'WI', 'city' => 'Baldwin'],
    '54003' => ['state' => 'WI', 'city' => 'Beldenville'],
    '54004' => ['state' => 'WI', 'city' => 'Clayton'],
    '54005' => ['state' => 'WI', 'city' => 'Clear Lake'],
    '54006' => ['state' => 'WI', 'city' => 'Cushing'],
    '54007' => ['state' => 'WI', 'city' => 'Deer Park'],
    '54009' => ['state' => 'WI', 'city' => 'Dresser'],
    '54010' => ['state' => 'WI', 'city' => 'East Ellsworth'],
    '54011' => ['state' => 'WI', 'city' => 'Ellsworth'],
    '54013' => ['state' => 'WI', 'city' => 'Glenwood City'],
    '54014' => ['state' => 'WI', 'city' => 'Hager City'],
    '54015' => ['state' => 'WI', 'city' => 'Hammond'],
    '54016' => ['state' => 'WI', 'city' => 'Hudson'],
    '54017' => ['state' => 'WI', 'city' => 'New Richmond'],
    '54020' => ['state' => 'WI', 'city' => 'Osceola'],
    '54021' => ['state' => 'WI', 'city' => 'Prescott'],
    '54022' => ['state' => 'WI', 'city' => 'River Falls'],
    '54023' => ['state' => 'WI', 'city' => 'Roberts'],
    '54024' => ['state' => 'WI', 'city' => 'Saint Croix Falls'],
    '54025' => ['state' => 'WI', 'city' => 'Somerset'],
    '54026' => ['state' => 'WI', 'city' => 'Star Prairie'],
    '54027' => ['state' => 'WI', 'city' => 'Wilson'],
    '54028' => ['state' => 'WI', 'city' => 'Woodville'],
    '54082' => ['state' => 'WI', 'city' => 'Houlton'],
];
