<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '54301' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54302' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54303' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54304' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54305' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54306' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54307' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54308' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54311' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54313' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54324' => ['state' => 'WI', 'city' => 'Green Bay'],
    '54344' => ['state' => 'WI', 'city' => 'Green Bay'],
];
