<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '55550' => ['state' => 'MN', 'city' => 'Young America'],
    '55551' => ['state' => 'MN', 'city' => 'Young America'],
    '55553' => ['state' => 'MN', 'city' => 'Young America'],
    '55554' => ['state' => 'MN', 'city' => 'Norwood'],
    '55558' => ['state' => 'MN', 'city' => 'Young America'],
    '55568' => ['state' => 'MN', 'city' => 'Young America'],
    '55569' => ['state' => 'MN', 'city' => 'Osseo'],
    '55570' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55571' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55572' => ['state' => 'MN', 'city' => 'Rockford'],
    '55573' => ['state' => 'MN', 'city' => 'Young America'],
    '55574' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55575' => ['state' => 'MN', 'city' => 'Howard Lake'],
    '55576' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55577' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55578' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55579' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55583' => ['state' => 'MN', 'city' => 'Norwood'],
    '55592' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55593' => ['state' => 'MN', 'city' => 'Maple Plain'],
    '55594' => ['state' => 'MN', 'city' => 'Young America'],
    '55595' => ['state' => 'MN', 'city' => 'Loretto'],
    '55596' => ['state' => 'MN', 'city' => 'Loretto'],
    '55597' => ['state' => 'MN', 'city' => 'Loretto'],
    '55598' => ['state' => 'MN', 'city' => 'Loretto'],
    '55599' => ['state' => 'MN', 'city' => 'Loretto'],
];
