<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '55601' => ['state' => 'MN', 'city' => 'Beaver Bay'],
    '55602' => ['state' => 'MN', 'city' => 'Brimson'],
    '55603' => ['state' => 'MN', 'city' => 'Finland'],
    '55604' => ['state' => 'MN', 'city' => 'Grand Marais'],
    '55605' => ['state' => 'MN', 'city' => 'Grand Portage'],
    '55606' => ['state' => 'MN', 'city' => 'Hovland'],
    '55607' => ['state' => 'MN', 'city' => 'Isabella'],
    '55609' => ['state' => 'MN', 'city' => 'Knife River'],
    '55612' => ['state' => 'MN', 'city' => 'Lutsen'],
    '55613' => ['state' => 'MN', 'city' => 'Schroeder'],
    '55614' => ['state' => 'MN', 'city' => 'Silver Bay'],
    '55615' => ['state' => 'MN', 'city' => 'Tofte'],
    '55616' => ['state' => 'MN', 'city' => 'Two Harbors'],
];
