<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '55801' => ['state' => 'MN', 'city' => 'Duluth'],
    '55802' => ['state' => 'MN', 'city' => 'Duluth'],
    '55803' => ['state' => 'MN', 'city' => 'Duluth'],
    '55804' => ['state' => 'MN', 'city' => 'Duluth'],
    '55805' => ['state' => 'MN', 'city' => 'Duluth'],
    '55806' => ['state' => 'MN', 'city' => 'Duluth'],
    '55807' => ['state' => 'MN', 'city' => 'Duluth'],
    '55808' => ['state' => 'MN', 'city' => 'Duluth'],
    '55810' => ['state' => 'MN', 'city' => 'Duluth'],
    '55811' => ['state' => 'MN', 'city' => 'Duluth'],
    '55812' => ['state' => 'MN', 'city' => 'Duluth'],
    '55814' => ['state' => 'MN', 'city' => 'Duluth'],
    '55815' => ['state' => 'MN', 'city' => 'Duluth'],
    '55816' => ['state' => 'MN', 'city' => 'Duluth'],
];
