<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '58801' => ['state' => 'ND', 'city' => 'Williston'],
    '58802' => ['state' => 'ND', 'city' => 'Williston'],
    '58803' => ['state' => 'ND', 'city' => 'Williston'],
    '58830' => ['state' => 'ND', 'city' => 'Alamo'],
    '58831' => ['state' => 'ND', 'city' => 'Alexander'],
    '58833' => ['state' => 'ND', 'city' => 'Ambrose'],
    '58835' => ['state' => 'ND', 'city' => 'Arnegard'],
    '58838' => ['state' => 'ND', 'city' => 'Cartwright'],
    '58843' => ['state' => 'ND', 'city' => 'Epping'],
    '58844' => ['state' => 'ND', 'city' => 'Fortuna'],
    '58845' => ['state' => 'ND', 'city' => 'Grenora'],
    '58847' => ['state' => 'ND', 'city' => 'Keene'],
    '58849' => ['state' => 'ND', 'city' => 'Ray'],
    '58852' => ['state' => 'ND', 'city' => 'Tioga'],
    '58853' => ['state' => 'ND', 'city' => 'Trenton'],
    '58854' => ['state' => 'ND', 'city' => 'Watford City'],
    '58856' => ['state' => 'ND', 'city' => 'Zahl'],
];
