<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '59501' => ['state' => 'MT', 'city' => 'Havre'],
    '59520' => ['state' => 'MT', 'city' => 'Big Sandy'],
    '59521' => ['state' => 'MT', 'city' => 'Box Elder'],
    '59522' => ['state' => 'MT', 'city' => 'Chester'],
    '59523' => ['state' => 'MT', 'city' => 'Chinook'],
    '59524' => ['state' => 'MT', 'city' => 'Dodson'],
    '59525' => ['state' => 'MT', 'city' => 'Gildford'],
    '59526' => ['state' => 'MT', 'city' => 'Harlem'],
    '59527' => ['state' => 'MT', 'city' => 'Hays'],
    '59528' => ['state' => 'MT', 'city' => 'Hingham'],
    '59529' => ['state' => 'MT', 'city' => 'Hogeland'],
    '59530' => ['state' => 'MT', 'city' => 'Inverness'],
    '59531' => ['state' => 'MT', 'city' => 'Joplin'],
    '59532' => ['state' => 'MT', 'city' => 'Kremlin'],
    '59535' => ['state' => 'MT', 'city' => 'Lloyd'],
    '59537' => ['state' => 'MT', 'city' => 'Loring'],
    '59538' => ['state' => 'MT', 'city' => 'Malta'],
    '59540' => ['state' => 'MT', 'city' => 'Rudyard'],
    '59542' => ['state' => 'MT', 'city' => 'Turner'],
    '59544' => ['state' => 'MT', 'city' => 'Whitewater'],
    '59545' => ['state' => 'MT', 'city' => 'Whitlash'],
    '59546' => ['state' => 'MT', 'city' => 'Zortman'],
    '59547' => ['state' => 'MT', 'city' => 'Zurich'],
];
