<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '59601' => ['state' => 'MT', 'city' => 'Helena'],
    '59602' => ['state' => 'MT', 'city' => 'Helena'],
    '59604' => ['state' => 'MT', 'city' => 'Helena'],
    '59620' => ['state' => 'MT', 'city' => 'Helena'],
    '59623' => ['state' => 'MT', 'city' => 'Helena'],
    '59624' => ['state' => 'MT', 'city' => 'Helena'],
    '59625' => ['state' => 'MT', 'city' => 'Helena'],
    '59626' => ['state' => 'MT', 'city' => 'Helena'],
    '59631' => ['state' => 'MT', 'city' => 'Basin'],
    '59632' => ['state' => 'MT', 'city' => 'Boulder'],
    '59633' => ['state' => 'MT', 'city' => 'Canyon Creek'],
    '59634' => ['state' => 'MT', 'city' => 'Clancy'],
    '59635' => ['state' => 'MT', 'city' => 'East Helena'],
    '59636' => ['state' => 'MT', 'city' => 'Fort Harrison'],
    '59638' => ['state' => 'MT', 'city' => 'Jefferson City'],
    '59639' => ['state' => 'MT', 'city' => 'Lincoln'],
    '59640' => ['state' => 'MT', 'city' => 'Marysville'],
    '59641' => ['state' => 'MT', 'city' => 'Radersburg'],
    '59642' => ['state' => 'MT', 'city' => 'Ringling'],
    '59643' => ['state' => 'MT', 'city' => 'Toston'],
    '59644' => ['state' => 'MT', 'city' => 'Townsend'],
    '59645' => ['state' => 'MT', 'city' => 'White Sulphur Springs'],
    '59647' => ['state' => 'MT', 'city' => 'Winston'],
    '59648' => ['state' => 'MT', 'city' => 'Wolf Creek'],
];
