<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '60201' => ['state' => 'IL', 'city' => 'Evanston'],
    '60202' => ['state' => 'IL', 'city' => 'Evanston'],
    '60203' => ['state' => 'IL', 'city' => 'Evanston'],
    '60204' => ['state' => 'IL', 'city' => 'Evanston'],
    '60208' => ['state' => 'IL', 'city' => 'Evanston'],
    '60209' => ['state' => 'IL', 'city' => 'Evanston'],
];
