<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '60301' => ['state' => 'IL', 'city' => 'Oak Park'],
    '60302' => ['state' => 'IL', 'city' => 'Oak Park'],
    '60303' => ['state' => 'IL', 'city' => 'Oak Park'],
    '60304' => ['state' => 'IL', 'city' => 'Oak Park'],
    '60305' => ['state' => 'IL', 'city' => 'River Forest'],
    '60399' => ['state' => 'IL', 'city' => 'Wood Dale'],
];
