<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '60701' => ['state' => 'IL', 'city' => 'Chicago'],
    '60706' => ['state' => 'IL', 'city' => 'Harwood Heights'],
    '60707' => ['state' => 'IL', 'city' => 'Elmwood Park'],
    '60712' => ['state' => 'IL', 'city' => 'Lincolnwood'],
    '60714' => ['state' => 'IL', 'city' => 'Niles'],
];
