<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '60803' => ['state' => 'IL', 'city' => 'Alsip'],
    '60804' => ['state' => 'IL', 'city' => 'Cicero'],
    '60805' => ['state' => 'IL', 'city' => 'Evergreen Park'],
    '60827' => ['state' => 'IL', 'city' => 'Riverdale'],
];
