<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '61101' => ['state' => 'IL', 'city' => 'Rockford'],
    '61102' => ['state' => 'IL', 'city' => 'Rockford'],
    '61103' => ['state' => 'IL', 'city' => 'Rockford'],
    '61104' => ['state' => 'IL', 'city' => 'Rockford'],
    '61105' => ['state' => 'IL', 'city' => 'Rockford'],
    '61106' => ['state' => 'IL', 'city' => 'Rockford'],
    '61107' => ['state' => 'IL', 'city' => 'Rockford'],
    '61108' => ['state' => 'IL', 'city' => 'Rockford'],
    '61109' => ['state' => 'IL', 'city' => 'Rockford'],
    '61110' => ['state' => 'IL', 'city' => 'Rockford'],
    '61111' => ['state' => 'IL', 'city' => 'Loves Park'],
    '61112' => ['state' => 'IL', 'city' => 'Rockford'],
    '61114' => ['state' => 'IL', 'city' => 'Rockford'],
    '61115' => ['state' => 'IL', 'city' => 'Machesney Park'],
    '61125' => ['state' => 'IL', 'city' => 'Rockford'],
    '61126' => ['state' => 'IL', 'city' => 'Rockford'],
    '61130' => ['state' => 'IL', 'city' => 'Loves Park'],
    '61131' => ['state' => 'IL', 'city' => 'Loves Park'],
    '61132' => ['state' => 'IL', 'city' => 'Loves Park'],
];
