<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '65101' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65102' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65103' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65104' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65105' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65106' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65107' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65108' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65109' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65110' => ['state' => 'MO', 'city' => 'Jefferson City'],
    '65111' => ['state' => 'MO', 'city' => 'Jefferson City'],
];
