<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '67301' => ['state' => 'KS', 'city' => 'Independence'],
    '67330' => ['state' => 'KS', 'city' => 'Altamont'],
    '67332' => ['state' => 'KS', 'city' => 'Bartlett'],
    '67333' => ['state' => 'KS', 'city' => 'Caney'],
    '67334' => ['state' => 'KS', 'city' => 'Chautauqua'],
    '67335' => ['state' => 'KS', 'city' => 'Cherryvale'],
    '67336' => ['state' => 'KS', 'city' => 'Chetopa'],
    '67337' => ['state' => 'KS', 'city' => 'Coffeyville'],
    '67340' => ['state' => 'KS', 'city' => 'Dearing'],
    '67341' => ['state' => 'KS', 'city' => 'Dennis'],
    '67342' => ['state' => 'KS', 'city' => 'Edna'],
    '67344' => ['state' => 'KS', 'city' => 'Elk City'],
    '67345' => ['state' => 'KS', 'city' => 'Elk Falls'],
    '67346' => ['state' => 'KS', 'city' => 'Grenola'],
    '67347' => ['state' => 'KS', 'city' => 'Havana'],
    '67349' => ['state' => 'KS', 'city' => 'Howard'],
    '67351' => ['state' => 'KS', 'city' => 'Liberty'],
    '67352' => ['state' => 'KS', 'city' => 'Longton'],
    '67353' => ['state' => 'KS', 'city' => 'Moline'],
    '67354' => ['state' => 'KS', 'city' => 'Mound Valley'],
    '67355' => ['state' => 'KS', 'city' => 'Niotaze'],
    '67356' => ['state' => 'KS', 'city' => 'Oswego'],
    '67357' => ['state' => 'KS', 'city' => 'Parsons'],
    '67360' => ['state' => 'KS', 'city' => 'Peru'],
    '67361' => ['state' => 'KS', 'city' => 'Sedan'],
    '67363' => ['state' => 'KS', 'city' => 'Sycamore'],
    '67364' => ['state' => 'KS', 'city' => 'Tyro'],
];
