<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '67701' => ['state' => 'KS', 'city' => 'Colby'],
    '67730' => ['state' => 'KS', 'city' => 'Atwood'],
    '67731' => ['state' => 'KS', 'city' => 'Bird City'],
    '67732' => ['state' => 'KS', 'city' => 'Brewster'],
    '67733' => ['state' => 'KS', 'city' => 'Edson'],
    '67734' => ['state' => 'KS', 'city' => 'Gem'],
    '67735' => ['state' => 'KS', 'city' => 'Goodland'],
    '67736' => ['state' => 'KS', 'city' => 'Gove'],
    '67737' => ['state' => 'KS', 'city' => 'Grainfield'],
    '67738' => ['state' => 'KS', 'city' => 'Grinnell'],
    '67739' => ['state' => 'KS', 'city' => 'Herndon'],
    '67740' => ['state' => 'KS', 'city' => 'Hoxie'],
    '67741' => ['state' => 'KS', 'city' => 'Kanorado'],
    '67743' => ['state' => 'KS', 'city' => 'Levant'],
    '67744' => ['state' => 'KS', 'city' => 'Ludell'],
    '67745' => ['state' => 'KS', 'city' => 'Mc Donald'],
    '67747' => ['state' => 'KS', 'city' => 'Monument'],
    '67748' => ['state' => 'KS', 'city' => 'Oakley'],
    '67749' => ['state' => 'KS', 'city' => 'Oberlin'],
    '67751' => ['state' => 'KS', 'city' => 'Park'],
    '67752' => ['state' => 'KS', 'city' => 'Quinter'],
    '67753' => ['state' => 'KS', 'city' => 'Rexford'],
    '67756' => ['state' => 'KS', 'city' => 'Saint Francis'],
    '67757' => ['state' => 'KS', 'city' => 'Selden'],
    '67758' => ['state' => 'KS', 'city' => 'Sharon Springs'],
    '67761' => ['state' => 'KS', 'city' => 'Wallace'],
    '67762' => ['state' => 'KS', 'city' => 'Weskan'],
    '67764' => ['state' => 'KS', 'city' => 'Winona'],
];
