<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '67901' => ['state' => 'KS', 'city' => 'Liberal'],
    '67905' => ['state' => 'KS', 'city' => 'Liberal'],
    '67950' => ['state' => 'KS', 'city' => 'Elkhart'],
    '67951' => ['state' => 'KS', 'city' => 'Hugoton'],
    '67952' => ['state' => 'KS', 'city' => 'Moscow'],
    '67953' => ['state' => 'KS', 'city' => 'Richfield'],
    '67954' => ['state' => 'KS', 'city' => 'Rolla'],
];
