<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '69001' => ['state' => 'NE', 'city' => 'Mc Cook'],
    '69020' => ['state' => 'NE', 'city' => 'Bartley'],
    '69021' => ['state' => 'NE', 'city' => 'Benkelman'],
    '69022' => ['state' => 'NE', 'city' => 'Cambridge'],
    '69023' => ['state' => 'NE', 'city' => 'Champion'],
    '69024' => ['state' => 'NE', 'city' => 'Culbertson'],
    '69025' => ['state' => 'NE', 'city' => 'Curtis'],
    '69026' => ['state' => 'NE', 'city' => 'Danbury'],
    '69027' => ['state' => 'NE', 'city' => 'Enders'],
    '69028' => ['state' => 'NE', 'city' => 'Eustis'],
    '69029' => ['state' => 'NE', 'city' => 'Farnam'],
    '69030' => ['state' => 'NE', 'city' => 'Haigler'],
    '69032' => ['state' => 'NE', 'city' => 'Hayes Center'],
    '69033' => ['state' => 'NE', 'city' => 'Imperial'],
    '69034' => ['state' => 'NE', 'city' => 'Indianola'],
    '69036' => ['state' => 'NE', 'city' => 'Lebanon'],
    '69037' => ['state' => 'NE', 'city' => 'Max'],
    '69038' => ['state' => 'NE', 'city' => 'Maywood'],
    '69039' => ['state' => 'NE', 'city' => 'Moorefield'],
    '69040' => ['state' => 'NE', 'city' => 'Palisade'],
    '69041' => ['state' => 'NE', 'city' => 'Parks'],
    '69042' => ['state' => 'NE', 'city' => 'Stockville'],
    '69043' => ['state' => 'NE', 'city' => 'Stratton'],
    '69044' => ['state' => 'NE', 'city' => 'Trenton'],
    '69045' => ['state' => 'NE', 'city' => 'Wauneta'],
    '69046' => ['state' => 'NE', 'city' => 'Wilsonville'],
];
