<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '69201' => ['state' => 'NE', 'city' => 'Valentine'],
    '69210' => ['state' => 'NE', 'city' => 'Ainsworth'],
    '69211' => ['state' => 'NE', 'city' => 'Cody'],
    '69212' => ['state' => 'NE', 'city' => 'Crookston'],
    '69214' => ['state' => 'NE', 'city' => 'Johnstown'],
    '69216' => ['state' => 'NE', 'city' => 'Kilgore'],
    '69217' => ['state' => 'NE', 'city' => 'Long Pine'],
    '69218' => ['state' => 'NE', 'city' => 'Merriman'],
    '69219' => ['state' => 'NE', 'city' => 'Nenzel'],
    '69220' => ['state' => 'NE', 'city' => 'Sparks'],
    '69221' => ['state' => 'NE', 'city' => 'Wood Lake'],
];
