<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '73301' => ['state' => 'TX', 'city' => 'Austin'],
    '73344' => ['state' => 'TX', 'city' => 'Austin'],
];
