<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '73801' => ['state' => 'OK', 'city' => 'Woodward'],
    '73802' => ['state' => 'OK', 'city' => 'Woodward'],
    '73832' => ['state' => 'OK', 'city' => 'Arnett'],
    '73834' => ['state' => 'OK', 'city' => 'Buffalo'],
    '73835' => ['state' => 'OK', 'city' => 'Camargo'],
    '73838' => ['state' => 'OK', 'city' => 'Chester'],
    '73840' => ['state' => 'OK', 'city' => 'Fargo'],
    '73841' => ['state' => 'OK', 'city' => 'Fort Supply'],
    '73842' => ['state' => 'OK', 'city' => 'Freedom'],
    '73843' => ['state' => 'OK', 'city' => 'Gage'],
    '73844' => ['state' => 'OK', 'city' => 'Gate'],
    '73848' => ['state' => 'OK', 'city' => 'Laverne'],
    '73851' => ['state' => 'OK', 'city' => 'May'],
    '73852' => ['state' => 'OK', 'city' => 'Mooreland'],
    '73853' => ['state' => 'OK', 'city' => 'Mutual'],
    '73855' => ['state' => 'OK', 'city' => 'Rosston'],
    '73857' => ['state' => 'OK', 'city' => 'Sharon'],
    '73858' => ['state' => 'OK', 'city' => 'Shattuck'],
    '73859' => ['state' => 'OK', 'city' => 'Vici'],
    '73860' => ['state' => 'OK', 'city' => 'Waynoka'],
];
