<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '73901' => ['state' => 'OK', 'city' => 'Adams'],
    '73931' => ['state' => 'OK', 'city' => 'Balko'],
    '73932' => ['state' => 'OK', 'city' => 'Beaver'],
    '73933' => ['state' => 'OK', 'city' => 'Boise City'],
    '73937' => ['state' => 'OK', 'city' => 'Felt'],
    '73938' => ['state' => 'OK', 'city' => 'Forgan'],
    '73939' => ['state' => 'OK', 'city' => 'Goodwell'],
    '73942' => ['state' => 'OK', 'city' => 'Guymon'],
    '73944' => ['state' => 'OK', 'city' => 'Hardesty'],
    '73945' => ['state' => 'OK', 'city' => 'Hooker'],
    '73946' => ['state' => 'OK', 'city' => 'Kenton'],
    '73947' => ['state' => 'OK', 'city' => 'Keyes'],
    '73949' => ['state' => 'OK', 'city' => 'Texhoma'],
    '73950' => ['state' => 'OK', 'city' => 'Turpin'],
    '73951' => ['state' => 'OK', 'city' => 'Tyrone'],
    '73960' => ['state' => 'TX', 'city' => 'Texhoma'],
];
