<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '74601' => ['state' => 'OK', 'city' => 'Ponca City'],
    '74602' => ['state' => 'OK', 'city' => 'Ponca City'],
    '74604' => ['state' => 'OK', 'city' => 'Ponca City'],
    '74630' => ['state' => 'OK', 'city' => 'Billings'],
    '74631' => ['state' => 'OK', 'city' => 'Blackwell'],
    '74632' => ['state' => 'OK', 'city' => 'Braman'],
    '74633' => ['state' => 'OK', 'city' => 'Burbank'],
    '74636' => ['state' => 'OK', 'city' => 'Deer Creek'],
    '74637' => ['state' => 'OK', 'city' => 'Fairfax'],
    '74640' => ['state' => 'OK', 'city' => 'Hunter'],
    '74641' => ['state' => 'OK', 'city' => 'Kaw City'],
    '74643' => ['state' => 'OK', 'city' => 'Lamont'],
    '74644' => ['state' => 'OK', 'city' => 'Marland'],
    '74646' => ['state' => 'OK', 'city' => 'Nardin'],
    '74647' => ['state' => 'OK', 'city' => 'Newkirk'],
    '74650' => ['state' => 'OK', 'city' => 'Ralston'],
    '74651' => ['state' => 'OK', 'city' => 'Red Rock'],
    '74652' => ['state' => 'OK', 'city' => 'Shidler'],
    '74653' => ['state' => 'OK', 'city' => 'Tonkawa'],
];
