<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '75501' => ['state' => 'TX', 'city' => 'Texarkana'],
    '75503' => ['state' => 'TX', 'city' => 'Texarkana'],
    '75504' => ['state' => 'TX', 'city' => 'Texarkana'],
    '75505' => ['state' => 'TX', 'city' => 'Texarkana'],
    '75507' => ['state' => 'TX', 'city' => 'Texarkana'],
    '75550' => ['state' => 'TX', 'city' => 'Annona'],
    '75551' => ['state' => 'TX', 'city' => 'Atlanta'],
    '75554' => ['state' => 'TX', 'city' => 'Avery'],
    '75555' => ['state' => 'TX', 'city' => 'Bivins'],
    '75556' => ['state' => 'TX', 'city' => 'Bloomburg'],
    '75558' => ['state' => 'TX', 'city' => 'Cookville'],
    '75559' => ['state' => 'TX', 'city' => 'De Kalb'],
    '75560' => ['state' => 'TX', 'city' => 'Douglassville'],
    '75561' => ['state' => 'TX', 'city' => 'Hooks'],
    '75562' => ['state' => 'TX', 'city' => 'Kildare'],
    '75563' => ['state' => 'TX', 'city' => 'Linden'],
    '75564' => ['state' => 'TX', 'city' => 'Lodi'],
    '75565' => ['state' => 'TX', 'city' => 'Mc Leod'],
    '75566' => ['state' => 'TX', 'city' => 'Marietta'],
    '75567' => ['state' => 'TX', 'city' => 'Maud'],
    '75568' => ['state' => 'TX', 'city' => 'Naples'],
    '75569' => ['state' => 'TX', 'city' => 'Nash'],
    '75570' => ['state' => 'TX', 'city' => 'New Boston'],
    '75571' => ['state' => 'TX', 'city' => 'Omaha'],
    '75572' => ['state' => 'TX', 'city' => 'Queen City'],
    '75573' => ['state' => 'TX', 'city' => 'Redwater'],
    '75574' => ['state' => 'TX', 'city' => 'Simms'],
    '75599' => ['state' => 'TX', 'city' => 'Texarkana'],
];
