<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '76901' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76902' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76903' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76904' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76905' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76906' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76908' => ['state' => 'TX', 'city' => 'Goodfellow Afb'],
    '76909' => ['state' => 'TX', 'city' => 'San Angelo'],
    '76930' => ['state' => 'TX', 'city' => 'Barnhart'],
    '76932' => ['state' => 'TX', 'city' => 'Big Lake'],
    '76933' => ['state' => 'TX', 'city' => 'Bronte'],
    '76934' => ['state' => 'TX', 'city' => 'Carlsbad'],
    '76935' => ['state' => 'TX', 'city' => 'Christoval'],
    '76936' => ['state' => 'TX', 'city' => 'Eldorado'],
    '76937' => ['state' => 'TX', 'city' => 'Eola'],
    '76939' => ['state' => 'TX', 'city' => 'Knickerbocker'],
    '76940' => ['state' => 'TX', 'city' => 'Mereta'],
    '76941' => ['state' => 'TX', 'city' => 'Mertzon'],
    '76943' => ['state' => 'TX', 'city' => 'Ozona'],
    '76945' => ['state' => 'TX', 'city' => 'Robert Lee'],
    '76949' => ['state' => 'TX', 'city' => 'Silver'],
    '76950' => ['state' => 'TX', 'city' => 'Sonora'],
    '76951' => ['state' => 'TX', 'city' => 'Sterling City'],
    '76953' => ['state' => 'TX', 'city' => 'Tennyson'],
    '76955' => ['state' => 'TX', 'city' => 'Vancourt'],
    '76957' => ['state' => 'TX', 'city' => 'Wall'],
    '76958' => ['state' => 'TX', 'city' => 'Water Valley'],
];
