<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '78931' => ['state' => 'TX', 'city' => 'Bleiblerville'],
    '78932' => ['state' => 'TX', 'city' => 'Carmine'],
    '78933' => ['state' => 'TX', 'city' => 'Cat Spring'],
    '78934' => ['state' => 'TX', 'city' => 'Columbus'],
    '78935' => ['state' => 'TX', 'city' => 'Alleyton'],
    '78938' => ['state' => 'TX', 'city' => 'Ellinger'],
    '78940' => ['state' => 'TX', 'city' => 'Fayetteville'],
    '78941' => ['state' => 'TX', 'city' => 'Flatonia'],
    '78942' => ['state' => 'TX', 'city' => 'Giddings'],
    '78943' => ['state' => 'TX', 'city' => 'Glidden'],
    '78944' => ['state' => 'TX', 'city' => 'Industry'],
    '78945' => ['state' => 'TX', 'city' => 'La Grange'],
    '78946' => ['state' => 'TX', 'city' => 'Ledbetter'],
    '78947' => ['state' => 'TX', 'city' => 'Lexington'],
    '78948' => ['state' => 'TX', 'city' => 'Lincoln'],
    '78949' => ['state' => 'TX', 'city' => 'Muldoon'],
    '78950' => ['state' => 'TX', 'city' => 'New Ulm'],
    '78951' => ['state' => 'TX', 'city' => 'Oakland'],
    '78952' => ['state' => 'TX', 'city' => 'Plum'],
    '78953' => ['state' => 'TX', 'city' => 'Rosanky'],
    '78954' => ['state' => 'TX', 'city' => 'Round Top'],
    '78956' => ['state' => 'TX', 'city' => 'Schulenburg'],
    '78957' => ['state' => 'TX', 'city' => 'Smithville'],
    '78959' => ['state' => 'TX', 'city' => 'Waelder'],
    '78960' => ['state' => 'TX', 'city' => 'Warda'],
    '78961' => ['state' => 'TX', 'city' => 'Round Top'],
    '78962' => ['state' => 'TX', 'city' => 'Weimar'],
    '78963' => ['state' => 'TX', 'city' => 'West Point'],
];
