<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '79601' => ['state' => 'TX', 'city' => 'Abilene'],
    '79602' => ['state' => 'TX', 'city' => 'Abilene'],
    '79603' => ['state' => 'TX', 'city' => 'Abilene'],
    '79604' => ['state' => 'TX', 'city' => 'Abilene'],
    '79605' => ['state' => 'TX', 'city' => 'Abilene'],
    '79606' => ['state' => 'TX', 'city' => 'Abilene'],
    '79607' => ['state' => 'TX', 'city' => 'Dyess Afb'],
    '79608' => ['state' => 'TX', 'city' => 'Abilene'],
    '79697' => ['state' => 'TX', 'city' => 'Abilene'],
    '79698' => ['state' => 'TX', 'city' => 'Abilene'],
    '79699' => ['state' => 'TX', 'city' => 'Abilene'],
];
