<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '79821' => ['state' => 'TX', 'city' => 'Anthony'],
    '79830' => ['state' => 'TX', 'city' => 'Alpine'],
    '79831' => ['state' => 'TX', 'city' => 'Alpine'],
    '79832' => ['state' => 'TX', 'city' => 'Alpine'],
    '79834' => ['state' => 'TX', 'city' => 'Big Bend National Park'],
    '79835' => ['state' => 'TX', 'city' => 'Canutillo'],
    '79836' => ['state' => 'TX', 'city' => 'Clint'],
    '79837' => ['state' => 'TX', 'city' => 'Dell City'],
    '79838' => ['state' => 'TX', 'city' => 'Fabens'],
    '79839' => ['state' => 'TX', 'city' => 'Fort Hancock'],
    '79842' => ['state' => 'TX', 'city' => 'Marathon'],
    '79843' => ['state' => 'TX', 'city' => 'Marfa'],
    '79845' => ['state' => 'TX', 'city' => 'Presidio'],
    '79846' => ['state' => 'TX', 'city' => 'Redford'],
    '79847' => ['state' => 'TX', 'city' => 'Salt Flat'],
    '79848' => ['state' => 'TX', 'city' => 'Sanderson'],
    '79849' => ['state' => 'TX', 'city' => 'San Elizario'],
    '79851' => ['state' => 'TX', 'city' => 'Sierra Blanca'],
    '79852' => ['state' => 'TX', 'city' => 'Terlingua'],
    '79853' => ['state' => 'TX', 'city' => 'Tornillo'],
    '79854' => ['state' => 'TX', 'city' => 'Valentine'],
    '79855' => ['state' => 'TX', 'city' => 'Van Horn'],
];
