<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '80301' => ['state' => 'CO', 'city' => 'Boulder'],
    '80302' => ['state' => 'CO', 'city' => 'Boulder'],
    '80303' => ['state' => 'CO', 'city' => 'Boulder'],
    '80304' => ['state' => 'CO', 'city' => 'Boulder'],
    '80305' => ['state' => 'CO', 'city' => 'Boulder'],
    '80306' => ['state' => 'CO', 'city' => 'Boulder'],
    '80307' => ['state' => 'CO', 'city' => 'Boulder'],
    '80308' => ['state' => 'CO', 'city' => 'Boulder'],
    '80309' => ['state' => 'CO', 'city' => 'Boulder'],
    '80310' => ['state' => 'CO', 'city' => 'Boulder'],
    '80314' => ['state' => 'CO', 'city' => 'Boulder'],
];
