<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '81301' => ['state' => 'CO', 'city' => 'Durango'],
    '81302' => ['state' => 'CO', 'city' => 'Durango'],
    '81303' => ['state' => 'CO', 'city' => 'Durango'],
    '81320' => ['state' => 'CO', 'city' => 'Cahone'],
    '81321' => ['state' => 'CO', 'city' => 'Cortez'],
    '81323' => ['state' => 'CO', 'city' => 'Dolores'],
    '81324' => ['state' => 'CO', 'city' => 'Dove Creek'],
    '81325' => ['state' => 'CO', 'city' => 'Egnar'],
    '81326' => ['state' => 'CO', 'city' => 'Hesperus'],
    '81327' => ['state' => 'CO', 'city' => 'Lewis'],
    '81328' => ['state' => 'CO', 'city' => 'Mancos'],
    '81329' => ['state' => 'CO', 'city' => 'Marvel'],
    '81330' => ['state' => 'CO', 'city' => 'Mesa Verde National Park'],
    '81331' => ['state' => 'CO', 'city' => 'Pleasant View'],
    '81332' => ['state' => 'CO', 'city' => 'Rico'],
    '81334' => ['state' => 'CO', 'city' => 'Towaoc'],
    '81335' => ['state' => 'CO', 'city' => 'Yellow Jacket'],
];
