<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '81401' => ['state' => 'CO', 'city' => 'Montrose'],
    '81402' => ['state' => 'CO', 'city' => 'Montrose'],
    '81403' => ['state' => 'CO', 'city' => 'Montrose'],
    '81410' => ['state' => 'CO', 'city' => 'Austin'],
    '81411' => ['state' => 'CO', 'city' => 'Bedrock'],
    '81413' => ['state' => 'CO', 'city' => 'Cedaredge'],
    '81414' => ['state' => 'CO', 'city' => 'Cory'],
    '81415' => ['state' => 'CO', 'city' => 'Crawford'],
    '81416' => ['state' => 'CO', 'city' => 'Delta'],
    '81418' => ['state' => 'CO', 'city' => 'Eckert'],
    '81419' => ['state' => 'CO', 'city' => 'Hotchkiss'],
    '81420' => ['state' => 'CO', 'city' => 'Lazear'],
    '81422' => ['state' => 'CO', 'city' => 'Naturita'],
    '81423' => ['state' => 'CO', 'city' => 'Norwood'],
    '81424' => ['state' => 'CO', 'city' => 'Nucla'],
    '81425' => ['state' => 'CO', 'city' => 'Olathe'],
    '81426' => ['state' => 'CO', 'city' => 'Ophir'],
    '81427' => ['state' => 'CO', 'city' => 'Ouray'],
    '81428' => ['state' => 'CO', 'city' => 'Paonia'],
    '81429' => ['state' => 'CO', 'city' => 'Paradox'],
    '81430' => ['state' => 'CO', 'city' => 'Placerville'],
    '81431' => ['state' => 'CO', 'city' => 'Redvale'],
    '81432' => ['state' => 'CO', 'city' => 'Ridgway'],
    '81433' => ['state' => 'CO', 'city' => 'Silverton'],
    '81434' => ['state' => 'CO', 'city' => 'Somerset'],
    '81435' => ['state' => 'CO', 'city' => 'Telluride'],
];
