<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '81501' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81502' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81503' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81504' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81505' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81506' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81507' => ['state' => 'CO', 'city' => 'Grand Junction'],
    '81520' => ['state' => 'CO', 'city' => 'Clifton'],
    '81521' => ['state' => 'CO', 'city' => 'Fruita'],
    '81522' => ['state' => 'CO', 'city' => 'Gateway'],
    '81523' => ['state' => 'CO', 'city' => 'Glade Park'],
    '81524' => ['state' => 'CO', 'city' => 'Loma'],
    '81525' => ['state' => 'CO', 'city' => 'Mack'],
    '81526' => ['state' => 'CO', 'city' => 'Palisade'],
    '81527' => ['state' => 'CO', 'city' => 'Whitewater'],
];
