<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82001' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82002' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82003' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82005' => ['state' => 'WY', 'city' => 'Fe Warren Afb'],
    '82006' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82007' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82008' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82009' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82010' => ['state' => 'WY', 'city' => 'Cheyenne'],
    '82050' => ['state' => 'WY', 'city' => 'Albin'],
    '82051' => ['state' => 'WY', 'city' => 'Bosler'],
    '82052' => ['state' => 'WY', 'city' => 'Buford'],
    '82053' => ['state' => 'WY', 'city' => 'Burns'],
    '82054' => ['state' => 'WY', 'city' => 'Carpenter'],
    '82055' => ['state' => 'WY', 'city' => 'Centennial'],
    '82058' => ['state' => 'WY', 'city' => 'Garrett'],
    '82059' => ['state' => 'WY', 'city' => 'Granite Canon'],
    '82060' => ['state' => 'WY', 'city' => 'Hillsdale'],
    '82061' => ['state' => 'WY', 'city' => 'Horse Creek'],
    '82063' => ['state' => 'WY', 'city' => 'Jelm'],
    '82070' => ['state' => 'WY', 'city' => 'Laramie'],
    '82071' => ['state' => 'WY', 'city' => 'Laramie'],
    '82072' => ['state' => 'WY', 'city' => 'Laramie'],
    '82073' => ['state' => 'WY', 'city' => 'Laramie'],
    '82081' => ['state' => 'WY', 'city' => 'Meriden'],
    '82082' => ['state' => 'WY', 'city' => 'Pine Bluffs'],
    '82083' => ['state' => 'WY', 'city' => 'Rock River'],
    '82084' => ['state' => 'WY', 'city' => 'Tie Siding'],
];
