<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82301' => ['state' => 'WY', 'city' => 'Rawlins'],
    '82310' => ['state' => 'WY', 'city' => 'Jeffrey City'],
    '82321' => ['state' => 'WY', 'city' => 'Baggs'],
    '82322' => ['state' => 'WY', 'city' => 'Bairoil'],
    '82323' => ['state' => 'WY', 'city' => 'Dixon'],
    '82324' => ['state' => 'WY', 'city' => 'Elk Mountain'],
    '82325' => ['state' => 'WY', 'city' => 'Encampment'],
    '82327' => ['state' => 'WY', 'city' => 'Hanna'],
    '82329' => ['state' => 'WY', 'city' => 'Medicine Bow'],
    '82331' => ['state' => 'WY', 'city' => 'Saratoga'],
    '82332' => ['state' => 'WY', 'city' => 'Savery'],
    '82334' => ['state' => 'WY', 'city' => 'Sinclair'],
    '82335' => ['state' => 'WY', 'city' => 'Walcott'],
    '82336' => ['state' => 'WY', 'city' => 'Wamsutter'],
];
