<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82401' => ['state' => 'WY', 'city' => 'Worland'],
    '82410' => ['state' => 'WY', 'city' => 'Basin'],
    '82411' => ['state' => 'WY', 'city' => 'Burlington'],
    '82412' => ['state' => 'WY', 'city' => 'Byron'],
    '82414' => ['state' => 'WY', 'city' => 'Cody'],
    '82420' => ['state' => 'WY', 'city' => 'Cowley'],
    '82421' => ['state' => 'WY', 'city' => 'Deaver'],
    '82422' => ['state' => 'WY', 'city' => 'Emblem'],
    '82423' => ['state' => 'WY', 'city' => 'Frannie'],
    '82426' => ['state' => 'WY', 'city' => 'Greybull'],
    '82428' => ['state' => 'WY', 'city' => 'Hyattville'],
    '82430' => ['state' => 'WY', 'city' => 'Kirby'],
    '82431' => ['state' => 'WY', 'city' => 'Lovell'],
    '82432' => ['state' => 'WY', 'city' => 'Manderson'],
    '82433' => ['state' => 'WY', 'city' => 'Meeteetse'],
    '82434' => ['state' => 'WY', 'city' => 'Otto'],
    '82435' => ['state' => 'WY', 'city' => 'Powell'],
    '82440' => ['state' => 'WY', 'city' => 'Ralston'],
    '82441' => ['state' => 'WY', 'city' => 'Shell'],
    '82442' => ['state' => 'WY', 'city' => 'Ten Sleep'],
    '82443' => ['state' => 'WY', 'city' => 'Thermopolis'],
    '82450' => ['state' => 'WY', 'city' => 'Wapiti'],
];
