<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82501' => ['state' => 'WY', 'city' => 'Riverton'],
    '82510' => ['state' => 'WY', 'city' => 'Arapahoe'],
    '82512' => ['state' => 'WY', 'city' => 'Crowheart'],
    '82513' => ['state' => 'WY', 'city' => 'Dubois'],
    '82514' => ['state' => 'WY', 'city' => 'Fort Washakie'],
    '82515' => ['state' => 'WY', 'city' => 'Hudson'],
    '82516' => ['state' => 'WY', 'city' => 'Kinnear'],
    '82520' => ['state' => 'WY', 'city' => 'Lander'],
    '82523' => ['state' => 'WY', 'city' => 'Pavillion'],
    '82524' => ['state' => 'WY', 'city' => 'Saint Stephens'],
];
