<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82601' => ['state' => 'WY', 'city' => 'Casper'],
    '82602' => ['state' => 'WY', 'city' => 'Casper'],
    '82604' => ['state' => 'WY', 'city' => 'Casper'],
    '82605' => ['state' => 'WY', 'city' => 'Casper'],
    '82609' => ['state' => 'WY', 'city' => 'Casper'],
    '82615' => ['state' => 'WY', 'city' => 'Shirley Basin'],
    '82620' => ['state' => 'WY', 'city' => 'Alcova'],
    '82630' => ['state' => 'WY', 'city' => 'Arminto'],
    '82633' => ['state' => 'WY', 'city' => 'Douglas'],
    '82635' => ['state' => 'WY', 'city' => 'Edgerton'],
    '82636' => ['state' => 'WY', 'city' => 'Evansville'],
    '82637' => ['state' => 'WY', 'city' => 'Glenrock'],
    '82638' => ['state' => 'WY', 'city' => 'Hiland'],
    '82639' => ['state' => 'WY', 'city' => 'Kaycee'],
    '82640' => ['state' => 'WY', 'city' => 'Linch'],
    '82642' => ['state' => 'WY', 'city' => 'Lysite'],
    '82643' => ['state' => 'WY', 'city' => 'Midwest'],
    '82644' => ['state' => 'WY', 'city' => 'Mills'],
    '82646' => ['state' => 'WY', 'city' => 'Natrona'],
    '82648' => ['state' => 'WY', 'city' => 'Powder River'],
    '82649' => ['state' => 'WY', 'city' => 'Shoshoni'],
];
