<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82701' => ['state' => 'WY', 'city' => 'Newcastle'],
    '82710' => ['state' => 'WY', 'city' => 'Aladdin'],
    '82711' => ['state' => 'WY', 'city' => 'Alva'],
    '82712' => ['state' => 'WY', 'city' => 'Beulah'],
    '82714' => ['state' => 'WY', 'city' => 'Devils Tower'],
    '82715' => ['state' => 'WY', 'city' => 'Four Corners'],
    '82716' => ['state' => 'WY', 'city' => 'Gillette'],
    '82717' => ['state' => 'WY', 'city' => 'Gillette'],
    '82718' => ['state' => 'WY', 'city' => 'Gillette'],
    '82720' => ['state' => 'WY', 'city' => 'Hulett'],
    '82721' => ['state' => 'WY', 'city' => 'Moorcroft'],
    '82723' => ['state' => 'WY', 'city' => 'Osage'],
    '82725' => ['state' => 'WY', 'city' => 'Recluse'],
    '82727' => ['state' => 'WY', 'city' => 'Rozet'],
    '82729' => ['state' => 'WY', 'city' => 'Sundance'],
    '82730' => ['state' => 'WY', 'city' => 'Upton'],
    '82731' => ['state' => 'WY', 'city' => 'Weston'],
    '82732' => ['state' => 'WY', 'city' => 'Wright'],
];
