<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '82801' => ['state' => 'WY', 'city' => 'Sheridan'],
    '82831' => ['state' => 'WY', 'city' => 'Arvada'],
    '82832' => ['state' => 'WY', 'city' => 'Banner'],
    '82833' => ['state' => 'WY', 'city' => 'Big Horn'],
    '82834' => ['state' => 'WY', 'city' => 'Buffalo'],
    '82835' => ['state' => 'WY', 'city' => 'Clearmont'],
    '82836' => ['state' => 'WY', 'city' => 'Dayton'],
    '82837' => ['state' => 'WY', 'city' => 'Leiter'],
    '82838' => ['state' => 'WY', 'city' => 'Parkman'],
    '82839' => ['state' => 'WY', 'city' => 'Ranchester'],
    '82840' => ['state' => 'WY', 'city' => 'Saddlestring'],
    '82842' => ['state' => 'WY', 'city' => 'Story'],
    '82844' => ['state' => 'WY', 'city' => 'Wolf'],
    '82845' => ['state' => 'WY', 'city' => 'Wyarno'],
];
