<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '83001' => ['state' => 'WY', 'city' => 'Jackson'],
    '83002' => ['state' => 'WY', 'city' => 'Jackson'],
    '83011' => ['state' => 'WY', 'city' => 'Kelly'],
    '83012' => ['state' => 'WY', 'city' => 'Moose'],
    '83013' => ['state' => 'WY', 'city' => 'Moran'],
    '83014' => ['state' => 'WY', 'city' => 'Wilson'],
    '83025' => ['state' => 'WY', 'city' => 'Teton Village'],
];
