<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '83501' => ['state' => 'ID', 'city' => 'Lewiston'],
    '83520' => ['state' => 'ID', 'city' => 'Ahsahka'],
    '83522' => ['state' => 'ID', 'city' => 'Cottonwood'],
    '83523' => ['state' => 'ID', 'city' => 'Craigmont'],
    '83524' => ['state' => 'ID', 'city' => 'Culdesac'],
    '83525' => ['state' => 'ID', 'city' => 'Elk City'],
    '83526' => ['state' => 'ID', 'city' => 'Ferdinand'],
    '83530' => ['state' => 'ID', 'city' => 'Grangeville'],
    '83531' => ['state' => 'ID', 'city' => 'Fenn'],
    '83533' => ['state' => 'ID', 'city' => 'Greencreek'],
    '83535' => ['state' => 'ID', 'city' => 'Juliaetta'],
    '83536' => ['state' => 'ID', 'city' => 'Kamiah'],
    '83537' => ['state' => 'ID', 'city' => 'Kendrick'],
    '83539' => ['state' => 'ID', 'city' => 'Kooskia'],
    '83540' => ['state' => 'ID', 'city' => 'Lapwai'],
    '83541' => ['state' => 'ID', 'city' => 'Lenore'],
    '83542' => ['state' => 'ID', 'city' => 'Lucile'],
    '83543' => ['state' => 'ID', 'city' => 'Nezperce'],
    '83544' => ['state' => 'ID', 'city' => 'Orofino'],
    '83545' => ['state' => 'ID', 'city' => 'Peck'],
    '83546' => ['state' => 'ID', 'city' => 'Pierce'],
    '83547' => ['state' => 'ID', 'city' => 'Pollock'],
    '83548' => ['state' => 'ID', 'city' => 'Reubens'],
    '83549' => ['state' => 'ID', 'city' => 'Riggins'],
    '83552' => ['state' => 'ID', 'city' => 'Stites'],
    '83553' => ['state' => 'ID', 'city' => 'Weippe'],
    '83554' => ['state' => 'ID', 'city' => 'White Bird'],
    '83555' => ['state' => 'ID', 'city' => 'Winchester'],
];
