<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '84501' => ['state' => 'UT', 'city' => 'Price'],
    '84510' => ['state' => 'UT', 'city' => 'Aneth'],
    '84511' => ['state' => 'UT', 'city' => 'Blanding'],
    '84512' => ['state' => 'UT', 'city' => 'Bluff'],
    '84513' => ['state' => 'UT', 'city' => 'Castle Dale'],
    '84515' => ['state' => 'UT', 'city' => 'Cisco'],
    '84516' => ['state' => 'UT', 'city' => 'Clawson'],
    '84518' => ['state' => 'UT', 'city' => 'Cleveland'],
    '84520' => ['state' => 'UT', 'city' => 'East Carbon'],
    '84521' => ['state' => 'UT', 'city' => 'Elmo'],
    '84522' => ['state' => 'UT', 'city' => 'Emery'],
    '84523' => ['state' => 'UT', 'city' => 'Ferron'],
    '84525' => ['state' => 'UT', 'city' => 'Green River'],
    '84526' => ['state' => 'UT', 'city' => 'Helper'],
    '84528' => ['state' => 'UT', 'city' => 'Huntington'],
    '84529' => ['state' => 'UT', 'city' => 'Kenilworth'],
    '84530' => ['state' => 'UT', 'city' => 'La Sal'],
    '84531' => ['state' => 'UT', 'city' => 'Mexican Hat'],
    '84532' => ['state' => 'UT', 'city' => 'Moab'],
    '84533' => ['state' => 'UT', 'city' => 'Lake Powell'],
    '84534' => ['state' => 'UT', 'city' => 'Montezuma Creek'],
    '84535' => ['state' => 'UT', 'city' => 'Monticello'],
    '84536' => ['state' => 'UT', 'city' => 'Monument Valley'],
    '84537' => ['state' => 'UT', 'city' => 'Orangeville'],
    '84539' => ['state' => 'UT', 'city' => 'Sunnyside'],
    '84540' => ['state' => 'UT', 'city' => 'Thompson'],
    '84542' => ['state' => 'UT', 'city' => 'Wellington'],
];
