<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '85501' => ['state' => 'AZ', 'city' => 'Globe'],
    '85502' => ['state' => 'AZ', 'city' => 'Globe'],
    '85530' => ['state' => 'AZ', 'city' => 'Bylas'],
    '85531' => ['state' => 'AZ', 'city' => 'Central'],
    '85532' => ['state' => 'AZ', 'city' => 'Claypool'],
    '85533' => ['state' => 'AZ', 'city' => 'Clifton'],
    '85534' => ['state' => 'AZ', 'city' => 'Duncan'],
    '85535' => ['state' => 'AZ', 'city' => 'Eden'],
    '85536' => ['state' => 'AZ', 'city' => 'Fort Thomas'],
    '85539' => ['state' => 'AZ', 'city' => 'Miami'],
    '85540' => ['state' => 'AZ', 'city' => 'Morenci'],
    '85541' => ['state' => 'AZ', 'city' => 'Payson'],
    '85542' => ['state' => 'AZ', 'city' => 'Peridot'],
    '85543' => ['state' => 'AZ', 'city' => 'Pima'],
    '85544' => ['state' => 'AZ', 'city' => 'Pine'],
    '85545' => ['state' => 'AZ', 'city' => 'Roosevelt'],
    '85546' => ['state' => 'AZ', 'city' => 'Safford'],
    '85547' => ['state' => 'AZ', 'city' => 'Payson'],
    '85548' => ['state' => 'AZ', 'city' => 'Safford'],
    '85550' => ['state' => 'AZ', 'city' => 'San Carlos'],
    '85551' => ['state' => 'AZ', 'city' => 'Solomon'],
    '85552' => ['state' => 'AZ', 'city' => 'Thatcher'],
    '85553' => ['state' => 'AZ', 'city' => 'Tonto Basin'],
    '85554' => ['state' => 'AZ', 'city' => 'Young'],
];
