<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '85901' => ['state' => 'AZ', 'city' => 'Show Low'],
    '85902' => ['state' => 'AZ', 'city' => 'Show Low'],
    '85911' => ['state' => 'AZ', 'city' => 'Cibecue'],
    '85912' => ['state' => 'AZ', 'city' => 'White Mountain Lake'],
    '85920' => ['state' => 'AZ', 'city' => 'Alpine'],
    '85922' => ['state' => 'AZ', 'city' => 'Blue'],
    '85923' => ['state' => 'AZ', 'city' => 'Clay Springs'],
    '85924' => ['state' => 'AZ', 'city' => 'Concho'],
    '85925' => ['state' => 'AZ', 'city' => 'Eagar'],
    '85926' => ['state' => 'AZ', 'city' => 'Fort Apache'],
    '85927' => ['state' => 'AZ', 'city' => 'Greer'],
    '85928' => ['state' => 'AZ', 'city' => 'Heber'],
    '85929' => ['state' => 'AZ', 'city' => 'Lakeside'],
    '85930' => ['state' => 'AZ', 'city' => 'Mcnary'],
    '85931' => ['state' => 'AZ', 'city' => 'Forest Lakes'],
    '85932' => ['state' => 'AZ', 'city' => 'Nutrioso'],
    '85933' => ['state' => 'AZ', 'city' => 'Overgaard'],
    '85934' => ['state' => 'AZ', 'city' => 'Pinedale'],
    '85935' => ['state' => 'AZ', 'city' => 'Pinetop'],
    '85936' => ['state' => 'AZ', 'city' => 'Saint Johns'],
    '85937' => ['state' => 'AZ', 'city' => 'Snowflake'],
    '85938' => ['state' => 'AZ', 'city' => 'Springerville'],
    '85939' => ['state' => 'AZ', 'city' => 'Taylor'],
    '85940' => ['state' => 'AZ', 'city' => 'Vernon'],
    '85941' => ['state' => 'AZ', 'city' => 'Whiteriver'],
    '85942' => ['state' => 'AZ', 'city' => 'Woodruff'],
];
