<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '86502' => ['state' => 'AZ', 'city' => 'Chambers'],
    '86503' => ['state' => 'AZ', 'city' => 'Chinle'],
    '86504' => ['state' => 'AZ', 'city' => 'Fort Defiance'],
    '86505' => ['state' => 'AZ', 'city' => 'Ganado'],
    '86506' => ['state' => 'AZ', 'city' => 'Houck'],
    '86507' => ['state' => 'AZ', 'city' => 'Lukachukai'],
    '86508' => ['state' => 'AZ', 'city' => 'Lupton'],
    '86510' => ['state' => 'AZ', 'city' => 'Pinon'],
    '86511' => ['state' => 'AZ', 'city' => 'Saint Michaels'],
    '86512' => ['state' => 'AZ', 'city' => 'Sanders'],
    '86514' => ['state' => 'AZ', 'city' => 'Teec Nos Pos'],
    '86515' => ['state' => 'AZ', 'city' => 'Window Rock'],
    '86520' => ['state' => 'AZ', 'city' => 'Blue Gap'],
    '86535' => ['state' => 'AZ', 'city' => 'Dennehotso'],
    '86538' => ['state' => 'AZ', 'city' => 'Many Farms'],
    '86540' => ['state' => 'AZ', 'city' => 'Nazlini'],
    '86544' => ['state' => 'AZ', 'city' => 'Red Valley'],
    '86545' => ['state' => 'AZ', 'city' => 'Rock Point'],
    '86547' => ['state' => 'AZ', 'city' => 'Round Rock'],
    '86556' => ['state' => 'AZ', 'city' => 'Tsaile'],
];
