<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '87401' => ['state' => 'NM', 'city' => 'Farmington'],
    '87402' => ['state' => 'NM', 'city' => 'Farmington'],
    '87410' => ['state' => 'NM', 'city' => 'Aztec'],
    '87412' => ['state' => 'NM', 'city' => 'Blanco'],
    '87413' => ['state' => 'NM', 'city' => 'Bloomfield'],
    '87415' => ['state' => 'NM', 'city' => 'Flora Vista'],
    '87416' => ['state' => 'NM', 'city' => 'Fruitland'],
    '87417' => ['state' => 'NM', 'city' => 'Kirtland'],
    '87418' => ['state' => 'NM', 'city' => 'La Plata'],
    '87419' => ['state' => 'NM', 'city' => 'Navajo Dam'],
    '87420' => ['state' => 'NM', 'city' => 'Shiprock'],
    '87421' => ['state' => 'NM', 'city' => 'Waterflow'],
    '87455' => ['state' => 'NM', 'city' => 'Newcomb'],
    '87461' => ['state' => 'NM', 'city' => 'Sanostee'],
    '87499' => ['state' => 'NM', 'city' => 'Farmington'],
];
