<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '87801' => ['state' => 'NM', 'city' => 'Socorro'],
    '87820' => ['state' => 'NM', 'city' => 'Aragon'],
    '87821' => ['state' => 'NM', 'city' => 'Datil'],
    '87823' => ['state' => 'NM', 'city' => 'Lemitar'],
    '87824' => ['state' => 'NM', 'city' => 'Luna'],
    '87825' => ['state' => 'NM', 'city' => 'Magdalena'],
    '87827' => ['state' => 'NM', 'city' => 'Pie Town'],
    '87828' => ['state' => 'NM', 'city' => 'Polvadera'],
    '87829' => ['state' => 'NM', 'city' => 'Quemado'],
    '87830' => ['state' => 'NM', 'city' => 'Reserve'],
    '87831' => ['state' => 'NM', 'city' => 'San Acacia'],
    '87832' => ['state' => 'NM', 'city' => 'San Antonio'],
];
