<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '87901' => ['state' => 'NM', 'city' => 'Truth Or Consequences'],
    '87930' => ['state' => 'NM', 'city' => 'Arrey'],
    '87931' => ['state' => 'NM', 'city' => 'Caballo'],
    '87933' => ['state' => 'NM', 'city' => 'Derry'],
    '87935' => ['state' => 'NM', 'city' => 'Elephant Butte'],
    '87936' => ['state' => 'NM', 'city' => 'Garfield'],
    '87937' => ['state' => 'NM', 'city' => 'Hatch'],
    '87939' => ['state' => 'NM', 'city' => 'Monticello'],
    '87940' => ['state' => 'NM', 'city' => 'Rincon'],
    '87941' => ['state' => 'NM', 'city' => 'Salem'],
    '87942' => ['state' => 'NM', 'city' => 'Williamsburg'],
    '87943' => ['state' => 'NM', 'city' => 'Winston'],
];
