<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '88101' => ['state' => 'NM', 'city' => 'Clovis'],
    '88102' => ['state' => 'NM', 'city' => 'Clovis'],
    '88103' => ['state' => 'NM', 'city' => 'Cannon Afb'],
    '88112' => ['state' => 'NM', 'city' => 'Broadview'],
    '88113' => ['state' => 'NM', 'city' => 'Causey'],
    '88114' => ['state' => 'NM', 'city' => 'Crossroads'],
    '88115' => ['state' => 'NM', 'city' => 'Dora'],
    '88116' => ['state' => 'NM', 'city' => 'Elida'],
    '88118' => ['state' => 'NM', 'city' => 'Floyd'],
    '88119' => ['state' => 'NM', 'city' => 'Fort Sumner'],
    '88120' => ['state' => 'NM', 'city' => 'Grady'],
    '88121' => ['state' => 'NM', 'city' => 'House'],
    '88122' => ['state' => 'NM', 'city' => 'Kenna'],
    '88123' => ['state' => 'NM', 'city' => 'Lingo'],
    '88124' => ['state' => 'NM', 'city' => 'Melrose'],
    '88125' => ['state' => 'NM', 'city' => 'Milnesand'],
    '88126' => ['state' => 'NM', 'city' => 'Pep'],
    '88130' => ['state' => 'NM', 'city' => 'Portales'],
    '88132' => ['state' => 'NM', 'city' => 'Rogers'],
    '88133' => ['state' => 'NM', 'city' => 'Saint Vrain'],
    '88134' => ['state' => 'NM', 'city' => 'Taiban'],
    '88135' => ['state' => 'NM', 'city' => 'Texico'],
    '88136' => ['state' => 'NM', 'city' => 'Yeso'],
];
