<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '88201' => ['state' => 'NM', 'city' => 'Roswell'],
    '88202' => ['state' => 'NM', 'city' => 'Roswell'],
    '88203' => ['state' => 'NM', 'city' => 'Roswell'],
    '88210' => ['state' => 'NM', 'city' => 'Artesia'],
    '88211' => ['state' => 'NM', 'city' => 'Artesia'],
    '88213' => ['state' => 'NM', 'city' => 'Caprock'],
    '88220' => ['state' => 'NM', 'city' => 'Carlsbad'],
    '88221' => ['state' => 'NM', 'city' => 'Carlsbad'],
    '88230' => ['state' => 'NM', 'city' => 'Dexter'],
    '88231' => ['state' => 'NM', 'city' => 'Eunice'],
    '88232' => ['state' => 'NM', 'city' => 'Hagerman'],
    '88240' => ['state' => 'NM', 'city' => 'Hobbs'],
    '88241' => ['state' => 'NM', 'city' => 'Hobbs'],
    '88242' => ['state' => 'NM', 'city' => 'Hobbs'],
    '88244' => ['state' => 'NM', 'city' => 'Hobbs'],
    '88250' => ['state' => 'NM', 'city' => 'Hope'],
    '88252' => ['state' => 'NM', 'city' => 'Jal'],
    '88253' => ['state' => 'NM', 'city' => 'Lake Arthur'],
    '88254' => ['state' => 'NM', 'city' => 'Lakewood'],
    '88255' => ['state' => 'NM', 'city' => 'Loco Hills'],
    '88256' => ['state' => 'NM', 'city' => 'Loving'],
    '88260' => ['state' => 'NM', 'city' => 'Lovington'],
    '88262' => ['state' => 'NM', 'city' => 'Mcdonald'],
    '88263' => ['state' => 'NM', 'city' => 'Malaga'],
    '88264' => ['state' => 'NM', 'city' => 'Maljamar'],
    '88265' => ['state' => 'NM', 'city' => 'Monument'],
    '88267' => ['state' => 'NM', 'city' => 'Tatum'],
    '88268' => ['state' => 'NM', 'city' => 'Whites City'],
];
