<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '88401' => ['state' => 'NM', 'city' => 'Tucumcari'],
    '88410' => ['state' => 'NM', 'city' => 'Amistad'],
    '88411' => ['state' => 'NM', 'city' => 'Bard'],
    '88414' => ['state' => 'NM', 'city' => 'Capulin'],
    '88415' => ['state' => 'NM', 'city' => 'Clayton'],
    '88416' => ['state' => 'NM', 'city' => 'Conchas Dam'],
    '88417' => ['state' => 'NM', 'city' => 'Cuervo'],
    '88418' => ['state' => 'NM', 'city' => 'Des Moines'],
    '88419' => ['state' => 'NM', 'city' => 'Folsom'],
    '88421' => ['state' => 'NM', 'city' => 'Garita'],
    '88422' => ['state' => 'NM', 'city' => 'Gladstone'],
    '88424' => ['state' => 'NM', 'city' => 'Grenville'],
    '88426' => ['state' => 'NM', 'city' => 'Logan'],
    '88427' => ['state' => 'NM', 'city' => 'Mcalister'],
    '88430' => ['state' => 'NM', 'city' => 'Nara Visa'],
    '88431' => ['state' => 'NM', 'city' => 'Newkirk'],
    '88433' => ['state' => 'NM', 'city' => 'Quay'],
    '88434' => ['state' => 'NM', 'city' => 'San Jon'],
    '88435' => ['state' => 'NM', 'city' => 'Santa Rosa'],
    '88436' => ['state' => 'NM', 'city' => 'Sedan'],
    '88439' => ['state' => 'NM', 'city' => 'Trementina'],
];
