<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '88901' => ['state' => 'NV', 'city' => 'The Lakes'],
    '88905' => ['state' => 'NV', 'city' => 'The Lakes'],
];
