<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '89301' => ['state' => 'NV', 'city' => 'Ely'],
    '89310' => ['state' => 'NV', 'city' => 'Austin'],
    '89311' => ['state' => 'NV', 'city' => 'Baker'],
    '89314' => ['state' => 'NV', 'city' => 'Duckwater'],
    '89315' => ['state' => 'NV', 'city' => 'Ely'],
    '89316' => ['state' => 'NV', 'city' => 'Eureka'],
    '89317' => ['state' => 'NV', 'city' => 'Lund'],
    '89318' => ['state' => 'NV', 'city' => 'Mc Gill'],
    '89319' => ['state' => 'NV', 'city' => 'Ruth'],
];
