<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '89701' => ['state' => 'NV', 'city' => 'Carson City'],
    '89702' => ['state' => 'NV', 'city' => 'Carson City'],
    '89703' => ['state' => 'NV', 'city' => 'Carson City'],
    '89704' => ['state' => 'NV', 'city' => 'Washoe Valley'],
    '89705' => ['state' => 'NV', 'city' => 'Carson City'],
    '89706' => ['state' => 'NV', 'city' => 'Carson City'],
    '89711' => ['state' => 'NV', 'city' => 'Carson City'],
    '89712' => ['state' => 'NV', 'city' => 'Carson City'],
    '89713' => ['state' => 'NV', 'city' => 'Carson City'],
    '89714' => ['state' => 'NV', 'city' => 'Carson City'],
    '89721' => ['state' => 'NV', 'city' => 'Carson City'],
];
