<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '89801' => ['state' => 'NV', 'city' => 'Elko'],
    '89802' => ['state' => 'NV', 'city' => 'Elko'],
    '89803' => ['state' => 'NV', 'city' => 'Elko'],
    '89815' => ['state' => 'NV', 'city' => 'Spring Creek'],
    '89820' => ['state' => 'NV', 'city' => 'Battle Mountain'],
    '89821' => ['state' => 'NV', 'city' => 'Crescent Valley'],
    '89822' => ['state' => 'NV', 'city' => 'Carlin'],
    '89823' => ['state' => 'NV', 'city' => 'Deeth'],
    '89825' => ['state' => 'NV', 'city' => 'Jackpot'],
    '89826' => ['state' => 'NV', 'city' => 'Jarbidge'],
    '89828' => ['state' => 'NV', 'city' => 'Lamoille'],
    '89830' => ['state' => 'NV', 'city' => 'Montello'],
    '89831' => ['state' => 'NV', 'city' => 'Mountain City'],
    '89832' => ['state' => 'NV', 'city' => 'Owyhee'],
    '89833' => ['state' => 'NV', 'city' => 'Ruby Valley'],
    '89834' => ['state' => 'NV', 'city' => 'Tuscarora'],
    '89835' => ['state' => 'NV', 'city' => 'Wells'],
    '89883' => ['state' => 'NV', 'city' => 'West Wendover'],
];
