<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '90134' => ['state' => 'CA', 'city' => 'Los Angeles'],
    '90189' => ['state' => 'CA', 'city' => 'Los Angeles'],
];
