<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '91001' => ['state' => 'CA', 'city' => 'Altadena'],
    '91003' => ['state' => 'CA', 'city' => 'Altadena'],
    '91006' => ['state' => 'CA', 'city' => 'Arcadia'],
    '91007' => ['state' => 'CA', 'city' => 'Arcadia'],
    '91008' => ['state' => 'CA', 'city' => 'Duarte'],
    '91009' => ['state' => 'CA', 'city' => 'Duarte'],
    '91010' => ['state' => 'CA', 'city' => 'Duarte'],
    '91011' => ['state' => 'CA', 'city' => 'La Canada Flintridge'],
    '91012' => ['state' => 'CA', 'city' => 'La Canada Flintridge'],
    '91016' => ['state' => 'CA', 'city' => 'Monrovia'],
    '91017' => ['state' => 'CA', 'city' => 'Monrovia'],
    '91020' => ['state' => 'CA', 'city' => 'Montrose'],
    '91021' => ['state' => 'CA', 'city' => 'Montrose'],
    '91023' => ['state' => 'CA', 'city' => 'Mount Wilson'],
    '91024' => ['state' => 'CA', 'city' => 'Sierra Madre'],
    '91025' => ['state' => 'CA', 'city' => 'Sierra Madre'],
    '91030' => ['state' => 'CA', 'city' => 'South Pasadena'],
    '91031' => ['state' => 'CA', 'city' => 'South Pasadena'],
    '91040' => ['state' => 'CA', 'city' => 'Sunland'],
    '91041' => ['state' => 'CA', 'city' => 'Sunland'],
    '91042' => ['state' => 'CA', 'city' => 'Tujunga'],
    '91043' => ['state' => 'CA', 'city' => 'Tujunga'],
    '91046' => ['state' => 'CA', 'city' => 'Verdugo City'],
    '91066' => ['state' => 'CA', 'city' => 'Arcadia'],
    '91077' => ['state' => 'CA', 'city' => 'Arcadia'],
];
