<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '91201' => ['state' => 'CA', 'city' => 'Glendale'],
    '91202' => ['state' => 'CA', 'city' => 'Glendale'],
    '91203' => ['state' => 'CA', 'city' => 'Glendale'],
    '91204' => ['state' => 'CA', 'city' => 'Glendale'],
    '91205' => ['state' => 'CA', 'city' => 'Glendale'],
    '91206' => ['state' => 'CA', 'city' => 'Glendale'],
    '91207' => ['state' => 'CA', 'city' => 'Glendale'],
    '91208' => ['state' => 'CA', 'city' => 'Glendale'],
    '91209' => ['state' => 'CA', 'city' => 'Glendale'],
    '91210' => ['state' => 'CA', 'city' => 'Glendale'],
    '91214' => ['state' => 'CA', 'city' => 'La Crescenta'],
    '91221' => ['state' => 'CA', 'city' => 'Glendale'],
    '91222' => ['state' => 'CA', 'city' => 'Glendale'],
    '91224' => ['state' => 'CA', 'city' => 'La Crescenta'],
    '91225' => ['state' => 'CA', 'city' => 'Glendale'],
    '91226' => ['state' => 'CA', 'city' => 'Glendale'],
];
