<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '91401' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91402' => ['state' => 'CA', 'city' => 'Panorama City'],
    '91403' => ['state' => 'CA', 'city' => 'Sherman Oaks'],
    '91404' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91405' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91406' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91407' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91408' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91409' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91410' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91411' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91412' => ['state' => 'CA', 'city' => 'Panorama City'],
    '91413' => ['state' => 'CA', 'city' => 'Sherman Oaks'],
    '91416' => ['state' => 'CA', 'city' => 'Encino'],
    '91423' => ['state' => 'CA', 'city' => 'Sherman Oaks'],
    '91426' => ['state' => 'CA', 'city' => 'Encino'],
    '91436' => ['state' => 'CA', 'city' => 'Encino'],
    '91470' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91482' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91495' => ['state' => 'CA', 'city' => 'Sherman Oaks'],
    '91496' => ['state' => 'CA', 'city' => 'Van Nuys'],
    '91499' => ['state' => 'CA', 'city' => 'Van Nuys'],
];
