<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '91501' => ['state' => 'CA', 'city' => 'Burbank'],
    '91502' => ['state' => 'CA', 'city' => 'Burbank'],
    '91503' => ['state' => 'CA', 'city' => 'Burbank'],
    '91504' => ['state' => 'CA', 'city' => 'Burbank'],
    '91505' => ['state' => 'CA', 'city' => 'Burbank'],
    '91506' => ['state' => 'CA', 'city' => 'Burbank'],
    '91507' => ['state' => 'CA', 'city' => 'Burbank'],
    '91508' => ['state' => 'CA', 'city' => 'Burbank'],
    '91510' => ['state' => 'CA', 'city' => 'Burbank'],
    '91521' => ['state' => 'CA', 'city' => 'Burbank'],
    '91522' => ['state' => 'CA', 'city' => 'Burbank'],
    '91523' => ['state' => 'CA', 'city' => 'Burbank'],
    '91526' => ['state' => 'CA', 'city' => 'Burbank'],
];
