<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '92401' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92402' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92403' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92404' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92405' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92406' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92407' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92408' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92410' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92411' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92413' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92415' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92418' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92423' => ['state' => 'CA', 'city' => 'San Bernardino'],
    '92427' => ['state' => 'CA', 'city' => 'San Bernardino'],
];
