<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '94801' => ['state' => 'CA', 'city' => 'Richmond'],
    '94802' => ['state' => 'CA', 'city' => 'Richmond'],
    '94803' => ['state' => 'CA', 'city' => 'El Sobrante'],
    '94804' => ['state' => 'CA', 'city' => 'Richmond'],
    '94805' => ['state' => 'CA', 'city' => 'Richmond'],
    '94806' => ['state' => 'CA', 'city' => 'San Pablo'],
    '94807' => ['state' => 'CA', 'city' => 'Richmond'],
    '94808' => ['state' => 'CA', 'city' => 'Richmond'],
    '94820' => ['state' => 'CA', 'city' => 'El Sobrante'],
    '94850' => ['state' => 'CA', 'city' => 'Richmond'],
];
