<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '96910' => ['state' => 'GU', 'city' => 'Hagatna'],
    '96911' => ['state' => 'GU', 'city' => 'Tamuning'],
    '96912' => ['state' => 'GU', 'city' => 'Dededo'],
    '96913' => ['state' => 'GU', 'city' => 'Barrigada'],
    '96914' => ['state' => 'GU', 'city' => 'Yona'],
    '96915' => ['state' => 'GU', 'city' => 'Santa Rita'],
    '96916' => ['state' => 'GU', 'city' => 'Merizo'],
    '96917' => ['state' => 'GU', 'city' => 'Inarajan'],
    '96918' => ['state' => 'GU', 'city' => 'Umatac'],
    '96919' => ['state' => 'GU', 'city' => 'Agana Heights'],
    '96921' => ['state' => 'GU', 'city' => 'Barrigada'],
    '96922' => ['state' => 'GU', 'city' => 'Asan'],
    '96923' => ['state' => 'GU', 'city' => 'Mangilao'],
    '96925' => ['state' => 'GU', 'city' => 'Piti'],
    '96926' => ['state' => 'GU', 'city' => 'Sinajana'],
    '96927' => ['state' => 'GU', 'city' => 'Mongmong'],
    '96928' => ['state' => 'GU', 'city' => 'Agat'],
    '96929' => ['state' => 'GU', 'city' => 'Yigo'],
    '96930' => ['state' => 'GU', 'city' => 'Talofofo'],
    '96931' => ['state' => 'GU', 'city' => 'Tamuning'],
    '96932' => ['state' => 'GU', 'city' => 'Hagatna'],
    '96950' => ['state' => 'MP', 'city' => 'Saipan'],
    '96951' => ['state' => 'MP', 'city' => 'Rota'],
    '96952' => ['state' => 'MP', 'city' => 'Tinian'],
];
