<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '97501' => ['state' => 'OR', 'city' => 'Medford'],
    '97502' => ['state' => 'OR', 'city' => 'Central Point'],
    '97503' => ['state' => 'OR', 'city' => 'White City'],
    '97504' => ['state' => 'OR', 'city' => 'Medford'],
    '97520' => ['state' => 'OR', 'city' => 'Ashland'],
    '97522' => ['state' => 'OR', 'city' => 'Butte Falls'],
    '97523' => ['state' => 'OR', 'city' => 'Cave Junction'],
    '97524' => ['state' => 'OR', 'city' => 'Eagle Point'],
    '97525' => ['state' => 'OR', 'city' => 'Gold Hill'],
    '97526' => ['state' => 'OR', 'city' => 'Grants Pass'],
    '97527' => ['state' => 'OR', 'city' => 'Grants Pass'],
    '97528' => ['state' => 'OR', 'city' => 'Grants Pass'],
    '97530' => ['state' => 'OR', 'city' => 'Jacksonville'],
    '97531' => ['state' => 'OR', 'city' => 'Kerby'],
    '97532' => ['state' => 'OR', 'city' => 'Merlin'],
    '97533' => ['state' => 'OR', 'city' => 'Murphy'],
    '97534' => ['state' => 'OR', 'city' => 'O Brien'],
    '97535' => ['state' => 'OR', 'city' => 'Phoenix'],
    '97536' => ['state' => 'OR', 'city' => 'Prospect'],
    '97537' => ['state' => 'OR', 'city' => 'Rogue River'],
    '97538' => ['state' => 'OR', 'city' => 'Selma'],
    '97539' => ['state' => 'OR', 'city' => 'Shady Cove'],
    '97540' => ['state' => 'OR', 'city' => 'Talent'],
    '97541' => ['state' => 'OR', 'city' => 'Trail'],
    '97543' => ['state' => 'OR', 'city' => 'Wilderville'],
    '97544' => ['state' => 'OR', 'city' => 'Williams'],
];
