<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '97601' => ['state' => 'OR', 'city' => 'Klamath Falls'],
    '97602' => ['state' => 'OR', 'city' => 'Klamath Falls'],
    '97603' => ['state' => 'OR', 'city' => 'Klamath Falls'],
    '97604' => ['state' => 'OR', 'city' => 'Crater Lake'],
    '97620' => ['state' => 'OR', 'city' => 'Adel'],
    '97621' => ['state' => 'OR', 'city' => 'Beatty'],
    '97622' => ['state' => 'OR', 'city' => 'Bly'],
    '97623' => ['state' => 'OR', 'city' => 'Bonanza'],
    '97624' => ['state' => 'OR', 'city' => 'Chiloquin'],
    '97625' => ['state' => 'OR', 'city' => 'Dairy'],
    '97626' => ['state' => 'OR', 'city' => 'Fort Klamath'],
    '97627' => ['state' => 'OR', 'city' => 'Keno'],
    '97630' => ['state' => 'OR', 'city' => 'Lakeview'],
    '97632' => ['state' => 'OR', 'city' => 'Malin'],
    '97633' => ['state' => 'OR', 'city' => 'Merrill'],
    '97634' => ['state' => 'OR', 'city' => 'Midland'],
    '97635' => ['state' => 'OR', 'city' => 'New Pine Creek'],
    '97636' => ['state' => 'OR', 'city' => 'Paisley'],
    '97637' => ['state' => 'OR', 'city' => 'Plush'],
    '97638' => ['state' => 'OR', 'city' => 'Silver Lake'],
    '97639' => ['state' => 'OR', 'city' => 'Sprague River'],
    '97640' => ['state' => 'OR', 'city' => 'Summer Lake'],
    '97641' => ['state' => 'OR', 'city' => 'Christmas Valley'],
];
