<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '97901' => ['state' => 'OR', 'city' => 'Adrian'],
    '97902' => ['state' => 'OR', 'city' => 'Arock'],
    '97903' => ['state' => 'OR', 'city' => 'Brogan'],
    '97904' => ['state' => 'OR', 'city' => 'Drewsey'],
    '97905' => ['state' => 'OR', 'city' => 'Durkee'],
    '97906' => ['state' => 'OR', 'city' => 'Harper'],
    '97907' => ['state' => 'OR', 'city' => 'Huntington'],
    '97908' => ['state' => 'OR', 'city' => 'Ironside'],
    '97909' => ['state' => 'OR', 'city' => 'Jamieson'],
    '97910' => ['state' => 'OR', 'city' => 'Jordan Valley'],
    '97911' => ['state' => 'OR', 'city' => 'Juntura'],
    '97913' => ['state' => 'OR', 'city' => 'Nyssa'],
    '97914' => ['state' => 'OR', 'city' => 'Ontario'],
    '97917' => ['state' => 'OR', 'city' => 'Riverside'],
    '97918' => ['state' => 'OR', 'city' => 'Vale'],
    '97920' => ['state' => 'OR', 'city' => 'Westfall'],
];
