<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '99401' => ['state' => 'WA', 'city' => 'Anatone'],
    '99402' => ['state' => 'WA', 'city' => 'Asotin'],
    '99403' => ['state' => 'WA', 'city' => 'Clarkston'],
];
