<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '99801' => ['state' => 'AK', 'city' => 'Juneau'],
    '99802' => ['state' => 'AK', 'city' => 'Juneau'],
    '99803' => ['state' => 'AK', 'city' => 'Juneau'],
    '99811' => ['state' => 'AK', 'city' => 'Juneau'],
    '99812' => ['state' => 'AK', 'city' => 'Juneau'],
    '99820' => ['state' => 'AK', 'city' => 'Angoon'],
    '99821' => ['state' => 'AK', 'city' => 'Auke Bay'],
    '99824' => ['state' => 'AK', 'city' => 'Douglas'],
    '99825' => ['state' => 'AK', 'city' => 'Elfin Cove'],
    '99826' => ['state' => 'AK', 'city' => 'Gustavus'],
    '99827' => ['state' => 'AK', 'city' => 'Haines'],
    '99829' => ['state' => 'AK', 'city' => 'Hoonah'],
    '99830' => ['state' => 'AK', 'city' => 'Kake'],
    '99832' => ['state' => 'AK', 'city' => 'Pelican'],
    '99833' => ['state' => 'AK', 'city' => 'Petersburg'],
    '99835' => ['state' => 'AK', 'city' => 'Sitka'],
    '99836' => ['state' => 'AK', 'city' => 'Port Alexander'],
    '99840' => ['state' => 'AK', 'city' => 'Skagway'],
    '99841' => ['state' => 'AK', 'city' => 'Tenakee Springs'],
    '99850' => ['state' => 'AK', 'city' => 'Juneau'],
];
