<?php

// Generated by bin/generate-postal-code-data.php - do not edit by hand. Sources and licences: NOTICE.md

return [
    '99901' => ['state' => 'AK', 'city' => 'Ketchikan'],
    '99903' => ['state' => 'AK', 'city' => 'Meyers Chuck'],
    '99918' => ['state' => 'AK', 'city' => 'Coffman Cove'],
    '99919' => ['state' => 'AK', 'city' => 'Thorne Bay'],
    '99921' => ['state' => 'AK', 'city' => 'Craig'],
    '99922' => ['state' => 'AK', 'city' => 'Hydaburg'],
    '99923' => ['state' => 'AK', 'city' => 'Hyder'],
    '99925' => ['state' => 'AK', 'city' => 'Klawock'],
    '99926' => ['state' => 'AK', 'city' => 'Metlakatla'],
    '99927' => ['state' => 'AK', 'city' => 'Point Baker'],
    '99928' => ['state' => 'AK', 'city' => 'Ward Cove'],
    '99929' => ['state' => 'AK', 'city' => 'Wrangell'],
    '99950' => ['state' => 'AK', 'city' => 'Ketchikan'],
];
